### ISSUE TITLE
下载的程序被报windows defender 报毒了

### ISSUE THREAD

**Issue by somewheve** [FQrabbit/SSTap-Rule#105]
作者的源程序是官网下的吗 emmmm

**Comment by AmazingDM** [comment]
https://github.com/FQrabbit/SSTap-Rule/releases/tag/%E5%8E%BB%E5%B9%BF%E5%91%8A%E7%89%88%E6%9C%AC%E7%9A%841.0.9.7

http://r.virscan.org/language/zh-cn/report/6da93d7251fb3ab7c1de69524bed670a
