### ISSUE TITLE
epic平台与堡垒之夜规则外服规则

### ISSUE THREAD

**Issue by esen-biaobiao** [FQrabbit/SSTap-Rule#109]
**需要增加游戏\程序名字**
如``epic平台规则与堡垒之夜外服规则``

**该游戏\程序的运行环境**
``PC``

**该游戏\程序哪部分需要代理**
``整个游戏\程序都需要``

**特殊情况**
如果还有特殊想说明的请在这里描述.

**Comment by AmazingDM** [comment]
亚服已添加 待测试
