### ISSUE TITLE
does some can add a black desert rules(korea,taiwan,steam)?

### ISSUE THREAD

**Issue by xishijt** [FQrabbit/SSTap-Rule#116]
**需要增加游戏\程序名字**
 Daum Games Black Desert

**该游戏\程序的运行环境**
``PC``

**该游戏\程序哪部分需要代理**
如
the game needed proxy,several exe

**特殊情况**
如果还有特殊想说明的请在这里描述.
korea need web page to log in.

**Comment by Filterrr** [comment]
> **需要增加游戏\程序名字**
> Daum Games Black Desert
> 
> **该游戏\程序的运行环境**
> `PC`
> 
> **该游戏\程序哪部分需要代理**
> 如
> 游戏需要代理，几个exe
> 
> **情况特殊**
> 如果还有特殊想说明的请在这里描述。
> 韩国需要网页登录。


[Black-Desert.zip](https://github.com/FQrabbit/SSTap-Rule/files/2801213/Black-Desert.zip)
拿去

**Comment by xishijt** [comment]
> > **需要增加游戏\程序名字**
> > Daum Games Black Desert
> > **该游戏\程序的运行环境**
> > `PC`
> > **该游戏\程序哪部分需要代理**
> > 如
> > 游戏需要代理，几个exe
> > **情况特殊**
> > 如果还有特殊想说明的请在这里描述。
> > 韩国需要网页登录。
> 
> [Black-Desert.zip](https://github.com/FQrabbit/SSTap-Rule/files/2801213/Black-Desert.zip)
> 拿去

可以的,大部分时间能用,有时候连不上 必须开全局,可能是IP不全
