### ISSUE TITLE
路由转SSTAP规则工具没有输出

### ISSUE THREAD

**Issue by strange-life** [FQrabbit/SSTap-Rule#119]
**问题描述**
复制了 route.txt 到页面上点击转换没有结果

**从哪里开始出现这个问题**

**截图**
如果可以，请添加截图以帮助解释您的问题.
![image](https://user-images.githubusercontent.com/19758341/50546483-462a8c80-0c63-11e9-950a-9d7a8de70c60.png)

**运行环境**
![image](https://user-images.githubusercontent.com/19758341/50546502-8d188200-0c63-11e9-9671-e28a73fa8161.png)

**Comment by AmazingDM** [comment]
能提供一下route.txt的内容吗

**Comment by AmazingDM** [comment]
你是不是加速模式选错了，此路由表没有可加速的公共IP

**Comment by strange-life** [comment]
我是根据教程选的模式一二，是不是试用账号不行要VIP

**Comment by FQrabbit** [comment]
@AmazingDM 🌚

**Comment by AmazingDM** [comment]
提供一下加速游戏的名称吧我去试试

**Comment by strange-life** [comment]
网易uu的荣耀战魂

**Comment by AmazingDM** [comment]
正确姿势：
![image](https://user-images.githubusercontent.com/10679055/50562268-941bbf00-0d4d-11e9-8833-998cb729b7d2.png)

![image](https://user-images.githubusercontent.com/10679055/50562279-a4cc3500-0d4d-11e9-94dd-b0be67f12b33.png)

3.112.0.0/16
13.112.0.0/16
13.228.0.0/16
13.230.0.0/16
13.250.0.0/16
13.250.244.21/32
18.136.199.0/24
18.136.212.0/24
18.179.0.0/16
18.179.147.209/32
18.182.0.0/16
18.236.248.0/24
23.2.16.0/24
27.0.0.0/4
34.192.65.0/24
34.199.243.0/24
34.206.170.0/24
34.208.0.0/16
34.230.70.0/24
34.250.212.0/24
34.250.254.0/24
36.234.126.0/24
43.230.88.0/24
43.250.192.0/24
43.250.193.0/24
46.51.216.0/24
46.51.224.0/24
46.137.192.0/24
46.137.224.0/24
52.1.0.0/16
52.4.200.0/24
52.10.101.0/24
52.18.177.0/24
52.20.101.0/24
52.20.229.0/24
52.23.82.0/24
52.44.90.0/24
52.45.39.0/24
52.45.82.0/24
52.45.125.0/24
52.49.15.0/24
52.54.0.0/16
52.54.17.0/24
52.54.18.0/24
52.54.19.0/24
52.55.72.0/24
52.55.174.0/24
52.68.0.0/16
52.73.106.0/24
52.74.0.0/16
52.76.0.0/16
52.76.128.0/24
52.77.0.0/16
52.84.193.0/24
52.92.56.0/24
52.92.60.0/24
52.92.80.0/24
52.93.8.0/24
52.94.8.0/24
52.94.11.0/24
52.94.198.96/32
52.94.198.111/32
52.94.200.0/24
52.94.248.32/32
52.94.248.47/32
52.94.248.80/32
52.94.248.95/32
52.95.30.0/24
52.95.34.0/24
52.95.35.0/24
52.95.56.0/24
52.95.212.0/24
52.95.242.0/24
52.95.243.0/24
52.95.255.32/32
52.95.255.47/32
52.95.255.48/32
52.95.255.63/32
52.119.184.0/24
52.119.205.0/24
52.119.216.0/24
52.192.0.0/16
52.194.0.0/16
52.196.0.0/16
52.203.65.0/24
52.206.154.0/24
52.206.157.0/24
52.210.167.0/24
52.211.184.0/24
52.212.89.0/24
52.212.225.0/24
52.216.0.0/16
52.216.1.0/24
52.216.16.0/24
52.216.17.0/24
52.216.32.0/24
52.216.64.0/24
52.216.65.0/24
52.216.66.0/24
52.216.80.0/24
52.216.81.0/24
52.216.82.0/24
52.216.224.0/24
52.216.225.0/24
52.216.226.0/24
52.216.227.0/24
52.219.0.0/16
52.219.16.0/24
52.219.32.0/24
52.219.40.0/24
52.219.68.0/24
52.219.76.0/24
52.220.0.0/16
52.222.238.0/24
52.229.171.0/24
54.64.0.0/16
54.87.184.0/24
54.87.186.0/24
54.87.231.0/24
54.88.90.0/24
54.92.0.0/16
54.95.0.0/16
54.144.188.0/24
54.150.0.0/16
54.151.128.0/24
54.154.49.0/24
54.165.27.0/24
54.168.0.0/16
54.169.0.0/16
54.171.55.0/24
54.172.0.0/16
54.178.0.0/16
54.179.0.0/16
54.182.4.0/24
54.192.151.0/24
54.194.67.0/24
54.199.0.0/16
54.202.0.0/16
54.210.80.0/24
54.218.57.0/24
54.229.122.0/24
54.230.73.0/24
54.231.11.0/24
54.231.33.0/24
54.231.40.0/24
54.231.41.0/24
54.231.48.0/24
54.231.49.0/24
54.231.50.0/24
54.231.72.0/24
54.231.80.0/24
54.231.81.0/24
54.231.82.0/24
54.231.83.0/24
54.231.98.0/24
54.231.113.0/24
54.231.114.0/24
54.231.120.0/24
54.231.224.0/24
54.231.240.0/24
54.236.0.0/16
54.238.0.0/16
54.239.0.80/32
54.239.0.95/32
54.239.0.96/32
54.239.0.111/32
54.239.52.0/24
54.239.96.0/24
54.240.199.0/24
54.240.200.0/24
54.240.225.0/24
54.240.226.0/24
54.240.227.0/24
54.248.0.0/16
54.250.0.0/16
54.251.0.0/16
54.254.0.0/16
54.255.0.0/16
58.151.132.0/24
61.213.168.0/24
61.213.171.0/24
65.200.22.0/24
65.216.231.0/24
65.222.200.0/24
103.4.8.0/24
103.4.12.0/24
103.10.124.0/24
103.28.54.0/24
103.38.255.0/24
103.246.148.0/24
103.246.150.0/24
118.217.76.0/24
119.81.245.0/24
119.205.127.0/24
122.248.192.0/24
130.105.224.0/24
149.202.223.0/24
153.254.86.0/24
155.133.245.0/24
163.53.89.235/32
175.41.128.0/24
175.41.192.0/24
176.32.64.0/24
176.34.0.0/16
176.34.32.0/24
180.176.105.0/24
184.24.26.0/24
184.24.155.0/24
184.24.195.0/24
184.24.223.0/24
184.25.19.0/24
184.25.61.0/24
184.25.158.0/24
184.25.221.0/24
184.25.243.0/24
184.25.253.0/24
184.26.22.0/24
184.26.84.0/24
184.26.114.0/24
184.26.120.0/24
184.26.141.0/24
184.26.221.0/24
184.27.239.0/24
184.28.37.0/24
184.28.38.0/24
184.28.69.0/24
184.28.79.0/24
184.28.154.0/24
184.28.156.0/24
184.28.162.0/24
184.28.238.0/24
184.28.245.0/24
184.29.59.0/24
184.29.108.0/24
184.30.20.0/24
184.30.226.0/24
184.31.201.0/24
184.50.2.0/24
184.50.87.0/24
184.50.163.0/24
184.51.15.0/24
184.51.17.0/24
184.84.168.0/24
184.85.67.0/24
184.85.120.0/24
184.85.244.0/24
184.86.20.0/24
184.86.105.0/24
184.86.108.0/24
184.86.122.0/24
184.86.171.0/24
184.86.232.0/24
184.87.121.0/24
184.87.197.0/24
202.111.128.0/24
202.182.224.0/24
203.83.220.0/24
203.107.128.0/24
203.131.240.0/24
203.243.7.0/24
205.196.6.0/24
210.72.128.0/24
212.84.41.0/24
216.98.48.0/24
216.98.54.0/24
216.98.55.0/24
216.98.58.0/24
216.98.60.0/24
216.98.62.0/24
216.98.99.0/24
218.98.128.0/24
218.104.128.0/24
219.149.128.0/24
221.11.128.0/24
221.12.128.0/24
222.249.128.0/24
223.119.206.0/24
223.119.217.0/24
223.255.128.0/24

**Comment by strange-life** [comment]
非常感谢🙏

**Comment by nijiasha** [comment]
下载链接已经没了
