### ISSUE TITLE
请求添加 MU2/奇迹：传奇 国际服规则

### ISSUE THREAD

**Issue by ShadyWhite** [FQrabbit/SSTap-Rule#126]
需要增加游戏\程序名字
MU2/奇迹:传奇/MU:Legend

该游戏\程序的运行环境
PC

该游戏\程序哪部分需要代理
整个游戏都需要,登录器也需要

特殊情况
暂无

**Comment by youdeoo** [comment]
美服.日服,东南亚服

**Comment by youdeoo** [comment]
规则已经添加
