### ISSUE TITLE
请求增加 美国卡车模拟 规则

### ISSUE THREAD

**Issue by shaguaphm** [FQrabbit/SSTap-Rule#129]
**需要增加游戏\程序名字**
``美国卡车模拟（American Truck Simulator）``

**该游戏\程序的运行环境**
``PC``

**该游戏\程序哪部分需要代理**
``只代理登陆部分（插件服务器）``

**特殊情况**
欧服和美服

**Comment by youdeoo** [comment]
规则已添加!
