### ISSUE TITLE
希望有好心人能添加一下steam游戏Dirty bomb的规则

### ISSUE THREAD

**Issue by Zeddddd** [FQrabbit/SSTap-Rule#15]
跪谢跪谢了！或者发一篇添加规则的教程

**Comment by FQrabbit** [comment]
有人提交了规则，但未经过测试，您可以到[测试分支](https://github.com/FQrabbit/SSTap-Rule/blob/Test/rules/Dirty-Bomb.rules)查看测试版本的规则
