### ISSUE TITLE
黑色沙漠规则感觉需要更新了,偶尔会出现连不上的情况,必须开全局

### ISSUE THREAD

**Issue by xishijt** [FQrabbit/SSTap-Rule#153]
**需要增加游戏\程序名字**
黑色沙漠

**该游戏\程序的运行环境**
PC

**该游戏\程序哪部分需要代理**
如
`整个游戏\程序都需要`

**特殊情况**
如果还有特殊想说明的请在这里描述.需要更新,台服可能又加新的服务器了

**Comment by jungeshiyong** [comment]
顶一顶
