### ISSUE TITLE
寻求一份bluestacks（蓝叠模拟器国际版）的规则

### ISSUE THREAD

**Issue by nuoicom** [FQrabbit/SSTap-Rule#160]
蓝叠模拟器国际版（4）

PC

`整个游戏\程序都需要`

**Comment by nuoicom** [comment]
> 蓝叠加速器国际版
> 
> PC
> 
> `整个游戏\程序都需要`

**Comment by nuoicom** [comment]
> 蓝叠加速器国际版
> 
> PC
> 
> `整个游戏\程序都需要`

**Comment by nuoicom** [comment]
找傻了，字都全打错😶

**Comment by FQrabbit** [comment]
@nuoicom 模拟器里面安装纸飞机不行么🌚
