### ISSUE TITLE
 请求全境封锁2新增规则

### ISSUE THREAD

**Issue by JacyJam** [FQrabbit/SSTap-Rule#162]
**需要增加游戏\程序名字**
``全境封锁2``

**该游戏\程序的运行环境**
``PC``

**该游戏\程序哪部分需要代理**
``整个游戏\程序都需要``

**Comment by Bourshevik0** [comment]
全境封锁2在网易UU里只有模式4的节点，无法根据教程提取规则。(wireshark或者别的加速器提取请)

**Comment by zymgg** [comment]
#Tom clancy's The Division 2,全境封锁2,0,0,1,0,1,0,By-ZYM
3.82.84.0/24
3.82.123.0/24
3.208.56.0/24
5.200.3.0/24
5.200.8.0/24
23.2.16.0/24
23.45.158.0/24
23.46.211.0/24
23.48.32.0/24
23.57.66.0/24
23.57.114.0/24
23.78.217.0/24
23.200.142.0/24
34.85.0.0/16
34.226.97.0/24
34.251.147.0/24
34.252.216.0/24
35.156.40.0/24
35.184.0.0/16
35.186.170.0/24
35.188.0.0/16
35.189.0.0/16
35.192.0.0/16
35.197.160.0/24
35.198.0.0/16
35.199.64.0/24
35.200.0.0/16
35.200.149.0/24
35.201.0.0/16
35.204.0.0/16
35.205.0.0/16
35.220.128.0/24
35.221.64.0/24
35.228.0.0/16
35.233.0.0/16
35.235.64.0/24
35.236.0.0/16
35.236.192.0/24
35.240.0.0/16
35.241.64.0/24
35.243.64.0/24
35.244.64.0/24
35.245.0.0/16
43.239.137.0/24
52.53.89.0/24
52.199.165.0/24
54.87.78.0/24
54.158.229.0/24
103.194.166.0/24
103.194.167.0/24
104.17.197.0/24
104.17.198.0/24
104.153.86.0/24
104.154.185.0/24
104.198.84.0/24
104.199.0.0/16
109.200.213.0/24
117.52.35.0/24
138.128.137.0/24
146.148.92.0/24
146.148.104.0/24
152.195.61.0/24
153.254.86.0/24
162.244.53.0/24
184.25.238.0/24
185.50.107.0/24
185.179.203.0/24
188.122.81.0/24
192.158.31.0/24
213.179.196.0/24
216.98.54.0/24
216.98.56.0/24
216.98.62.0/24
34.197.26.232/32
208.185.115.113/32
208.185.115.128/32
自己提取的不知道是否可用，保存使用看看

**Comment by MrCutey** [comment]
> #Tom clancy's The Division 2,全境封锁2,0,0,1,0,1,0,By-ZYM
> 3.82.84.0/24
> 3.82.123.0/24
> 3.208.56.0/24
> 5.200.3.0/24
> 5.200.8.0/24
> 23.2.16.0/24
> 23.45.158.0/24
> 23.46.211.0/24
> 23.48.32.0/24
> 23.57.66.0/24
> 23.57.114.0/24
> 23.78.217.0/24
> 23.200.142.0/24
> 34.85.0.0/16
> 34.226.97.0/24
> 34.251.147.0/24
> 34.252.216.0/24
> 35.156.40.0/24
> 35.184.0.0/16
> 35.186.170.0/24
> 35.188.0.0/16
> 35.189.0.0/16
> 35.192.0.0/16
> 35.197.160.0/24
> 35.198.0.0/16
> 35.199.64.0/24
> 35.200.0.0/16
> 35.200.149.0/24
> 35.201.0.0/16
> 35.204.0.0/16
> 35.205.0.0/16
> 35.220.128.0/24
> 35.221.64.0/24
> 35.228.0.0/16
> 35.233.0.0/16
> 35.235.64.0/24
> 35.236.0.0/16
> 35.236.192.0/24
> 35.240.0.0/16
> 35.241.64.0/24
> 35.243.64.0/24
> 35.244.64.0/24
> 35.245.0.0/16
> 43.239.137.0/24
> 52.53.89.0/24
> 52.199.165.0/24
> 54.87.78.0/24
> 54.158.229.0/24
> 103.194.166.0/24
> 103.194.167.0/24
> 104.17.197.0/24
> 104.17.198.0/24
> 104.153.86.0/24
> 104.154.185.0/24
> 104.198.84.0/24
> 104.199.0.0/16
> 109.200.213.0/24
> 117.52.35.0/24
> 138.128.137.0/24
> 146.148.92.0/24
> 146.148.104.0/24
> 152.195.61.0/24
> 153.254.86.0/24
> 162.244.53.0/24
> 184.25.238.0/24
> 185.50.107.0/24
> 185.179.203.0/24
> 188.122.81.0/24
> 192.158.31.0/24
> 213.179.196.0/24
> 216.98.54.0/24
> 216.98.56.0/24
> 216.98.62.0/24
> 34.197.26.232/32
> 208.185.115.113/32
> 208.185.115.128/32
> 自己提取的不知道是否可用，保存使用看看

大佬，香港google的服务器没有IP，加速不了

**Comment by partment** [comment]
從Mudfish中提取出來的，用用看

#Tom clancy's The Division 2,全境封锁 2,0,0,1,0,1,0,By-PartMent
25.0.0.1/32
25.42.169.109/32
3.0.0.0/4
5.200.8.128/32
13.228.0.0/16
13.232.0.0/16
18.128.0.0/16
25.0.0.0/4
34.64.0.0/16
34.192.0.0/16
35.152.0.0/16
35.160.0.0/16
35.176.0.0/16
35.192.0.0/16
35.208.0.0/16
35.224.0.0/16
35.240.0.0/16
43.239.136.0/24
52.32.0.0/16
52.84.0.0/16
52.88.0.0/16
54.72.0.0/16
54.80.0.0/16
54.160.0.0/16
54.224.0.0/16
103.102.160.0/24
103.194.164.0/24
104.153.84.0/24
104.196.0.0/16
109.200.212.0/24
138.128.136.0/24
162.244.52.0/24
162.245.204.0/24
185.50.104.0/24
185.50.106.0/24
185.179.203.0/24
187.179.0.0/16
188.122.80.0/24
216.98.48.0/24

**Comment by yuchenshuize** [comment]
> #Tom clancy's The Division 2,全境封锁2,0,0,1,0,1,0,By-ZYM
> 3.82.84.0/24
> 3.82.123.0/24
> 3.208.56.0/24
> 5.200.3.0/24
> 5.200.8.0/24
> 23.2.16.0/24
> 23.45.158.0/24
> 23.46.211.0/24
> 23.48.32.0/24
> 23.57.66.0/24
> 23.57.114.0/24
> 23.78.217.0/24
> 23.200.142.0/24
> 34.85.0.0/16
> 34.226.97.0/24
> 34.251.147.0/24
> 34.252.216.0/24
> 35.156.40.0/24
> 35.184.0.0/16
> 35.186.170.0/24
> 35.188.0.0/16
> 35.189.0.0/16
> 35.192.0.0/16
> 35.197.160.0/24
> 35.198.0.0/16
> 35.199.64.0/24
> 35.200.0.0/16
> 35.200.149.0/24
> 35.201.0.0/16
> 35.204.0.0/16
> 35.205.0.0/16
> 35.220.128.0/24
> 35.221.64.0/24
> 35.228.0.0/16
> 35.233.0.0/16
> 35.235.64.0/24
> 35.236.0.0/16
> 35.236.192.0/24
> 35.240.0.0/16
> 35.241.64.0/24
> 35.243.64.0/24
> 35.244.64.0/24
> 35.245.0.0/16
> 43.239.137.0/24
> 52.53.89.0/24
> 52.199.165.0/24
> 54.87.78.0/24
> 54.158.229.0/24
> 103.194.166.0/24
> 103.194.167.0/24
> 104.17.197.0/24
> 104.17.198.0/24
> 104.153.86.0/24
> 104.154.185.0/24
> 104.198.84.0/24
> 104.199.0.0/16
> 109.200.213.0/24
> 117.52.35.0/24
> 138.128.137.0/24
> 146.148.92.0/24
> 146.148.104.0/24
> 152.195.61.0/24
> 153.254.86.0/24
> 162.244.53.0/24
> 184.25.238.0/24
> 185.50.107.0/24
> 185.179.203.0/24
> 188.122.81.0/24
> 192.158.31.0/24
> 213.179.196.0/24
> 216.98.54.0/24
> 216.98.56.0/24
> 216.98.62.0/24
> 34.197.26.232/32
> 208.185.115.113/32
> 208.185.115.128/32
> 自己提取的不知道是否可用，保存使用看看

整合大佬和另一位大佬partment的，还是没有谷歌香港的IP，加速不了谷歌香港的，请求大佬添加

**Comment by Askwind** [comment]
> > #Tom clancy's The Division 2,全境封锁2,0,0,1,0,1,0,By-ZYM
> > 3.82.84.0/24
> > 3.82.123.0/24
> > 3.208.56.0/24
> > 5.200.3.0/24
> > 5.200.8.0/24
> > 23.2.16.0/24
> > 23.45.158.0/24
> > 23.46.211.0/24
> > 23.48.32.0/24
> > 23.57.66.0/24
> > 23.57.114.0/24
> > 23.78.217.0/24
> > 23.200.142.0/24
> > 34.85.0.0/16
> > 34.226.97.0/24
> > 34.251.147.0/24
> > 34.252.216.0/24
> > 35.156.40.0/24
> > 35.184.0.0/16
> > 35.186.170.0/24
> > 35.188.0.0/16
> > 35.189.0.0/16
> > 35.192.0.0/16
> > 35.197.160.0/24
> > 35.198.0.0/16
> > 35.199.64.0/24
> > 35.200.0.0/16
> > 35.200.149.0/24
> > 35.201.0.0/16
> > 35.204.0.0/16
> > 35.205.0.0/16
> > 35.220.128.0/24
> > 35.221.64.0/24
> > 35.228.0.0/16
> > 35.233.0.0/16
> > 35.235.64.0/24
> > 35.236.0.0/16
> > 35.236.192.0/24
> > 35.240.0.0/16
> > 35.241.64.0/24
> > 35.243.64.0/24
> > 35.244.64.0/24
> > 35.245.0.0/16
> > 43.239.137.0/24
> > 52.53.89.0/24
> > 52.199.165.0/24
> > 54.87.78.0/24
> > 54.158.229.0/24
> > 103.194.166.0/24
> > 103.194.167.0/24
> > 104.17.197.0/24
> > 104.17.198.0/24
> > 104.153.86.0/24
> > 104.154.185.0/24
> > 104.198.84.0/24
> > 104.199.0.0/16
> > 109.200.213.0/24
> > 117.52.35.0/24
> > 138.128.137.0/24
> > 146.148.92.0/24
> > 146.148.104.0/24
> > 152.195.61.0/24
> > 153.254.86.0/24
> > 162.244.53.0/24
> > 184.25.238.0/24
> > 185.50.107.0/24
> > 185.179.203.0/24
> > 188.122.81.0/24
> > 192.158.31.0/24
> > 213.179.196.0/24
> > 216.98.54.0/24
> > 216.98.56.0/24
> > 216.98.62.0/24
> > 34.197.26.232/32
> > 208.185.115.113/32
> > 208.185.115.128/32
> > 自己提取的不知道是否可用，保存使用看看
> 
> 整合大佬和另一位大佬partment的，还是没有谷歌香港的IP，加速不了谷歌香港的，请求大佬添加

你可以直接用全局代理 + 游戏加加 分析出游戏需要的香港IP 然后自己添加上去

**Comment by LJea** [comment]
去重或转换成openvpn|cmroute规则工具 https://github.com/LJea/Route-Rule-Convert
25.42.169.109/32
13.228.0.0/16
13.232.0.0/16
18.128.0.0/16
34.64.0.0/16
34.192.0.0/16
35.152.0.0/16
35.160.0.0/16
35.176.0.0/16
35.192.0.0/16
35.208.0.0/16
35.224.0.0/16
35.240.0.0/16
43.239.136.0/24
52.32.0.0/16
52.84.0.0/16
52.88.0.0/16
54.72.0.0/16
54.80.0.0/16
54.160.0.0/16
54.224.0.0/16
103.102.160.0/24
103.194.164.0/24
104.153.84.0/24
104.196.0.0/16
109.200.212.0/24
138.128.136.0/24
162.244.52.0/24
162.245.204.0/24
185.50.104.0/24
185.50.106.0/24
185.179.203.0/24
187.179.0.0/16
188.122.80.0/24
216.98.48.0/24
3.82.84.0/24
3.82.123.0/24
5.200.3.0/24
5.200.8.0/24
23.2.16.0/24
23.45.158.0/24
23.46.211.0/24
23.48.32.0/24
23.57.66.0/24
23.57.114.0/24
23.78.217.0/24
23.200.142.0/24
34.85.0.0/16
34.226.97.0/24
34.251.147.0/24
34.252.216.0/24
35.184.0.0/16
35.188.0.0/16
35.189.0.0/16
35.198.0.0/16
35.200.0.0/16
35.201.0.0/16
35.204.0.0/16
35.205.0.0/16
35.220.128.0/24
35.228.0.0/16
35.233.0.0/16
35.235.64.0/24
35.236.0.0/16
35.241.64.0/24
35.244.64.0/24
35.245.0.0/16
43.239.137.0/24
52.53.89.0/24
52.199.165.0/24
54.87.78.0/24
54.158.229.0/24
103.194.166.0/24
103.194.167.0/24
104.17.197.0/24
104.17.198.0/24
104.153.86.0/24
104.199.0.0/16
109.200.213.0/24
117.52.35.0/24
138.128.137.0/24
146.148.92.0/24
146.148.104.0/24
152.195.61.0/24
153.254.86.0/24
162.244.53.0/24
184.25.238.0/24
185.50.107.0/24
188.122.81.0/24
192.158.31.0/24
213.179.196.0/24
216.98.54.0/24
216.98.56.0/24
216.98.62.0/24
34.197.26.232/32
208.185.115.113/32
208.185.115.128/32
3.80.0.0/16
3.208.0.0/16
8.34.210.0/24
8.34.212.0/24
8.34.216.0/24
8.35.192.0/24
23.52.171.43/32
23.236.48.0/24
23.236.56.0/24
23.236.60.0/24
23.236.62.0/24
23.251.144.0/24
34.66.0.0/16
34.68.0.0/16
34.72.0.0/16
34.76.0.0/16
34.81.0.0/16
34.82.0.0/16
34.84.0.0/16
34.86.0.0/16
34.88.0.0/16
34.89.0.0/16
34.90.0.0/16
34.92.0.0/16
34.94.0.0/16
34.95.128.0/24
34.96.0.0/16
34.97.0.0/16
34.224.0.0/16
34.248.0.0/16
35.156.0.0/16
35.185.0.0/16
35.186.0.0/16
35.187.132.0/24
35.187.136.0/24
35.187.139.0/24
35.187.140.0/24
35.187.143.0/24
35.187.192.0/24
35.190.128.0/24
35.190.224.0/24
35.190.240.0/24
35.194.0.0/16
35.195.0.0/16
35.196.0.0/16
35.197.0.0/16
35.199.0.0/16
35.202.0.0/16
35.203.128.0/24
35.203.192.0/24
35.203.209.0/24
35.203.210.0/24
35.203.212.0/24
35.203.216.0/24
35.203.221.0/24
35.203.222.0/24
35.203.232.0/24
35.203.240.0/24
35.203.243.0/24
35.203.244.0/24
35.203.248.0/24
35.206.0.0/16
35.207.0.0/16
35.211.0.0/16
35.212.0.0/16
35.213.0.0/16
35.214.128.0/24
35.215.0.0/16
35.216.128.0/24
35.217.128.0/24
35.221.0.0/16
35.222.0.0/16
35.226.0.0/16
35.227.0.0/16
35.229.0.0/16
35.230.0.0/16
35.231.0.0/16
35.232.0.0/16
35.234.176.0/24
35.235.192.0/24
35.235.216.0/24
35.235.228.0/24
35.235.232.0/24
35.237.0.0/16
35.238.0.0/16
35.241.128.0/24
35.243.0.0/16
35.247.0.0/16
52.52.0.0/16
52.196.0.0/16
54.156.0.0/16
59.37.129.81/32
96.17.180.122/32
100.25.208.54/32
104.154.0.0/16
104.155.128.0/24
104.155.240.0/24
104.198.0.0/16
107.167.160.0/24
107.178.192.0/24
107.178.200.0/24
107.178.208.0/24
107.178.224.0/24
107.178.225.0/24
107.178.226.0/24
107.178.228.0/24
107.178.232.0/24
107.178.235.0/24
107.178.236.0/24
108.59.80.0/24
108.170.192.0/24
108.170.200.0/24
108.170.202.0/24
108.170.204.0/24
108.170.209.0/24
108.170.210.0/24
108.170.212.0/24
108.170.216.0/24
108.170.220.0/24
108.170.222.0/24
117.18.237.29/32
117.104.138.9/32
117.104.138.32/32
130.211.112.0/24
130.211.128.0/24
130.211.192.0/24
130.211.224.0/24
146.148.32.0/24
146.148.64.0/24
146.148.96.0/24
151.139.128.14/32
162.216.148.0/24
162.222.176.0/24
173.255.112.0/24
199.192.112.0/24
199.192.114.0/24
199.223.232.0/24
199.223.236.0/24
208.68.108.0/24
这是我结合了多个的规则应该很全了吧~
