### ISSUE TITLE
请求增加jump-force规则，路由转SSTAP规则工具连接无法打开，希望更换下载源

### ISSUE THREAD

**Issue by baizimujun** [FQrabbit/SSTap-Rule#171]
**需要增加游戏\程序名字**
``jump-force``

**该游戏\程序的运行环境**

``PC``

**该游戏\程序哪部分需要代理**
``整个游戏\程序都需要``
``只代理登陆部分``

**特殊情况**
路由转SSTAP规则工具 https://www.ssrtool.com/tool/routeToRules 链接打开不了

**Comment by AmazingDM** [comment]
请挂代理访问转换工具
