### ISSUE TITLE
请问有怪猎世界的规则吗

### ISSUE THREAD

**Issue by worldtree7** [FQrabbit/SSTap-Rule#177]
**需要增加游戏\程序名字**
steam平台的怪物猎人世界

**该游戏\程序的运行环境**
PC

**该游戏\程序哪部分需要代理**
整个游戏

**特殊情况**
顺便想问一下大佬，APEX英雄的规则我用起来时好时坏，vps是阿里云的香港节点，本人坐标在浙江，移动宽带，能改善嘛~

**Comment by Bourshevik0** [comment]
Apex规则已修改，看readme。
怪猎网易UU只有模式4的节点，无法根据教程提取规则。(wireshark或者别的加速器提取请)

**Comment by noir1216** [comment]
> 顶点规则已修改，看自述。
> 怪猎网易UU只有模式4的节点，无法根据教程提取规则。（Wireshark的或者别的加速器提取请）
> 问题重复，相关问题参见[＃99](https://github.com/FQrabbit/SSTap-Rule/issues/99)

请问有wireshark抓加速器规则的教程链接吗
