### ISSUE TITLE
请求大佬分享一份命运2(destiny2)的规则，多谢

### ISSUE THREAD

**Issue by fatbOy6666** [FQrabbit/SSTap-Rule#188]
**需要增加游戏\程序名字**
命运2(destiny2) 亚服

**该游戏\程序的运行环境**
``PC win10``

**该游戏\程序哪部分需要代理**
``整个游戏"

感谢各位无私的贡献

**Comment by AmazingDM** [comment]
https://github.com/FQrabbit/SSTap-Rule/blob/master/rules/Destiny2-Asia.rules
AmazingDM#4888 有空一起 🤠
