### ISSUE TITLE
关于闪退及提示找不到LibPrivoxy.dll

### ISSUE THREAD

**Issue by z19960413** [FQrabbit/SSTap-Rule#189]
**问题描述**
您好，可能我问的问题跟规则没什么关系，但还是想请教一下。
当我将我的SS配置输入后，点击测试键，SSTap程序就会自动关闭，再次打开时，提示找不到LibPrivoxy.dll，无法运行。我用另一个SS配置测试则没有问题，反复测试后，唯独第一个SS配置会一直闪退且无法再次运行

**从哪里开始出现这个问题**
SSTap本体

**截图**
![image](https://user-images.githubusercontent.com/42197156/53512043-c141df00-3afc-11e9-9c87-ed5874184d5c.png)

**运行环境**
win10

**Comment by esen-biaobiao** [comment]
@z19960413 重新安装

**Comment by z19960413** [comment]
反复重新安装好几次了，同样的问题

**Comment by esen-biaobiao** [comment]
@z19960413 安装的是官方原版吗

**Comment by z19960413** [comment]
在 https://www.sockscap64.com/zh-hans/sstap/ 下的1.1.0.1和在 https://github.com/mayunbaba2/SSTap-beta-setup 下的1.0.9.7
两个版本都是同样的问题

**Comment by esen-biaobiao** [comment]
@z19960413 你是先卸载删除干净文件之后再次安装的吗？安装1.0.9.7版

**Comment by z19960413** [comment]
是的

**Comment by esen-biaobiao** [comment]
@z19960413 群里有所有sst原版历史文件 换个版本试试吧！

**Comment by z19960413** [comment]
好的，我先试试，谢谢

**Comment by AmazingDM** [comment]
![image](https://user-images.githubusercontent.com/10679055/53535910-58c82180-3b3f-11e9-967a-1c688b6608e0.png)
nikenengques你可能缺少这个文件

[LibPrivoxy.zip](https://github.com/FQrabbit/SSTap-Rule/files/2913060/LibPrivoxy.zip)
