### ISSUE TITLE
可以添加一个英雄联盟澳服（大洋洲）加速的模式吗

### ISSUE THREAD

**Issue by WenseRainy** [FQrabbit/SSTap-Rule#191]
**英雄联盟**

**pc**

**整个游戏都需要代理**

*我现在用的不代理中国ip 延迟有130-160左右 用的是香港的节点**

**Comment by Bourshevik0** [comment]
你延迟大和规则没关系，觉得延迟大和规则有关系的话，先试试全局，不然就是无效信息。
延迟大——换节点，这才是有效的逻辑链。

**Comment by WenseRainy** [comment]
全局的话 就160延迟 还不错 就是想看看能不能出一个大洋洲的加速模式 会不会好一点 换了好几个英雄联盟的节点都是220-320的延迟

**Comment by WenseRainy** [comment]
好像很少澳服的节点吧

**Comment by Bourshevik0** [comment]
> 
> 
> 全局的话 就160延迟 还不错 就是想看看能不能出一个大洋洲的加速模式 会不会好一点 换了好几个英雄联盟的节点都是220-320的延迟

这你应该给你们的服务商提意见，规则不能改变服务器线路质量。
