### ISSUE TITLE
希望增加我的世界（Minecraft）国际版本规则

### ISSUE THREAD

**Issue by feizao520** [FQrabbit/SSTap-Rule#194]
**需要增加游戏\程序名字**
如``Minecraft`` 我的世界 官网：www.minecraft.net

**该游戏\程序的运行环境**
PC

**该游戏\程序哪部分需要代理**
游戏登陆界面，游戏内都需要代理，且是统一IP

**特殊情况**
注意，这不是我的世界网易的版本，目前网易UU 和 腾讯加速器都没有国际服版本的规则。
有规则的有：玲珑加速器 赛博加速器 奇游加速器 飞刀加速器
我尝试过教程的抓包飞刀加速器，确实也有规则，但是放进SSTAP就不可以使用，不走任何流量。
因为国际的版本是JAVA版，从正版登陆器启动出来是一个JAVA.EXE这个进程。正版登陆这个需要加速。
进游戏后点击多人游戏可以添加多人的服务器【注意：这些多人服务器都不是官方的服务器，是玩家们自己搭建的，有大有小】
所以基本上应该是要添加服务器地址：
上万人的服务器有：mc.hypixel.net （美服-芝加哥 因为他的地址也同时是服务器官网地址，有CF CDN 所以直接PING不一定是游戏地址，真实地址应该是202开头 而不是CF地址）

US.MINEPLEX.COM （美服-直接ping就是服务器地址）

play.hivemc.com 欧服 在法国ovh

https://minecraftservers.org/   这个网站可以找到更多的服务器，可以添加些热门的

玲珑加速器那些应该是直接加速的java.exe 不然不会玩任何服务器都是美服的延时

**Comment by FQrabbit** [comment]
建议你使用`proxifier`，比sstap更方便，随意开关是否代理

**Comment by feizao520** [comment]
> 建议你使用`proxifier`，比sstap更方便，随意开关是否代理

好，我去尝试下

**Comment by feizao520** [comment]
> 建议你使用`proxifier`，比sstap更方便，随意开关是否代理

我用SSTAP找到了解决方案，Minecraft的登陆界面用SSR可以过，我用SSR同节点进去游戏，在用SSTAP添加了服务器规则，发现可以成功加速

**Comment by 757321061** [comment]
> > 建议你使用`proxifier`，比sstap更方便，随意开关是否代理
> 
> 我用SSTAP找到了解决方案，的Minecraft的登陆界面用SSR可以过，我用SSR同节点进去游戏，在用SSTAP添加了服务器规则，发现可以成功加速

请问规则怎么填，是否能加我QQ告知757321061
