### ISSUE TITLE
星际战甲规则失效，开启后是全局代理的效果

### ISSUE THREAD

**Issue by h6fYe34KFSiH** [FQrabbit/SSTap-Rule#199]
开启游戏规则后，电脑所有软件都走代理了。

**Comment by h6fYe34KFSiH** [comment]
使用最新规则可解~

**Comment by h6fYe34KFSiH** [comment]
星际战甲规则，是不是有问题呢？

**Comment by NormanBB** [comment]
你好，可以帮我测试下吗？里面是我更新的规则。
[Warframe.zip](https://github.com/FQrabbit/SSTap-Rule/files/3586030/Warframe.zip)
