### ISSUE TITLE
请求添加PUBG Lite(电脑版) 泰国服或新加坡服规则

### ISSUE THREAD

**Issue by kankan666** [FQrabbit/SSTap-Rule#200]
**需要增加游戏\程序名字**
如``PUBG Lite``

**该游戏\程序的运行环境**
如
``PC``

**该游戏\程序哪部分需要代理**
如
``整个游戏\程序都需要``

**特殊情况**
如果还有特殊想说明的请在这里描述.

**Comment by XueTeng2** [comment]
笔记本想玩PUBG Lite，可惜没有规则。

**Comment by Smileeeer** [comment]
用不代理中国ip或全局也可以

**Comment by PUBGLITE** [comment]
不会上传规则。。。

**Comment by PUBGLITE** [comment]
#PUBGLite,绝地求生低配版,0,0,1,0,1,0,By-PUBGLITE
3.1.205.0/24
13.249.226.151/32
54.192.151.71/32
54.192.151.0/24
54.192.0.0/16
13.249.236.5/32
13.33.196.77/32
54.192.73.68/32
99.86.181.21/32
13.249.236.59/32
13.224.253.121/32
13.35.125.27/32
13.33.196.149/32
54.192.151.51/32
54.192.73.223/32
13.35.125.75/32
13.249.236.55/32
13.35.125.123/32
13.224.253.64/32
54.192.73.85/32
13.35.8.95/32
13.249.255.3/32
99.86.19.66/32
13.33.196.167/32
13.224.166.109/32
13.32.166.231/32
13.35.99.69/32
13.35.37.63/32
54.192.151.73/32
99.86.181.42/32
54.230.71.80/32
13.249.255.58/32
13.33.196.119/32
13.35.125.119/32
54.192.73.231/32
13.249.236.90/32
13.224.51.115/32
99.84.239.94/32
52.85.230.4/32
52.85.230.111/32
99.84.194.65/32
13.225.103.39/32
13.224.253.75/32
13.224.253.50/32
13.33.205.90/32
52.85.230.37/32
52.222.211.127/32
99.84.194.29/32
52.84.248.9/32
13.35.8.73/32
52.85.192.178/32
54.240.188.33/32
52.222.211.248/32
99.84.194.92/32
13.224.166.65/32
54.240.188.28/32
13.35.165.63/32
13.33.231.109/32
13.225.176.93/32
13.35.99.79/32
52.85.255.98/32
13.225.103.90/32
13.35.99.48/32
13.35.165.84/32
99.86.58.22/32
99.86.58.98/32
99.86.144.55/32
13.35.253.128/32
13.33.231.73/32
18.213.20.253/32
18.213.20.0/24
18.213.0.0/16
52.1.71.116/32
52.1.71.0/24
52.1.0.0/16
52.204.121.28/32
52.204.121.0/24
52.204.0.0/16
104.75.165.107/32
104.75.165.0/24
104.75.0.0/16
23.44.160.140/32
104.86.185.107/32
184.29.104.6/32
104.80.22.49/32
104.70.237.128/32
104.127.194.89/32
23.35.196.84/32
184.26.156.66/32
23.52.176.231/32
96.16.172.66/32
104.74.21.107/32
23.196.228.176/32
23.53.252.88/32
23.75.20.165/32
104.107.214.112/32
23.41.20.67/32
184.85.161.66/32
23.37.145.225/32
118.215.101.97/32
2.23.105.153/32
23.210.220.100/32
104.77.9.106/32
23.41.109.69/32
23.35.180.83/32
88.221.164.69/32
23.53.224.139/32
104.124.20.162/32
104.84.161.254/32
104.93.1.107/32
23.44.168.144/32
92.122.252.14/32
23.54.20.102/32
119.56.0.127/32
23.74.60.142/32
23.212.12.99/32
23.77.58.78/32
23.35.180.83/32
23.74.60.142/32
104.84.161.254/32
23.210.220.100/32
23.77.58.78/32
23.44.168.144/32
23.53.224.139/32
104.77.9.106/32
23.41.109.69/32
119.56.0.127/32
88.221.164.69/32
23.54.20.102/32
23.212.12.99/32
92.122.252.14/32
104.70.237.128/32
118.215.101.97/32
23.53.252.88/32
2.23.105.153/32
23.41.20.67/32
184.29.104.6/32
23.44.160.140/32
184.31.165.119/32
104.75.165.107/32
23.75.20.165/32
23.41.56.248/32
104.107.214.112/32
23.37.145.225/32
23.52.176.231/32
104.127.194.89/32
104.86.185.107/32
23.196.228.176/32
96.16.172.66/32
13.249.226.0/24
13.249.0.0/16
13.249.226.87/32
13.224.162.12/32
13.224.162.0/24
13.224.0.0/16
52.84.225.145/32
52.84.225.0/24
52.84.0.0/16
52.84.225.34/32
52.85.159.146/32
52.85.159.0/24
52.85.0.0/16
13.225.100.178/32
13.225.100.0/24
13.225.0.0/16
52.84.225.81/32
52.84.225.0/24
52.84.0.0/16
13.249.253.87/32
13.249.253.0/24
13.249.0.0/16
13.249.226.137/32
13.249.226.0/24
13.249.0.0/16
13.225.7.203/32
13.225.7.0/24
13.225.0.0/16
52.84.225.198/32
52.84.225.0/24
52.84.0.0/16
13.35.127.47/32
13.35.127.0/24
13.35.0.0/16
13.35.127.214/32
13.33.4.210/32
13.33.4.0/24
13.33.0.0/16
13.35.127.202/32
13.35.127.0/24
13.35.0.0/16
99.84.231.110/32
99.84.231.0/24
99.84.0.0/16
13.35.11.24/32
13.32.177.135/32
13.32.32.125/32
13.225.7.231/32
13.225.7.211/32
13.33.227.67/32
13.249.219.186/32
13.224.162.97/32
99.86.183.149/32
13.33.186.232/32
13.225.100.51/32
13.224.162.175/32
99.84.231.168/32
52.85.159.121/32
13.32.32.9/32
13.32.32.0/24
13.32.0.0/16
52.85.159.223/32
13.249.226.48/32
13.35.127.42/32
13.32.32.205/32
13.32.222.202/32
99.86.17.24/32
99.84.201.92/32
13.224.162.53/32
13.225.100.231/32
99.84.201.190/32
13.33.174.109/32
13.35.153.103/32
54.192.69.184/32
13.33.227.94/32
99.86.61.157/32
54.230.14.139/32
54.192.69.219/32
99.86.61.63/32
13.35.20.72/32
13.225.178.116/32
52.85.159.180/32
99.86.149.128/32
13.32.86.172/32
99.84.201.145/32
13.35.20.193/32
13.35.254.210/32
13.35.103.158/32
52.84.49.27/32
52.84.49.178/32
52.84.186.238/32
13.35.103.218/32
13.35.5.147/32
52.84.49.9/32
13.225.100.87/32
13.124.180.0/24
13.224.0.0/16
13.251.110.0/24
52.1.71.116/32
52.1.71.0/24
52.1.0.0/16
18.213.20.253/32
18.213.20.0/24
18.213.0.0/16
52.204.121.28/32
52.204.121.0/24
52.204.0.0/16
13.224.166.64/32
15.164.131.0/24
18.136.198.0/24
18.139.110.0/24
13.124.180.57/32
18.213.0.0/16
18.136.198.141/32
52.77.210.211/32
13.224.162.199/32
13.251.110.6/32
210.89.172.84/32
104.25.112.26/32
104.25.113.26/32
104.16.155.36/32
66.171.248.178/32
15.164.131.147/32
52.78.140.66/32
203.208.39.254/32
203.208.43.64/32
172.217.24.10/32
18.139.110.27/32
128.1.35.174/32
119.28.52.85/32
150.109.183.86/32
52.84.225.81/32
203.208.43.72/32
3.1.205.234/32
104.80.28.104/32
54.209.57.179/32
172.217.194.97/32
172.217.194.139/32
172.217.194.156/32
184.29.104.6/32
54.209.57.179/32
203.208.39.195/32
52.84.225.81/32
184.29.104.6/32
203.208.43.122/32
54.209.57.179/32
172.217.194.100/32
216.58.203.238/32
52.84.225.81/32
216.58.221.68/32
150.109.182.109/32
203.208.39.194/32
13.224.166.65/32
203.208.50.190/32
23.75.20.0/24
23.213.140.0/24
23.213.140.73/32
52.1.0.0/16
52.20.25.0/24
52.77.210.0/24
52.78.0.0/16
52.84.0.0/16
52.204.0.0/16
54.209.0.0/16
52.78.5.141/32
66.171.248.0/24
104.16.155.0/24
104.25.0.0/16
104.75.165.0/24
104.75.165.107/32
104.80.28.0/24
119.28.52.0/24
128.1.35.0/24
150.109.0.0/16
172.217.0.0/16
184.29.0.0/16
203.208.0.0/16
210.89.172.0/24
216.58.0.0/16
