### ISSUE TITLE
请问一下各位大佬只绕过局域网，其余都代理，规则要怎么改？？

### ISSUE THREAD

**Issue by musclebear76** [FQrabbit/SSTap-Rule#207]
**需要增加游戏\程序名字**
如``Lan``

**该游戏\程序的运行环境**
如

``PC``

**该游戏\程序哪部分需要代理**
如
``整个游戏\程序都需要``

**特殊情况**
排除局域网的全局。
小白一个，望大佬勿怪！！

**Comment by FQrabbit** [comment]
@musclebear76 0.0.0.0/8
10.0.0.0/8
100.64.0.0/10
127.0.0.0/8
169.254.0.0/16
172.16.0.0/12
192.0.0.0/24
192.0.2.0/24
192.168.0.0/16
198.18.0.0/15
198.51.100.0/24
203.0.113.0/24
::1/128
fc00::/7
fe80::/10


代理方式:直连

**Comment by musclebear76** [comment]
谢谢大佬！！！

**Comment by musclebear76** [comment]
@FQrabbit 
无论采用这个修改过的规则，还是下载规则包里有的烂橘子规则，打开烂橘子都会检测到我在国内，
而且商店页面还刷新不出来，
同时，我网页直连检测IP在国外，steam客户端可以打开社区页面，
SStap采用的本地端口socks5代理：127.0.0.1:1080；SSR监听本地1080端口，远程服务器填的ipv6地址（ipv4秒被墙）；附加路由填的远程服务器ipv4地址（好像填不了ipv6），直连；
打扰了！！

**Comment by FQrabbit** [comment]
@musclebear76 你的ssr是不是开了国内外分流...

**Comment by FQrabbit** [comment]
@musclebear76 好像某些平台吃ie代理(ssr某些设置会修改ie代理)🤔

**Comment by musclebear76** [comment]
不是酸酸乳的原因吧？？
我后来酸酸乳依旧监听本地1080端口，然后将sstap关掉，换成proxifer（只可用于TCP）开全局，依旧代理到127.0.0.1:1080，再打开烂橘子就能把我识别到国外了。
@FQrabbit  打扰了，这回在线等！！

**Comment by musclebear76** [comment]
v2ray的vmess好像也支持udp，
我待会儿把酸酸乳换成v2ray试试

**Comment by musclebear76** [comment]
先去吃饭了

**Comment by FQrabbit** [comment]
@musclebear76 那可能就是，解析域名的时候解析成国内的cdn了，所以就识别国区，没什么意外应该是sstap的dns解析错误地区导致的

**Comment by musclebear76** [comment]
谢谢大佬，终于搞好了！！
把那个智能分流dns关掉，换成谷歌的dns并代理，就可以真正全局了！！
再次感谢大佬！！
