### ISSUE TITLE
请求添加 discord/steam语音 规则

### ISSUE THREAD

**Issue by wywzxxz** [FQrabbit/SSTap-Rule#21]
**需要增加游戏\程序名字**
discord
steam语音

**该游戏\程序的运行环境**
PC

**该游戏\程序哪部分需要代理**
整个游戏\程序都需要`

**特殊情况**
discord和steam总容易掉线，并且掉线时无声音提示，希望能对其单独进行加速。

另注：我发现有时掉线时因为UDP持续发送失败导致的，尚未知原因。

**Comment by FQrabbit** [comment]
@yezixi 是不是规则失效了？🤔

**Comment by yezixi** [comment]
@FQrabbit 目前只能选《不代理中国IP》但是希望此规则可以单独出来，然后想添加到游戏的规则里面，因为基本打游戏都需要。还有个题外问题：我们是能通过rule目录下文件将规则自行合并吗？

**Comment by wywzxxz** [comment]
@FQrabbit
抱歉，之前因为主页没有列出discord，以为没有相关规则……
当前discord突然又能连接了，所以测试结果可能不准确。但是挂起规则后discord能正常使用且ping变低，因此规则应该有效。

**Comment by wywzxxz** [comment]
确认有效
