### ISSUE TITLE
有没有什么方法 可以把 skip cn ip 以及 想代理的游戏 合并成一个规则? 

### ISSUE THREAD

**Issue by yoyosnart** [FQrabbit/SSTap-Rule#212]
主要是想要一般逛网页 , 一边代理玩游戏 , 用全局不太适合 , 有什么方法可以把这两个规则合并的吗??

 skip cn ip  以及 代理游戏的规则

**Comment by sceraser** [comment]
![image](https://user-images.githubusercontent.com/42718757/56352890-c0772080-6202-11e9-9cad-fe1460aa36a9.png)
.rules是纯文本文件,你可以用notepad++手动把你需要的规则复制粘贴合并起来然后起一个新名字即可

**Comment by yezixi** [comment]
> .rules是纯文本文件,你可以用notepad++手动把你需要的规则复制粘贴合并起来然后起一个新名字即可

举例:1个规则是跳过指定IP段,另一个规则是代理指定IP段,放同一个规则里能同时生效吗?这样请问是否支持?

**Comment by yezixi** [comment]
@FQrabbit 能否解答下楼上提问 不胜感谢

**Comment by sceraser** [comment]
只要两个规则没冲突的话是可以的

**Comment by sceraser** [comment]
@yezixi 只要两个规则没冲突的话应该是可以的

**Comment by sceraser** [comment]
> > .rules是纯文本文件,你可以用notepad++手动把你需要的规则复制粘贴合并起来然后起一个新名字即可
> 
> 举例:1个规则是跳过指定IP段,另一个规则是代理指定IP段,放同一个规则里能同时生效吗?这样请问是否支持?
> @FQrabbit 不胜感谢

只要两个规则没冲突的话应该是可以的

**Comment by yezixi** [comment]
> > > .rules是纯文本文件,你可以用notepad++手动把你需要的规则复制粘贴合并起来然后起一个新名字即可
> > 举例:1个规则是跳过指定IP段,另一个规则是代理指定IP段,放同一个规则里能同时生效吗?这样请问是否支持?
> 只要两个规则没冲突的话应该是可以的


上述举例的不一样的代理规则也可以放同一个规则里执行吗?因为添加了跳过中国IP规则所以暂时没验证到同个rule的其他规则是否生效
