### ISSUE TITLE
``极限竞速:地平线4``

### ISSUE THREAD

**Issue by Shuai1a** [FQrabbit/SSTap-Rule#213]
**需要增加游戏\程序名字**
如``CS-GO``

**该游戏\程序的运行环境**
如
``虚拟机``
``局域网其他设备``
``PC``

**该游戏\程序哪部分需要代理**
如
``整个游戏\程序都需要``
``只代理登陆部分``

**特殊情况**
如果还有特殊想说明的请在这里描述.

**Comment by Liu6217** [comment]
地平线4无需规则 下载一个ssr然后更新PAC绕过大陆域名和IP 然后选择PAC模式 就可以玩了，不会掉线，拍卖行啥的秒开，连线1分钟左右。以前慢死了

**Comment by onyz4x** [comment]
直接用SSR 玩线上排位的时候还是会掉线
