### ISSUE TITLE
Skip all China IP and LAN无法正常使用

### ISSUE THREAD

**Issue by moritasan** [FQrabbit/SSTap-Rule#217]
**问题描述**
校园网环境无法使用正常使用ssr，所以我在使用SwitchOmega代理游览器。
目前想把游览器和应用一起代理，就想到了SSTap，使用了skip CN and LAN的这个规则。
但是使用后游览器全局都在走代理服务器，没有区分ip

**运行环境**
拨号的校园网

**Comment by FQrabbit** [comment]
@moritasan https://ip.skk.moe/

**Comment by moritasan** [comment]
我查询过了，国内地址也是走代理......

**Comment by moritasan** [comment]
已解决，请关闭。
解决方式是switchomega的设置改为直线连接，这样就可以让sstap调用自己的规则了
