### ISSUE TITLE
技术上的问题。。。

### ISSUE THREAD

**Issue by dilllay** [FQrabbit/SSTap-Rule#227]
作者，你好。首先我声明一下我对网络这一块不太熟悉，但我也很喜欢搞加速器。我自己也有自己也有一套加速方案，效果还不错，目前可以加速ps4,ns,xbox，因为最近想玩一下pc，就看了一下sscap这个东西，也看了一下你的这个项目，这个项目很不错，但有些不知道是你的描述有问题，还是sscap真的是这样实现，我想求证一下。   
- 问题1，这个sscap中的rule真的是路由列表吗？我看上去感觉像是ip段过滤，过滤得出结果后确定走直连线路还是走代理线路。   
- 问题2，如果这个rule是ip过滤列表的话，那么我写0.0.0.0/0是不是就可以代表全局代理了，那么只要我的加速服务器正常的话，我就不需要再去找相应游戏的sscap ip rule了？   
- 问题3，与其需要用uu加速器的账号去追踪游戏ip，为什么不直接使用uu加速器，还要折腾用sscap呢？我记得uu加速器好像是付费的，如果只是需要ip的话，那么tcpdump，wireshark这些不是应该更好么？
@FQrabbit

**Comment by FQrabbit** [comment]
@dilllay 回答1：这个规则是路由表规则噢亲，您可以wiki一下路由表的格式，但是你后面的理解也是正确的。

回答2：您写0.0.0.0/0确实就是全部流量走代理或者不走代理，至于为什么要选对应规则，因为不是所有人都想整台电脑程序都走代理出口，所以对应规则走代理是一个比较适合的选择。

回答3：至于为什么有人去找uu的ip，因为是懒的自己抓包，所以既然别人做好了，就直接拿过来用了，为什么不使用uu加速器的话，那大概就是省钱吧，抓包程序很多，但是方不方便统计并整理起来，就不是上述软件所能接受的来了吧。
请问亲还有什么问题吗？🌚
