### ISSUE TITLE
提供几个美国节点

### ISSUE THREAD

**Issue by YumiCoing** [FQrabbit/SSTap-Rule#229]
[https://github.com/YumiCoing/FreeSSTap](https://github.com/YumiCoing/FreeSSTap)

## 免费SSTAP 美国节点

类型：`Sokcs5`

IP地址：`47.102.147.120`

端口号：`65000 - 65460`

（一个端口号对应一个美国ip）

用户名 ：`uuccs`

密码：`uuccs2019`

## 注意事项

节点不支持UDP转发。

需要开启 [Pcap_DNSProxy](https://github.com/chengr28/Pcap_DNSProxy).

给SSTAP设置预选DNS为 127.0.0.1

或者关闭UDP转发，设置本地DNS为127.0.01

**Comment by FQrabbit** [comment]
@YumiCoing ...高防么🌚

**Comment by jzl1** [comment]
@YumiCoing 阿里上海？

**Comment by YumiCoing** [comment]
> @YumiCoing 阿里上海？

中转到美国

**Comment by AmazingDM** [comment]
大佬牛皮熬，四百多ip
