### ISSUE TITLE
台服LOL 规则失效

### ISSUE THREAD

**Issue by BIGlaoning** [FQrabbit/SSTap-Rule#23]
台服LOL的问题 
Garena平台正常登陆 

但是打开游戏就无法进入游戏了。提示服务器出错等信息

请兔子帮忙解决一下呗

**Comment by FQrabbit** [comment]
@BIGlaoning 这个游戏有时候有点问题，你尝试过用`全局`或者`不代理中国ip`的模式能进入游戏吗🤔

**Comment by BIGlaoning** [comment]
都尝试过了，只要点游戏开始  过不到一会儿它就直接弹出错误 我用全局和不代理中国IP的方式都试过 ，还是这样
![11](https://user-images.githubusercontent.com/41830404/43357144-ab19aba4-92af-11e8-8db6-1616a3a8819f.jpg)

**Comment by FQrabbit** [comment]
@BIGlaoning 这个游戏我就知道有点问题🤔

**Comment by BIGlaoning** [comment]
@FQrabbit 还希望兔子帮帮忙解决一下了。。感谢

**Comment by BIGlaoning** [comment]
我正在把电脑系统的语言更改为台湾的 看看是否可以

**Comment by FQrabbit** [comment]
游戏的连接方式应该不是正常通过路由表走ip数据包，应该是通过了自行的程序出口流量，感觉要有劫持程序才能代理这款游戏了，这样的话SSTap就无能为力了. :100:

**Comment by BIGlaoning** [comment]
@FQrabbit 听你这样说，我想唱首“凉凉”。。。

**Comment by FQrabbit** [comment]
因为全局都不能代理这款游戏，真的没办法，SSTap的路由表方式代理是无力了，这家游戏反作弊力度蛮"严格"的 🤔

**Comment by FQrabbit** [comment]
建议使用同作者的`Sockscap64`来代理这款游戏吧

**Comment by BIGlaoning** [comment]
@FQrabbit 除了台服  韩服日服这些应该没有影响把 ，我想去玩玩外服而已 ，真是倒霉 - -偏偏是台服不行了。。。  好的，我用下sockscap64看看

**Comment by FQrabbit** [comment]
应该是这个游戏不行，美服我也收到有你这个问题的报告🤔

**Comment by BIGlaoning** [comment]
好的，感谢在线解答...
