### ISSUE TITLE
eve-online.rules原规则已失效，提交新的规则

### ISSUE THREAD

**Issue by coldeve** [FQrabbit/SSTap-Rule#235]
[eve-online.zip](https://github.com/FQrabbit/SSTap-Rule/files/3144475/eve-online.zip)
不知道怎么提交合并请求，只能用issue提交修改请求了，求有权限的大佬帮忙修改下原项目的eve-online.rules
作者依然是我：寒夜方舟

**Comment by FQrabbit** [comment]
@coldeve 直接在网页修改文本，保存的时候就自动提交pr
了

**Comment by coldeve** [comment]
> @coldeve直接在网页修改文本，保存的时候就自动提交PR 
> 了

嗯，好的，已提交
