### ISSUE TITLE
高版本号客户端不兼容明文的rules文件吗？

### ISSUE THREAD

**Issue by KevinBlandy** [FQrabbit/SSTap-Rule#236]
我从该仓库下载的`rules`文件。直接复制到`rules`目录，启动客户端，发现没有任何选项。我尝试打开客户端默认的`rules`文件。发现里面是Base64编码？

> 版本号: SSTap-beta-setup-1.1.0.1.exe

**Comment by partment** [comment]
這個倉庫提供的規則文件需使用1.0.9.7版本以下的SSTAP
