### ISSUE TITLE
请求单独列出discord规则

### ISSUE THREAD

**Issue by yezixi** [FQrabbit/SSTap-Rule#24]
神墙的原因 有时候需要用游戏加速规则 然后会导致discord不可用 想作者能单独列一份出来 手动添加到游戏规则里

**Comment by FQrabbit** [comment]
项目里已经存在，更新日志还没更新，你可以直接 [查看](https://github.com/FQrabbit/SSTap-Rule/blob/de7ed39194a8215d9fcd1fdbc15e8eacba6e81fd/rules/Discord.rules) 此链接

**Comment by yezixi** [comment]
非常感谢@FQrabbit
