### ISSUE TITLE
请求补充对 CSGO Demo 回放下载服务器的代理规则

### ISSUE THREAD

**Issue by kj415j45** [FQrabbit/SSTap-Rule#245]
**需要增加游戏\程序名字**
``Counter-Strike: Global Offensive``

**该游戏\程序的运行环境**
``PC``

**该游戏\程序哪部分需要代理**
``Demo 下载``

**特殊情况**
Demo 的下载链接大概是从 `replay141.valve.net` 一直到 `replay156.valve.net`
好像都是V社所用的 akamai CDN（

**Comment by jzl1** [comment]
@kj415j45 akamai cdn段太大，建议后台再挂代理
