### ISSUE TITLE
希望大佬帮写一个黑色沙漠的规则，感谢

### ISSUE THREAD

**Issue by shaohuazz** [FQrabbit/SSTap-Rule#25]
黑色沙漠 台服

**该游戏\程序的运行环境**
PC

**该游戏\程序哪部分需要代理**
整个游戏\程序都需要

**Comment by Filterrr** [comment]
[Black-Desert.zip](https://github.com/FQrabbit/SSTap-Rule/files/2280673/Black-Desert.zip)
黑色沙漠台、韩、美服

**Comment by xishijt** [comment]
> [Black-Desert.zip](https://github.com/FQrabbit/SSTap-Rule/files/2280673/Black-Desert.zip)
> 黑色沙漠台、韩、美服

台服无法生效
