### ISSUE TITLE
求添加美服冒险岛规则

### ISSUE THREAD

**Issue by unsunday** [FQrabbit/SSTap-Rule#250]
需要增加游戏\程序名字
Maplestory

该游戏\程序的运行环境
PC 

该游戏\哪程序需要部分代理
整个游戏

**Comment by MechanicalBrain** [comment]
需要增加游戏\程序名字
Maplestory

该游戏\程序的运行环境
PC

该游戏\哪程序需要部分代理
整个游戏

**Comment by Dreamone1** [comment]
> 需要增加游戏\程序名字
> Maplestory
> 
> 该游戏\程序的运行环境
> PC
> 
> 该游戏\哪程序需要部分代理
> 整个游戏

#maplastory,冒险岛国际服,0,0,1,0,1,0,By-aiimeimei
34.215.62.0/24
35.167.153.0/24
52.37.193.0/24
172.217.5.0/24
52.197.41.0/24
52.68.4.0/24
54.250.175.0/24
74.125.28.0/24
52.42.3.0/24
52.37.21.0/24
13.124.51.0/24
35.165.11.0/24
172.217.5.0/24
172.217.4.0/24
13.33.231.0/24
54.191.87.0/24
52.43.10.0/24
13.33.231.0/24
我自己花了半小时抓的 
目前来说 应该没啥问题

**Comment by Dreamone1** [comment]
> 需要增加游戏\程序名字
> Maplestory
> 
> 该游戏\程序的运行环境
> PC
> 
> 该游戏\哪程序需要部分代理
> 整个游戏

#maplastory,冒险岛国际服,0,0,1,0,1,0,By-aiimeimei
34.215.62.0/24
35.167.153.0/24
52.37.193.0/24
172.217.5.0/24
52.197.41.0/24
52.68.4.0/24
54.250.175.0/24
74.125.28.0/24
52.42.3.0/24
52.37.21.0/24
13.124.51.0/24
35.165.11.0/24
172.217.5.0/24
172.217.4.0/24
13.33.231.0/24
54.191.87.0/24
52.43.10.0/24
13.33.231.0/24
我自己花了半小时抓的
目前来说 应该没啥问题

**Comment by Dreamone1** [comment]
1.0.0.0/4
1.2.0.0/16
1.4.0.0/16
1.9.0.0/16
1.10.0.0/16
1.16.0.0/16
1.32.0.0/16
1.40.0.0/16
1.44.0.0/16
1.46.0.0/16
1.52.0.0/16
1.64.0.0/16
1.72.0.0/16
1.96.0.0/16
1.112.0.0/16
1.120.0.0/16
1.128.0.0/16
1.160.0.0/16
1.176.0.0/16
1.186.0.0/16
1.200.0.0/16
1.208.0.0/16
1.224.0.0/16
2.0.0.0/4
4.0.0.0/4
8.0.0.0/4
8.31.99.0/24
11.0.0.0/4
12.0.0.0/4
14.0.0.0/4
14.32.0.0/16
14.64.0.0/16
14.96.0.0/16
14.100.0.0/16
14.102.0.0/16
14.128.0.0/16
14.132.0.0/16
14.136.0.0/16
14.160.0.0/16
14.192.0.0/16
14.198.0.0/16
14.200.0.0/16
14.206.0.0/16
14.224.0.0/16
15.0.0.0/4
16.0.0.0/4
24.0.0.0/4
26.0.0.0/4
27.0.0.0/4
27.32.0.0/16
27.48.0.0/16
27.50.0.0/16
27.51.0.0/16
27.52.0.0/16
27.56.0.0/16
27.64.0.0/16
27.96.0.0/16
27.98.0.0/16
27.99.0.0/16
27.100.0.0/16
27.102.0.0/16
27.104.0.0/16
27.112.0.0/16
27.114.0.0/16
27.115.128.0/24
27.116.0.0/16
27.120.0.0/16
27.130.0.0/16
27.132.0.0/16
27.136.0.0/16
27.145.0.0/16
27.146.0.0/16
27.160.0.0/16
27.176.0.0/16
27.228.0.0/16
27.232.0.0/16
27.240.0.0/16
28.0.0.0/4
32.0.0.0/4
36.2.0.0/16
36.8.0.0/16
36.37.0.0/16
36.38.0.0/16
36.52.0.0/16
36.64.0.0/16
36.240.0.0/16
36.252.0.0/16
36.255.0.0/16
37.0.0.0/4
38.0.0.0/4
39.1.0.0/16
39.2.0.0/16
39.4.0.0/16
39.8.0.0/16
39.16.0.0/16
39.32.0.0/16
39.109.0.0/16
39.110.0.0/16
39.112.0.0/16
39.116.0.0/16
39.120.0.0/16
39.192.0.0/16
40.0.0.0/4
42.0.0.0/4
42.1.0.0/16
42.2.0.0/16
42.8.0.0/16
42.16.0.0/16
42.32.0.0/16
42.60.0.0/16
42.62.128.0/24
42.64.0.0/16
42.82.0.0/16
42.83.0.0/16
42.96.0.0/16
42.98.0.0/16
42.104.0.0/16
42.112.0.0/16
42.123.0.0/16
42.124.0.0/16
42.144.0.0/16
42.152.0.0/16
42.156.0.0/16
42.187.0.0/16
42.188.0.0/16
42.200.0.0/16
42.201.128.0/24
42.241.0.0/16
43.0.0.0/4
43.128.0.0/16
43.192.0.0/16
43.224.0.0/16
43.232.0.0/16
43.239.52.0/24
43.239.56.0/24
43.239.64.0/24
43.239.96.0/24
43.239.112.0/24
43.239.124.0/24
43.239.128.0/24
43.240.0.0/16
44.0.0.0/4
48.0.0.0/4
49.0.0.0/4
49.8.0.0/16
49.16.0.0/16
49.32.0.0/16
49.48.0.0/16
49.50.0.0/16
49.51.0.0/16
49.56.0.0/16
49.96.0.0/16
49.124.0.0/16
49.128.0.0/16
49.136.0.0/16
49.142.0.0/16
49.144.0.0/16
49.156.0.0/16
49.160.0.0/16
49.192.0.0/16
49.212.0.0/16
49.216.0.0/16
49.224.0.0/16
49.236.0.0/16
49.240.0.0/16
50.0.0.0/4
52.0.0.0/4
52.43.5.0/24
52.79.206.0/24
54.0.0.0/4
54.128.0.0/16
54.148.26.0/24
54.192.0.0/16
54.208.0.0/16
54.216.0.0/16
54.220.0.0/16
54.224.0.0/16
55.0.0.0/4
56.0.0.0/4
58.0.0.0/4
58.8.0.0/16
58.12.0.0/16
58.26.0.0/16
58.28.0.0/16
58.64.0.0/16
58.68.0.0/16
58.69.0.0/16
58.70.0.0/16
58.72.0.0/16
58.80.0.0/16
58.82.128.0/24
58.84.0.0/16
58.88.0.0/16
58.96.0.0/16
58.98.0.0/16
58.99.0.0/16
58.102.0.0/16
58.104.0.0/16
58.112.0.0/16
58.120.0.0/16
58.136.0.0/16
58.145.0.0/16
58.146.0.0/16
58.148.0.0/16
58.152.0.0/16
58.156.0.0/16
58.160.0.0/16
58.224.0.0/16
59.0.0.0/4
59.84.0.0/16
59.88.0.0/16
59.96.0.0/16
59.104.0.0/16
59.106.0.0/16
59.112.0.0/16
59.128.0.0/16
59.144.0.0/16
59.148.0.0/16
59.150.0.0/16
59.151.128.0/24
59.152.0.0/16
59.154.0.0/16
59.156.0.0/16
59.160.0.0/16
59.168.0.0/16
59.176.0.0/16
59.184.0.0/16
59.188.0.0/16
59.190.0.0/16
59.191.128.0/24
60.32.0.0/16
60.48.0.0/16
60.52.0.0/16
60.54.0.0/16
60.56.0.0/16
60.60.0.0/16
60.62.0.0/16
60.64.0.0/16
60.128.0.0/16
60.192.0.0/16
60.196.0.0/16
60.224.0.0/16
60.234.0.0/16
60.236.0.0/16
60.240.0.0/16
60.244.0.0/16
60.245.0.0/16
60.246.0.0/16
60.248.0.0/16
60.253.0.0/16
60.254.0.0/16
61.0.0.0/4
61.32.0.0/16
61.56.0.0/16
61.64.0.0/16
61.192.0.0/16
61.224.0.0/16
61.238.0.0/16
61.244.0.0/16
61.248.0.0/16
62.0.0.0/4
64.0.0.0/4
96.0.0.0/4
100.0.0.0/4
100.128.0.0/16
101.0.0.0/4
101.8.0.0/16
101.50.0.0/16
101.53.0.0/16
101.55.0.0/16
101.56.0.0/16
101.78.0.0/16
101.96.0.0/16
101.97.0.0/16
101.98.0.0/16
101.100.0.0/16
101.108.0.0/16
101.112.0.0/16
101.127.0.0/16
101.128.0.0/16
101.132.237.193/32
101.136.0.0/16
101.160.0.0/16
101.202.0.0/16
101.208.0.0/16
101.234.0.0/16
101.250.0.0/16
101.251.0.0/16
101.255.0.0/16
102.0.0.0/4
103.0.0.0/4
103.192.0.0/16
103.196.0.0/16
103.198.0.0/16
103.198.32.0/24
103.198.48.0/24
103.198.56.0/24
103.198.68.0/24
103.198.72.0/24
103.198.80.0/24
103.198.96.0/24
103.198.128.0/24
103.199.0.0/16
103.200.0.0/16
103.208.0.0/16
103.212.0.0/16
103.214.0.0/16
103.214.32.0/24
103.214.52.0/24
103.214.56.0/24
103.214.64.0/24
103.214.128.0/24
103.215.0.0/16
103.216.0.0/16
103.224.0.0/16
104.0.0.0/4
106.0.0.0/4
106.10.0.0/16
106.51.0.0/16
106.64.0.0/16
106.72.0.0/16
106.76.0.0/16
106.96.0.0/16
106.104.0.0/16
106.128.0.0/16
106.192.0.0/16
106.240.0.0/16
107.0.0.0/4
108.0.0.0/4
110.0.0.0/4
110.4.0.0/16
110.8.0.0/16
110.20.0.0/16
110.24.0.0/16
110.32.0.0/16
110.44.0.0/16
110.49.0.0/16
110.50.0.0/16
110.54.0.0/16
110.66.0.0/16
110.68.0.0/16
110.74.0.0/16
110.76.0.0/16
110.77.128.0/24
110.78.0.0/16
110.92.0.0/16
110.128.0.0/16
110.144.0.0/16
110.158.0.0/16
110.160.0.0/16
110.164.0.0/16
110.168.0.0/16
110.224.0.0/16
110.232.0.0/16
110.238.0.0/16
111.64.0.0/16
111.67.0.0/16
111.68.0.0/16
111.80.0.0/16
111.84.0.0/16
111.86.0.0/16
111.88.0.0/16
111.96.0.0/16
111.118.0.0/16
111.125.0.0/16
111.168.0.0/16
111.171.0.0/16
111.184.0.0/16
111.188.0.0/16
111.216.0.0/16
111.220.0.0/16
111.221.0.0/16
111.223.0.0/16
111.232.0.0/16
111.240.0.0/16
112.68.0.0/16
112.72.0.0/16
112.76.0.0/16
112.104.0.0/16
112.108.0.0/16
112.109.0.0/16
112.110.0.0/16
112.118.0.0/16
112.120.0.0/16
112.133.0.0/16
112.134.0.0/16
112.136.0.0/16
112.144.0.0/16
112.160.0.0/16
112.196.0.0/16
112.200.0.0/16
112.208.0.0/16
113.10.0.0/16
113.19.0.0/16
113.20.0.0/16
113.28.0.0/16
113.30.0.0/16
113.32.0.0/16
113.40.0.0/16
113.52.0.0/16
113.59.128.0/24
113.60.0.0/16
113.130.0.0/16
113.144.0.0/16
113.160.0.0/16
113.192.0.0/16
113.196.0.0/16
113.203.0.0/16
113.208.0.0/16
113.210.0.0/16
113.212.0.0/16
113.213.128.0/24
113.216.0.0/16
113.252.0.0/16
114.0.0.0/4
114.16.0.0/16
114.24.0.0/16
114.29.0.0/16
114.30.0.0/16
114.32.0.0/16
114.48.0.0/16
114.52.0.0/16
114.56.0.0/16
114.69.0.0/16
114.70.0.0/16
114.72.0.0/16
114.108.0.0/16
114.120.0.0/16
114.128.0.0/16
114.133.0.0/16
114.134.0.0/16
114.136.0.0/16
114.140.0.0/16
114.144.0.0/16
114.160.0.0/16
114.192.0.0/16
114.198.0.0/16
114.200.0.0/16
115.0.0.0/4
115.16.0.0/16
115.30.0.0/16
115.36.0.0/16
115.40.0.0/16
115.64.0.0/16
115.96.0.0/16
115.108.0.0/16
115.112.0.0/16
115.124.0.0/16
115.128.0.0/16
115.144.0.0/16
115.160.0.0/16
115.176.0.0/16
115.184.0.0/16
115.188.0.0/16
115.240.0.0/16
116.0.0.0/4
116.12.0.0/16
116.14.0.0/16
116.32.0.0/16
116.48.0.0/16
116.58.0.0/16
116.64.0.0/16
116.66.128.0/24
116.67.0.0/16
116.68.0.0/16
116.70.128.0/24
116.71.0.0/16
116.72.0.0/16
116.80.0.0/16
116.84.0.0/16
116.86.0.0/16
116.88.0.0/16
116.92.0.0/16
116.94.0.0/16
116.96.0.0/16
116.118.0.0/16
116.120.0.0/16
116.193.0.0/16
116.197.0.0/16
116.199.128.0/24
116.200.0.0/16
116.206.0.0/16
116.212.0.0/16
116.213.0.0/16
116.214.0.0/16
116.220.0.0/16
116.240.0.0/16
116.250.0.0/16
116.254.0.0/16
116.255.0.0/16
117.0.0.0/4
117.16.0.0/16
117.20.0.0/16
117.46.0.0/16
117.52.0.0/16
117.56.0.0/16
117.58.128.0/24
117.74.0.0/16
117.96.0.0/16
117.102.0.0/16
117.104.0.0/16
117.108.0.0/16
117.120.0.0/16
117.121.128.0/24
117.122.0.0/16
117.123.0.0/16
117.192.0.0/16
118.0.0.0/4
118.16.0.0/16
118.27.0.0/16
118.32.0.0/16
118.67.0.0/16
118.68.0.0/16
118.82.0.0/16
118.86.0.0/16
118.88.0.0/16
118.90.0.0/16
118.92.0.0/16
118.96.0.0/16
118.127.0.0/16
118.128.0.0/16
118.136.0.0/16
118.148.0.0/16
118.152.0.0/16
118.160.0.0/16
118.176.0.0/16
118.179.0.0/16
118.185.0.0/16
118.189.0.0/16
118.200.0.0/16
118.208.0.0/16
118.214.0.0/16
118.216.0.0/16
118.231.0.0/16
118.232.0.0/16
118.236.0.0/16
118.238.0.0/16
118.240.0.0/16
118.243.0.0/16
119.2.0.0/16
119.9.0.0/16
119.10.128.0/24
119.11.0.0/16
119.12.0.0/16
119.17.0.0/16
119.18.0.0/16
119.24.0.0/16
119.28.0.0/16
119.30.0.0/16
119.38.128.0/24
119.40.0.0/16
119.42.0.0/16
119.46.0.0/16
119.56.0.0/16
119.59.0.0/16
119.63.0.0/16
119.72.0.0/16
119.76.0.0/16
119.81.0.0/16
119.82.0.0/16
119.92.0.0/16
119.104.0.0/16
119.110.0.0/16
119.148.0.0/16
119.152.0.0/16
119.160.0.0/16
119.161.0.0/16
119.168.0.0/16
119.192.0.0/16
119.224.0.0/16
119.234.0.0/16
119.236.0.0/16
119.240.0.0/16
119.252.0.0/16
120.16.0.0/16
120.28.0.0/16
120.50.0.0/16
120.56.0.0/16
120.72.0.0/16
120.73.0.0/16
120.74.0.0/16
120.88.0.0/16
120.93.0.0/16
120.96.0.0/16
120.136.0.0/16
120.137.128.0/24
120.138.0.0/16
120.140.0.0/16
120.144.0.0/16
120.160.0.0/16
121.0.0.0/4
121.6.0.0/16
121.44.0.0/16
121.46.0.0/16
121.50.0.0/16
121.52.0.0/16
121.58.128.0/24
121.64.0.0/16
121.72.0.0/16
121.78.0.0/16
121.80.0.0/16
121.88.0.0/16
121.90.0.0/16
121.92.0.0/16
121.96.0.0/16
121.100.0.0/16
121.101.0.0/16
121.102.0.0/16
121.104.0.0/16
121.112.0.0/16
121.128.0.0/16
121.200.0.0/16
121.202.0.0/16
121.208.0.0/16
121.240.0.0/16
121.252.0.0/16
121.254.0.0/16
122.0.0.0/4
122.1.0.0/16
122.2.0.0/16
122.11.128.0/24
122.15.0.0/16
122.16.0.0/16
122.32.0.0/16
122.49.0.0/16
122.50.0.0/16
122.52.0.0/16
122.56.0.0/16
122.98.0.0/16
122.100.0.0/16
122.104.0.0/16
122.116.0.0/16
122.118.0.0/16
122.120.0.0/16
122.128.0.0/16
122.144.0.0/16
122.145.0.0/16
122.146.0.0/16
122.148.0.0/16
122.152.0.0/16
122.160.0.0/16
122.176.0.0/16
122.184.0.0/16
122.196.0.0/16
122.199.0.0/16
122.200.0.0/16
122.208.0.0/16
122.248.0.0/16
123.0.0.0/4
123.16.0.0/16
123.32.0.0/16
123.48.0.0/16
123.49.0.0/16
123.50.0.0/16
123.63.0.0/16
123.98.128.0/24
123.99.0.0/16
123.100.0.0/16
123.102.0.0/16
123.103.128.0/24
123.104.0.0/16
123.136.0.0/16
123.140.0.0/16
123.176.0.0/16
123.192.0.0/16
123.198.0.0/16
123.199.0.0/16
123.200.0.0/16
123.204.0.0/16
123.208.0.0/16
123.224.0.0/16
123.236.0.0/16
123.240.0.0/16
123.242.128.0/24
123.243.0.0/16
123.248.0.0/16
123.250.0.0/16
123.252.0.0/16
123.254.0.0/16
124.0.0.0/4
124.8.0.0/16
124.12.0.0/16
124.18.0.0/16
124.24.0.0/16
124.28.0.0/16
124.29.128.0/24
124.30.0.0/16
124.32.0.0/16
124.40.0.0/16
124.43.0.0/16
124.44.0.0/16
124.48.0.0/16
124.66.128.0/24
124.80.0.0/16
124.96.0.0/16
124.120.0.0/16
124.124.0.0/16
124.136.0.0/16
124.144.0.0/16
124.146.0.0/16
124.147.0.0/16
124.148.0.0/16
124.150.0.0/16
124.153.0.0/16
124.154.0.0/16
124.157.0.0/16
124.158.0.0/16
124.168.0.0/16
124.176.0.0/16
124.194.0.0/16
124.197.0.0/16
124.198.0.0/16
124.208.0.0/16
124.216.0.0/16
124.240.128.0/24
124.241.0.0/16
124.243.0.0/16
124.244.0.0/16
124.248.128.0/24
124.252.0.0/16
125.0.0.0/4
125.48.0.0/16
125.56.0.0/16
125.58.0.0/16
125.59.0.0/16
125.60.0.0/16
125.61.0.0/16
125.62.0.0/16
125.99.0.0/16
125.100.0.0/16
125.128.0.0/16
125.160.0.0/16
125.168.0.0/16
125.170.0.0/16
125.172.0.0/16
125.176.0.0/16
125.192.0.0/16
125.208.0.0/16
125.212.0.0/16
125.213.128.0/24
125.214.0.0/16
125.224.0.0/16
126.0.0.0/4
128.0.0.0/4
132.0.0.0/4
134.0.0.0/4
134.128.0.0/16
134.192.0.0/16
134.197.0.0/16
134.198.0.0/16
134.200.0.0/16
134.208.0.0/16
134.224.0.0/16
135.0.0.0/4
136.0.0.0/4
138.0.0.0/4
139.0.0.0/4
139.8.0.0/16
139.10.0.0/16
139.12.0.0/16
139.16.0.0/16
139.32.0.0/16
139.64.0.0/16
139.128.0.0/16
139.130.0.0/16
139.132.0.0/16
139.136.0.0/16
139.144.0.0/16
139.149.0.0/16
139.150.0.0/16
139.152.0.0/16
139.154.0.0/16
139.156.0.0/16
139.158.0.0/16
139.160.0.0/16
139.168.0.0/16
139.171.0.0/16
139.172.0.0/16
139.177.0.0/16
139.178.0.0/16
139.180.0.0/16
139.182.0.0/16
139.184.0.0/16
139.187.0.0/16
139.188.0.0/16
139.190.0.0/16
139.192.0.0/16
139.216.0.0/16
139.218.0.0/16
139.222.0.0/16
139.225.0.0/16
139.228.0.0/16
139.232.0.0/16
139.240.0.0/16
140.0.0.0/4
140.64.0.0/16
140.72.0.0/16
140.74.0.0/16
140.76.0.0/16
140.80.0.0/16
140.96.0.0/16
140.128.0.0/16
140.136.0.0/16
140.140.0.0/16
140.142.0.0/16
140.144.0.0/16
140.160.0.0/16
140.192.0.0/16
140.200.0.0/16
140.204.0.0/16
140.208.0.0/16
140.211.0.0/16
140.212.0.0/16
140.216.0.0/16
140.225.0.0/16
140.226.0.0/16
140.228.0.0/16
140.232.0.0/16
140.236.0.0/16
140.238.0.0/16
140.241.0.0/16
140.242.0.0/16
140.244.0.0/16
140.247.0.0/16
140.248.0.0/16
140.251.0.0/16
140.252.0.0/16
140.254.0.0/16
141.0.0.0/4
142.0.0.0/4
144.2.0.0/16
144.4.0.0/16
144.6.0.0/16
144.8.0.0/16
144.13.0.0/16
144.14.0.0/16
144.16.0.0/16
144.32.0.0/16
144.48.0.0/16
144.53.0.0/16
144.54.0.0/16
144.56.0.0/16
144.64.0.0/16
144.96.0.0/16
144.112.0.0/16
144.120.0.0/16
144.122.0.0/16
144.124.0.0/16
144.128.0.0/16
144.192.0.0/16
144.224.0.0/16
144.240.0.0/16
144.248.0.0/16
144.252.0.0/16
144.254.0.0/16
145.0.0.0/4
146.0.0.0/4
148.0.0.0/4
150.1.0.0/16
150.2.0.0/16
150.4.0.0/16
150.8.0.0/16
150.16.0.0/16
150.32.0.0/16
150.64.0.0/16
150.96.0.0/16
150.112.0.0/16
150.114.0.0/16
150.116.0.0/16
150.120.0.0/16
150.123.0.0/16
150.124.0.0/16
150.128.0.0/16
150.136.0.0/16
150.140.0.0/16
150.144.0.0/16
150.160.0.0/16
150.192.0.0/16
150.208.0.0/16
150.216.0.0/16
150.220.0.0/16
150.222.0.0/16
150.224.0.0/16
150.240.0.0/16
150.248.0.0/16
150.252.0.0/16
150.254.0.0/16
151.0.0.0/4
152.0.0.0/4
152.64.0.0/16
152.96.0.0/16
152.104.0.0/16
152.105.0.0/16
152.106.0.0/16
152.108.0.0/16
152.112.0.0/16
152.128.0.0/16
153.1.0.0/16
153.2.0.0/16
153.4.0.0/16
153.8.0.0/16
153.16.0.0/16
153.32.0.0/16
153.38.0.0/16
153.40.0.0/16
153.48.0.0/16
153.64.0.0/16
153.96.0.0/16
153.98.0.0/16
153.100.0.0/16
153.102.0.0/16
153.104.0.0/16
153.112.0.0/16
153.116.0.0/16
153.120.0.0/16
153.128.0.0/16
154.0.0.0/4
156.0.0.0/4
157.1.0.0/16
157.2.0.0/16
157.4.0.0/16
157.8.0.0/16
157.16.0.0/16
157.19.0.0/16
157.20.0.0/16
157.24.0.0/16
157.32.0.0/16
157.48.0.0/16
157.56.0.0/16
157.60.0.0/16
157.62.0.0/16
157.64.0.0/16
157.96.0.0/16
157.112.0.0/16
157.120.0.0/16
157.123.0.0/16
157.124.0.0/16
157.128.0.0/16
157.144.0.0/16
157.149.0.0/16
157.150.0.0/16
157.152.0.0/16
157.157.0.0/16
157.158.0.0/16
157.160.0.0/16
157.192.0.0/16
157.224.0.0/16
157.240.0.0/16
157.248.0.0/16
157.252.0.0/16
157.254.0.0/16
158.0.0.0/4
159.0.0.0/4
159.128.0.0/16
159.192.0.0/16
159.224.0.0/16
159.227.0.0/16
159.228.0.0/16
159.232.0.0/16
159.240.0.0/16
160.0.0.0/4
161.0.0.0/4
161.128.0.0/16
161.192.0.0/16
161.200.0.0/16
161.204.0.0/16
161.206.0.0/16
161.208.0.0/16
161.224.0.0/16
162.0.0.0/4
162.64.0.0/16
162.96.0.0/16
162.104.0.0/16
162.106.0.0/16
162.108.0.0/16
162.112.0.0/16
162.128.0.0/16
163.1.0.0/16
163.2.0.0/16
163.4.0.0/16
163.8.0.0/16
163.16.0.0/16
163.32.0.0/16
163.64.0.0/16
163.96.0.0/16
163.112.0.0/16
163.120.0.0/16
163.124.0.0/16
163.126.0.0/16
163.128.0.0/16
163.136.0.0/16
163.140.0.0/16
163.143.0.0/16
163.144.0.0/16
163.160.0.0/16
163.176.0.0/16
163.178.0.0/16
163.180.0.0/16
163.184.0.0/16
163.192.0.0/16
163.200.0.0/16
163.205.0.0/16
163.206.0.0/16
163.208.0.0/16
163.224.0.0/16
164.0.0.0/4
166.0.0.0/4
166.64.0.0/16
166.96.0.0/16
166.104.0.0/16
166.108.0.0/16
166.110.0.0/16
166.112.0.0/16
166.128.0.0/16
167.0.0.0/4
167.128.0.0/16
167.136.0.0/16
167.138.0.0/16
167.140.0.0/16
167.144.0.0/16
167.160.0.0/16
167.176.0.0/16
167.184.0.0/16
167.188.0.0/16
167.190.0.0/16
167.192.0.0/16
168.0.0.0/4
168.128.0.0/16
168.161.0.0/16
168.162.0.0/16
168.164.0.0/16
168.168.0.0/16
168.176.0.0/16
168.192.0.0/16
169.0.0.0/4
169.128.0.0/16
169.192.0.0/16
169.224.0.0/16
169.240.0.0/16
169.248.0.0/16
169.252.0.0/16
169.255.0.0/16
170.0.0.0/4
171.0.0.0/4
171.16.0.0/16
171.32.0.0/16
171.48.0.0/16
171.64.0.0/16
171.96.0.0/16
171.128.0.0/16
171.192.0.0/16
171.224.0.0/16
172.0.0.0/4
172.32.0.0/16
172.64.0.0/16
172.128.0.0/16
173.0.0.0/4
174.0.0.0/4
175.28.0.0/16
175.32.0.0/16
175.40.0.0/16
175.45.0.0/16
175.96.0.0/16
175.100.0.0/16
175.103.0.0/16
175.104.0.0/16
175.106.0.0/16
175.107.0.0/16
175.108.0.0/16
175.112.0.0/16
175.128.0.0/16
175.144.0.0/16
175.156.0.0/16
175.176.0.0/16
175.179.0.0/16
175.180.0.0/16
175.184.0.0/16
175.192.0.0/16
176.0.0.0/4
180.0.0.0/4
180.64.0.0/16
180.72.0.0/16
180.80.0.0/16
180.87.0.0/16
180.92.0.0/16
180.94.0.0/16
180.95.0.0/16
180.128.0.0/16
180.129.0.0/16
180.131.0.0/16
180.132.0.0/16
180.144.0.0/16
180.176.0.0/16
180.188.128.0/24
180.189.0.0/16
180.190.0.0/16
180.192.0.0/16
180.200.0.0/16
180.204.0.0/16
180.210.0.0/16
180.214.0.0/16
180.216.0.0/16
180.220.0.0/16
180.222.0.0/16
180.224.0.0/16
181.0.0.0/4
182.0.0.0/4
182.16.0.0/16
182.18.128.0/24
182.19.0.0/16
182.20.0.0/16
182.24.0.0/16
182.48.0.0/16
182.50.0.0/16
182.52.0.0/16
182.54.128.0/24
182.55.0.0/16
182.56.0.0/16
182.60.0.0/16
182.62.0.0/16
182.64.0.0/16
182.93.0.0/16
182.94.0.0/16
182.152.0.0/16
182.156.0.0/16
182.158.0.0/16
182.160.0.0/16
182.168.0.0/16
182.172.0.0/16
182.176.0.0/16
182.192.0.0/16
182.208.0.0/16
182.224.0.0/16
182.232.0.0/16
182.236.0.0/16
182.237.0.0/16
182.239.0.0/16
182.248.0.0/16
182.252.0.0/16
182.255.0.0/16
183.72.0.0/16
183.80.0.0/16
183.86.0.0/16
183.88.0.0/16
183.96.0.0/16
183.171.0.0/16
183.176.0.0/16
184.0.0.0/4
192.128.0.0/16
192.160.0.0/16
192.169.0.0/16
192.170.0.0/16
192.172.0.0/16
192.176.0.0/16
192.192.0.0/16
193.0.0.0/4
194.0.0.0/4
196.0.0.0/4
198.0.0.0/4
198.16.0.0/16
198.20.0.0/16
198.24.0.0/16
198.32.0.0/16
198.64.0.0/16
198.128.0.0/16
199.0.0.0/4
200.0.0.0/4
202.0.0.0/4
202.64.0.0/16
202.122.0.0/16
202.124.0.0/16
202.128.0.0/16
202.208.0.0/16
202.224.0.0/16
203.0.0.0/4
203.64.0.0/16
203.96.0.0/16
203.104.0.0/16
203.106.0.0/16
203.107.128.0/24
203.108.0.0/16
203.112.0.0/16
203.116.0.0/16
203.118.0.0/16
203.119.0.0/16
203.120.0.0/16
203.128.0.0/16
203.192.0.0/16
203.194.0.0/16
203.195.0.0/16
203.196.0.0/16
203.200.0.0/16
203.204.0.0/16
203.205.0.0/16
203.206.0.0/16
203.207.0.0/16
203.208.0.0/16
203.224.0.0/16
204.0.0.0/4
208.0.0.0/4
208.85.110.0/24
210.0.0.0/4
210.8.0.0/16
210.14.0.0/16
210.16.0.0/16
210.20.0.0/16
210.23.0.0/16
210.24.0.0/16
210.48.0.0/16
210.50.0.0/16
210.52.0.0/16
210.54.0.0/16
210.56.0.0/16
210.64.0.0/16
210.78.0.0/16
210.80.0.0/16
210.84.0.0/16
210.88.0.0/16
210.96.0.0/16
210.128.0.0/16
211.0.0.0/4
211.72.0.0/16
211.104.0.0/16
211.112.0.0/16
211.128.0.0/16
211.155.0.0/16
211.168.0.0/16
211.176.0.0/16
211.192.0.0/16
212.0.0.0/4
216.0.0.0/4
218.32.0.0/16
218.48.0.0/16
218.98.128.0/24
218.100.0.0/16
218.101.0.0/16
218.102.0.0/16
218.110.0.0/16
218.112.0.0/16
218.128.0.0/16
218.208.0.0/16
218.224.0.0/16
218.248.0.0/16
218.250.0.0/16
218.252.0.0/16
219.0.0.0/4
219.64.0.0/16
219.73.0.0/16
219.74.0.0/16
219.76.0.0/16
219.80.0.0/16
219.83.0.0/16
219.84.0.0/16
219.88.0.0/16
219.96.0.0/16
219.160.0.0/16
219.192.0.0/16
219.208.0.0/16
219.240.0.0/16
219.248.0.0/16
220.0.0.0/4
220.64.0.0/16
220.96.0.0/16
220.116.0.0/16
220.120.0.0/16
220.128.0.0/16
220.144.0.0/16
220.152.0.0/16
220.153.0.0/16
220.156.0.0/16
220.208.0.0/16
220.224.0.0/16
220.228.0.0/16
220.230.0.0/16
220.231.0.0/16
220.232.0.0/16
220.235.0.0/16
220.236.0.0/16
220.240.0.0/16
220.244.0.0/16
220.253.0.0/16
220.254.0.0/16
221.12.128.0/24
221.16.0.0/16
221.32.0.0/16
221.64.0.0/16
221.96.0.0/16
221.112.0.0/16
221.120.0.0/16
221.124.0.0/16
221.128.0.0/16
221.132.0.0/16
221.138.0.0/16
221.140.0.0/16
221.144.0.0/16
221.160.0.0/16
221.168.0.0/16
221.184.0.0/16
221.199.0.0/16
221.240.0.0/16
222.0.0.0/4
222.96.0.0/16
222.112.0.0/16
222.120.0.0/16
222.124.0.0/16
222.126.0.0/16
222.127.0.0/16
222.144.0.0/16
222.164.0.0/16
222.224.0.0/16
222.250.0.0/16
222.252.0.0/16
223.16.0.0/16
223.22.0.0/16
223.24.0.0/16
223.32.0.0/16
223.118.0.0/16
223.130.0.0/16
223.132.0.0/16
223.136.0.0/16
223.164.0.0/16
223.168.0.0/16
223.176.0.0/16
223.194.0.0/16
223.196.0.0/16
223.200.0.0/16
223.204.0.0/16
223.216.0.0/16
223.222.0.0/16
223.224.0.0/16
223.252.0.0/16
223.253.0.0/16
223.255.128.0/24

试一下

**Comment by FQrabbit** [comment]
@Dreamone1 你直接在项目的规则文件夹下面点新建文件，然后粘贴进去，写好文件名，提交就行。谢谢🌚

**Comment by Shercoolcool** [comment]
需要增加游戏\程序名字
Nexon Launcher, MapleStory

该游戏\程序的运行环境
PC

该游戏\哪程序需要部分代理
游戏启动器，整个游戏

**Comment by bad7890** [comment]
可以的话也请添加一下steam的端
需要增加游戏\程序名字
MapleStory

该游戏\程序的运行环境
PC 

该游戏\哪程序需要部分代理
STEAM，整个游戏

**Comment by Shercoolcool** [comment]
安利一下netch，可以根据进程设置代理，代理maplestory很稳定。

**Comment by thisisjin** [comment]
> 安利一下netch，可以根据进程设置代理，代理maplestory很稳定。

扫描进程，然后修改配置文件，将0改为1吗。我的到了角色选择界面就闪退了

**Comment by Shercoolcool** [comment]
@thisisjin 我把nexon laucher文件夹和maplestory游戏根目录都扫描进去了，一共有14个进程。偶尔登录闪退再试一次就好了。
