### ISSUE TITLE
请求添加僵尸世界大战规则

### ISSUE THREAD

**Issue by lisheng15** [FQrabbit/SSTap-Rule#252]
**需要增加游戏\程序名字**
``World War Z``

**该游戏\程序的运行环境**
``PC``

**该游戏\程序哪部分需要代理**
``整个游戏\程序都需要``

**特殊情况**
不挂sstap人物会瞬移，挂了的话还是会显示网络不好，只能选择不代理中国IP

**Comment by STC214** [comment]
+1

**Comment by STC214** [comment]
=#worldwar Z,僵尸世界大战,0,0,1,0,0,0,By-STC214
3.17.151.0/24
5.8.24.0/24
5.8.26.0/24
13.69.131.0/24
13.69.134.0/24
13.74.65.0/24
13.74.160.0/24
13.79.34.0/24
13.79.134.0/24
13.79.171.0/24
13.79.190.0/24
13.90.144.0/24
13.90.201.0/24
13.124.0.0/16
13.124.1.0/24
13.124.145.16/32
13.125.0.0/16
13.209.0.0/16
13.209.73.0/24
15.164.0.0/16
15.164.100.0/24
18.88.41.0/24
18.194.0.0/16
18.203.69.0/24
18.221.254.0/24
18.223.32.0/24
18.223.108.0/24
18.224.38.0/24
20.41.64.0/24
23.96.0.0/16
23.101.54.0/24
23.102.24.0/24
23.212.12.0/24
31.13.95.0/24
34.238.208.161/32
34.244.98.0/24
34.252.62.0/24
34.252.145.0/24
35.153.154.4/32
35.156.40.0/24
40.68.1.0/24
40.68.86.0/24
40.69.58.0/24
40.69.61.0/24
40.69.216.0/24
40.69.223.0/24
40.85.83.0/24
40.85.160.0/24
40.87.131.0/24
40.87.154.0/24
40.112.48.0/24
40.112.72.0/24
40.112.76.0/24
40.112.77.0/24
40.112.79.0/24
40.112.88.0/24
40.112.95.0/24
40.113.148.0/24
40.114.0.0/16
40.115.96.0/24
40.117.64.0/24
40.121.0.0/16
40.127.97.0/24
40.127.105.0/24
40.127.134.0/24
49.7.8.22/32
52.19.31.0/24
52.49.222.0/24
52.53.89.0/24
52.78.0.0/16
52.78.247.128/32
52.79.0.0/16
52.87.134.163/32
52.92.0.0/16
52.94.6.0/24
52.94.198.64/32
52.94.248.176/32
52.95.111.0/24
52.95.192.0/24
52.95.252.0/24
52.138.139.0/24
52.138.160.0/24
52.138.163.0/24
52.138.221.0/24
52.141.0.0/16
52.141.32.0/24
52.141.33.0/24
52.141.34.0/24
52.141.35.0/24
52.141.36.0/24
52.141.37.0/24
52.141.38.0/24
52.141.39.0/24
52.164.209.0/24
52.164.215.0/24
52.164.223.0/24
52.164.253.0/24
52.166.0.0/16
52.168.120.0/24
52.169.6.0/24
52.169.150.0/24
52.169.251.0/24
52.178.41.0/24
52.178.167.0/24
52.178.222.0/24
52.186.0.0/16
52.219.56.0/24
52.219.60.0/24
52.224.0.0/16
52.226.65.0/24
52.231.0.0/16
52.231.10.0/24
52.231.14.0/24
52.231.15.0/24
52.231.24.0/24
52.231.25.0/24
52.231.26.0/24
52.231.27.0/24
52.231.28.0/24
52.231.29.0/24
52.231.30.0/24
52.231.31.0/24
52.231.32.0/24
52.231.33.0/24
52.231.34.0/24
52.231.35.0/24
52.231.36.0/24
52.231.38.0/24
52.231.39.0/24
52.231.65.0/24
52.231.66.0/24
52.231.67.0/24
52.231.68.0/24
52.231.69.0/24
52.231.70.0/24
52.231.71.0/24
52.231.72.0/24
52.231.73.0/24
52.231.74.0/24
52.231.75.0/24
52.231.76.0/24
52.231.77.0/24
52.231.78.0/24
52.231.79.0/24
52.236.35.0/24
52.236.57.0/24
52.236.59.0/24
54.171.114.0/24
54.180.0.0/16
54.225.215.0/24
54.239.0.192/32
54.239.116.0/24
54.239.120.0/24
54.239.130.0/24
92.38.148.0/24
92.38.186.0/24
92.38.187.0/24
94.245.91.0/24
99.82.168.0/24
104.41.226.0/24
104.41.229.0/24
104.45.128.0/24
104.211.0.0/16
108.177.98.0/24
123.129.254.0/24
137.116.235.0/24
137.116.251.0/24
137.117.88.0/24
137.135.160.0/24
137.135.162.0/24
137.135.245.0/24
155.89.14.0/24
162.245.204.0/24
168.63.79.0/24
183.111.26.0/24
211.44.226.0/24
212.64.116.0/24
218.28.144.0/24
220.250.64.0/24
221.204.244.0/24
3.17.151.0/24
5.8.24.0/24
5.8.26.0/24
13.69.131.0/24
13.69.134.0/24
13.74.65.0/24
13.74.160.0/24
13.79.34.0/24
13.79.134.0/24
13.79.171.0/24
13.79.190.0/24
13.90.144.0/24
13.90.201.0/24
13.124.0.0/16
13.124.1.0/24
13.124.145.16/32
13.125.0.0/16
13.209.0.0/16
13.209.73.0/24
15.164.0.0/16
15.164.100.0/24
18.88.41.0/24
18.194.0.0/16
18.203.69.0/24
18.221.254.0/24
18.223.32.0/24
18.223.108.0/24
18.224.38.0/24
20.41.64.0/24
23.96.0.0/16
23.101.54.0/24
23.102.24.0/24
23.212.12.0/24
31.13.95.0/24
34.238.208.161/32
34.244.98.0/24
34.252.62.0/24
34.252.145.0/24
35.153.154.4/32
35.156.40.0/24
40.68.1.0/24
40.68.86.0/24
40.69.58.0/24
40.69.61.0/24
40.69.216.0/24
40.69.223.0/24
40.85.83.0/24
40.85.160.0/24
40.87.131.0/24
40.87.154.0/24
40.112.48.0/24
40.112.72.0/24
40.112.76.0/24
40.112.77.0/24
40.112.79.0/24
40.112.88.0/24
40.112.95.0/24
40.113.148.0/24
40.114.0.0/16
40.115.96.0/24
40.117.64.0/24
40.121.0.0/16
40.127.97.0/24
40.127.105.0/24
40.127.134.0/24
52.19.31.0/24
52.49.222.0/24
52.53.89.0/24
52.78.0.0/16
52.78.247.128/32
52.79.0.0/16
52.87.134.163/32
52.92.0.0/16
52.94.6.0/24
52.94.198.64/32
52.94.248.176/32
52.95.111.0/24
52.95.192.0/24
52.95.252.0/24
52.138.139.0/24
52.138.160.0/24
52.138.163.0/24
52.138.221.0/24
52.141.0.0/16
52.141.32.0/24
52.141.33.0/24
52.141.34.0/24
52.141.35.0/24
52.141.36.0/24
52.141.37.0/24
52.141.38.0/24
52.141.39.0/24
52.164.209.0/24
52.164.215.0/24
52.164.223.0/24
52.164.253.0/24
52.166.0.0/16
52.168.120.0/24
52.169.6.0/24
52.169.150.0/24
52.169.251.0/24
52.178.41.0/24
52.178.167.0/24
52.178.222.0/24
52.186.0.0/16
52.219.56.0/24
52.219.60.0/24
52.224.0.0/16
52.226.65.0/24
52.231.0.0/16
52.231.10.0/24
52.231.14.0/24
52.231.15.0/24
52.231.24.0/24
52.231.25.0/24
52.231.26.0/24
52.231.27.0/24
52.231.28.0/24
52.231.29.0/24
52.231.30.0/24
52.231.31.0/24
52.231.32.0/24
52.231.33.0/24
52.231.34.0/24
52.231.35.0/24
52.231.36.0/24
52.231.38.0/24
52.231.39.0/24
52.231.65.0/24
52.231.66.0/24
52.231.67.0/24
52.231.68.0/24
52.231.69.0/24
52.231.70.0/24
52.231.71.0/24
52.231.72.0/24
52.231.73.0/24
52.231.74.0/24
52.231.75.0/24
52.231.76.0/24
52.231.77.0/24
52.231.78.0/24
52.231.79.0/24
52.236.35.0/24
52.236.57.0/24
52.236.59.0/24
54.171.114.0/24
54.180.0.0/16
54.225.215.0/24
54.239.0.192/32
54.239.116.0/24
54.239.120.0/24
54.239.130.0/24
59.37.129.66/32
92.38.148.0/24
92.38.186.0/24
92.38.187.0/24
94.245.91.0/24
99.82.168.0/24
104.41.226.0/24
104.41.229.0/24
104.45.128.0/24
104.211.0.0/16
108.177.98.0/24
123.129.254.0/24
137.116.235.0/24
137.116.251.0/24
137.117.88.0/24
137.135.160.0/24
137.135.162.0/24
137.135.245.0/24
155.89.14.0/24
162.245.204.0/24
168.63.79.0/24
183.111.26.0/24
211.44.226.0/24
212.64.116.0/24
218.28.144.0/24
220.250.64.0/24
221.204.244.0/24
3.17.151.0/24
5.8.24.0/24
5.8.26.0/24
13.69.131.0/24
13.69.134.0/24
13.74.65.0/24
13.74.160.0/24
13.79.34.0/24
13.79.134.0/24
13.79.171.0/24
13.79.190.0/24
13.90.144.0/24
13.90.201.0/24
13.124.0.0/16
13.124.1.0/24
13.124.145.16/32
13.125.0.0/16
13.209.0.0/16
13.209.73.0/24
15.164.0.0/16
15.164.100.0/24
18.88.41.0/24
18.194.0.0/16
18.203.69.0/24
18.221.254.0/24
18.223.32.0/24
18.223.108.0/24
18.224.38.0/24
20.41.64.0/24
23.96.0.0/16
23.101.54.0/24
23.102.24.0/24
23.212.12.0/24
31.13.95.0/24
34.238.208.161/32
34.244.98.0/24
34.252.62.0/24
34.252.145.0/24
35.153.154.4/32
35.156.40.0/24
40.68.1.0/24
40.68.86.0/24
40.69.58.0/24
40.69.61.0/24
40.69.216.0/24
40.69.223.0/24
40.85.83.0/24
40.85.160.0/24
40.87.131.0/24
40.87.154.0/24
40.112.48.0/24
40.112.72.0/24
40.112.76.0/24
40.112.77.0/24
40.112.79.0/24
40.112.88.0/24
40.112.95.0/24
40.113.148.0/24
40.114.0.0/16
40.115.96.0/24
40.117.64.0/24
40.121.0.0/16
40.127.97.0/24
40.127.105.0/24
40.127.134.0/24
52.19.31.0/24
52.49.222.0/24
52.53.89.0/24
52.78.0.0/16
52.78.247.128/32
52.79.0.0/16
52.87.134.163/32
52.92.0.0/16
52.94.6.0/24
52.94.198.64/32
52.94.248.176/32
52.95.111.0/24
52.95.192.0/24
52.95.252.0/24
52.138.139.0/24
52.138.160.0/24
52.138.163.0/24
52.138.221.0/24
52.141.0.0/16
52.141.32.0/24
52.141.33.0/24
52.141.34.0/24
52.141.35.0/24
52.141.36.0/24
52.141.37.0/24
52.141.38.0/24
52.141.39.0/24
52.164.209.0/24
52.164.215.0/24
52.164.223.0/24
52.164.253.0/24
52.166.0.0/16
52.168.120.0/24
52.169.6.0/24
52.169.150.0/24
52.169.251.0/24
52.178.41.0/24
52.178.167.0/24
52.178.222.0/24
52.186.0.0/16
52.219.56.0/24
52.219.60.0/24
52.224.0.0/16
52.226.65.0/24
52.231.0.0/16
52.231.10.0/24
52.231.14.0/24
52.231.15.0/24
52.231.24.0/24
52.231.25.0/24
52.231.26.0/24
52.231.27.0/24
52.231.28.0/24
52.231.29.0/24
52.231.30.0/24
52.231.31.0/24
52.231.32.0/24
52.231.33.0/24
52.231.34.0/24
52.231.35.0/24
52.231.36.0/24
52.231.38.0/24
52.231.39.0/24
52.231.65.0/24
52.231.66.0/24
52.231.67.0/24
52.231.68.0/24
52.231.69.0/24
52.231.70.0/24
52.231.71.0/24
52.231.72.0/24
52.231.73.0/24
52.231.74.0/24
52.231.75.0/24
52.231.76.0/24
52.231.77.0/24
52.231.78.0/24
52.231.79.0/24
52.236.35.0/24
52.236.57.0/24
52.236.59.0/24
54.171.114.0/24
54.180.0.0/16
54.225.215.0/24
54.239.0.192/32
54.239.116.0/24
54.239.120.0/24
54.239.130.0/24
59.37.134.2/32
92.38.148.0/24
92.38.186.0/24
92.38.187.0/24
94.245.91.0/24
99.82.168.0/24
104.41.226.0/24
104.41.229.0/24
104.45.128.0/24
104.211.0.0/16
108.177.98.0/24
123.129.254.0/24
137.116.235.0/24
137.116.251.0/24
137.117.88.0/24
137.135.160.0/24
137.135.162.0/24
137.135.245.0/24
155.89.14.0/24
162.245.204.0/24
168.63.79.0/24
183.111.26.0/24
211.44.226.0/24
212.64.116.0/24
218.28.144.0/24
220.250.64.0/24
221.204.244.0/24
