### ISSUE TITLE
请求增加刀塔霸业的代理规则

### ISSUE THREAD

**Issue by shuyaoyimei** [FQrabbit/SSTap-Rule#254]
**需要增加游戏\程序名字**
dota underlorads

**该游戏\程序的运行环境**
``PC``

**该游戏\程序哪部分需要代理**
如
``整个游戏\程序都需要``

**特殊情况**
uu加速器可以代理此游戏

**Comment by Maskeva** [comment]
你有UU加速账号么  有VIP的话可以导出规则

**Comment by AmazingDM** [comment]
https://github.com/netchx/Netch
此工具将逐步代替SSTap 无需繁琐代理规则

**Comment by Wenlu2019** [comment]
我也想求这个。现在用的是Dota2日服的加速，感觉还行
ss或ssr+sstap，后者代理规则选sock5，127.0.0.1/1080可以对UDP加速
因为越来越多的游戏必须UDP加速，很多加速方法都不行了

**Comment by 72521** [comment]
`
#Dota Underlords,刀塔霸业,0,0,1,0,1,0,By-72521
47.74.154.0/24
69.171.245.84/32
103.10.124.0/24
103.10.125.0/24
146.66.154.0/24
153.254.86.0/24
155.133.232.0/24
155.133.235.0/24
155.133.239.0/24
155.133.245.0/24
155.133.248.0/24
155.133.253.0/24
155.133.254.0/24
162.254.192.0/24
162.254.193.0/24
162.254.195.0/24
162.254.196.0/24
162.254.197.0/24
183.240.169.101/32
205.196.6.0/24
`

**Comment by 72521** [comment]
> **需要增加游戏\程序名字**
> dota underlorads
> 
> **该游戏\程序的运行环境**
> `PC`
> 
> **该游戏\程序哪部分需要代理**
> 如
> `整个游戏\程序都需要`
> 
> **特殊情况**
> uu加速器可以代理此游戏

[Dota-Underlords-uu.zip](https://github.com/FQrabbit/SSTap-Rule/files/3341915/Dota-Underlords-uu.zip)
