### ISSUE TITLE
请求增加火箭联盟（rocket league）steam版的规则

### ISSUE THREAD

**Issue by CCneorg** [FQrabbit/SSTap-Rule#262]
**需要增加游戏\程序名字**
火箭联盟（rocket league）

**该游戏\程序的运行环境**
PC steam平台

**该游戏\程序哪部分需要代理**
整个游戏\程序都需要

**特殊情况**
腾讯网游加速器能代理此游戏

**Comment by 72521** [comment]
> **需要增加游戏\程序名字**
> 火箭联盟（rocket league）
> 
> **该游戏\程序的运行环境**
> PC steam平台
> 
> **该游戏\程序哪部分需要代理**
> 整个游戏\程序都需要
> 
> **特殊情况**
> 腾讯网游加速器能代理此游戏

[Rocket-League-uu.zip](https://github.com/FQrabbit/SSTap-Rule/files/3342097/Rocket-League-uu.zip)

_根据WIKI教程提取，自己测试_

**Comment by CCneorg** [comment]
网易uu加速器是火箭联盟国服的规则吧，我看了下没有加速steam版的规则



------------------ 原始邮件 ------------------
发件人: "72521"<notifications@github.com>; 
发送时间: 2019年6月30日(星期天) 凌晨0:34
收件人: "FQrabbit/SSTap-Rule"<SSTap-Rule@noreply.github.com>; 
抄送: "幸运信息"<245293411@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [FQrabbit/SSTap-Rule] 请求增加火箭联盟（rocket league）steam版的规则 (#262)



 
需要增加游戏\程序名字
 火箭联盟（rocket league）
 
该游戏\程序的运行环境
 PC steam平台
 
该游戏\程序哪部分需要代理
 整个游戏\程序都需要
 
特殊情况
 腾讯网游加速器能代理此游戏
  
Rocket-League-uu.zip
 
根据WIKI教程提取，自己测试

**Comment by slightilusion** [comment]
你好
