### ISSUE TITLE
请求增加极限巅峰(steep)steam版的规则

### ISSUE THREAD

**Issue by GoogleDaddy** [FQrabbit/SSTap-Rule#266]
**需要增加游戏\程序名字**
极限巅峰(steep)

**该游戏\程序的运行环境**
PC steam平台

**该游戏\程序哪部分需要代理**
整个游戏\程序都需要

**特殊情况**
最新规则包有steep，但使用了进游戏还是连接失败

**Comment by NormanBB** [comment]
[steep.zip](https://github.com/FQrabbit/SSTap-Rule/files/3590908/steep.zip)

能帮我测试一下吗
