### ISSUE TITLE
请求增加Minecraft国际版(JAVA)规则

### ISSUE THREAD

**Issue by ZvonimirSun** [FQrabbit/SSTap-Rule#27]
**需要增加游戏\程序名字**
Minecraft国际版(JAVA)

**该游戏\程序的运行环境**
PC java

**该游戏\程序哪部分需要代理**
代理多人游戏连接、正版登陆器登录、下载客户端

**Comment by FQrabbit** [comment]
@ZvonimirSun 这款游戏，你可以直接把服务器的ip填到规则里面，单独代理这个mc服务器，而且mc java我记得是走TCP的🤔
这个应该不用项目更新🤔毕竟每个服务器都不一样，这个完全可以自己填规则🤔

**Comment by FQrabbit** [comment]
@ZvonimirSun 原来你说下载器啊🌚，我以为你说那些小游戏的服务器

**Comment by ZvonimirSun** [comment]
@FQrabbit hi@iszy.me

**Comment by FQrabbit** [comment]
@ZvonimirSun 已发送

**Comment by FQrabbit** [comment]
如果您有Telegram的联系方式那就更方便了
