### ISSUE TITLE
为什么不试试新出的kkcap呢?可以按进程加速 也能看到加速的ip，同样适用ss服务器

### ISSUE THREAD

**Issue by fuzzyscn** [FQrabbit/SSTap-Rule#271]
也可以检测进程链接的IP
推荐游戏玩家使用 最近刚发现的替代sstap的软件
https://www.kkcap.net/cn/index.html
![image](https://user-images.githubusercontent.com/40295154/61197398-470aa380-a707-11e9-9133-8ab700df3ad9.png)
KKCap 免费的代理上网软件
支持Socks5,ShadowSocks等协议
完美兼容TCP/UDP协议
最好的免费网络游戏加速器,可以仅代理选定的应用进程。
科学加速
全部支持
支持TCP,UDP,IPv4,IPv6

特别适合加速外服网络游戏 
轻松设置,支持指定应用程序

如:(游戏,浏览器,电子邮件等)联网程序代理。
轻量级,灵活的小工具,无需对被代理的应用程序做任何修改和设置。
比Proxifier,SSTap类软件更简单

**Comment by ycfnzz** [comment]
不开源 怕被请喝茶
