### ISSUE TITLE
请求：大佬RUST的规则在哪里 麻烦增加一个

### ISSUE THREAD

**Issue by aknee1ccc** [FQrabbit/SSTap-Rule#273]
**需要增加游戏\程序名字**
RUST

**该游戏\程序的运行环境**
如
``局域网其他设备``
``PC``

**该游戏\程序哪部分需要代理**
如
``整个游戏\程序都需要``

**特殊情况**
如果还有特殊想说明的请在这里描述.

**Comment by NormanBB** [comment]
哪个服？

**Comment by xiaopeng758** [comment]
rust  亚服   美服  欧服 澳服
