### ISSUE TITLE
Dota Underlords 刀塔霸业 有部分ip不在规则内。

### ISSUE THREAD

**Issue by kokutoukiritsugu** [FQrabbit/SSTap-Rule#274]
打了几局看了下，加进去了。

34.85.12.153/32
35.134.30.129/32
47.74.154.0/24
69.171.245.84/32
103.10.124.0/24
103.10.125.0/24
146.66.154.0/24
146.66.155.0/24
153.254.86.0/24
155.133.230.0/24
155.133.232.0/24
155.133.233.0/24
155.133.235.0/24
155.133.238.0/24
155.133.239.0/24
155.133.245.0/24
155.133.246.0/24
155.133.248.0/24
155.133.249.0/24
155.133.252.0/24
155.133.253.0/24
155.133.254.0/24
162.254.192.0/24
162.254.193.0/24
162.254.195.0/24
162.254.196.0/24
162.254.197.0/24
162.254.198.0/24
162.254.199.0/24
183.240.169.101/32
185.25.182.68/32
185.25.183.17/32
190.217.33.0/24
205.196.6.0/24
205.185.194.36/32
205.196.6.74/32

**Comment by kokutoukiritsugu** [comment]
规则文件
[Dota-Underlords.rules.zip](https://github.com/FQrabbit/SSTap-Rule/files/3404950/Dota-Underlords.rules.zip)

**Comment by NormanBB** [comment]
可考虑提交pull request.
