### ISSUE TITLE
请求添加怪物猎人世界steam版规则

### ISSUE THREAD

**Issue by suraxiuxiu** [FQrabbit/SSTap-Rule#275]
**需要增加游戏\程序名字**
怪物猎人世界

**该游戏\程序的运行环境**
PC steam

**该游戏\程序哪部分需要代理**
``整个游戏\程序都需要``

**Comment by coolyzp** [comment]
同求

**Comment by NormanBB** [comment]
[Monster Hunter World.zip](https://github.com/FQrabbit/SSTap-Rule/files/3590876/Monster.Hunter.World.zip)

能帮我测试一下吗
