### ISSUE TITLE
warframe  开启代理后 启动器显示更新失败

### ISSUE THREAD

**Issue by XZMK** [FQrabbit/SSTap-Rule#278]
**问题描述**
Warframe 开启规则后 游戏启动器显示更新失败 即使游戏没有更新
不开规则启动器正常 但是检查更新会卡几分钟以及交易频道聊天掉线

**截图**
![image](https://user-images.githubusercontent.com/51074922/61946441-2e3aa180-afd5-11e9-81f8-fd27310c8f52.png)

**运行环境**
WIN10 1809 中国电信  不开代理登陆后能正常与老外交易

**Comment by xyx0826** [comment]
Warframe 游戏服务屏蔽了大部分数据中心的 IP 并对请求返回 403。

**Comment by NormanBB** [comment]
更新可以考虑使用仅代理浏览器。再者可以改warframe的hosts
