### ISSUE TITLE
极限竞速地平线4 sstap规则

### ISSUE THREAD

**Issue by Liu6217** [FQrabbit/SSTap-Rule#279]
没有UU的会员 然后这游戏也不能游戏加加保存IP只能这样用v2ray全局模式抓的服务器 然后用CMD一个一个ping服务器找到IP 这工作量...当然 其它游戏也能这样抓
https://drive.google.com/open?id=1RORGEyUoftIXSvzU3Lw1m6hj59q1Jwex

图片教程和文件在谷歌盘里 图片里的红框内的是服务器 黄框是能下啦拖动的 拖动提取服务器  带.microsoft.com和.xbox.com的应该都是微软的 其它的应该不是 
服务器抓了要把 2019/07/29 17:24:08 tcp:127.0.0.1:61551 accepted tcp:这样的删除 然后在能到http://ip.tool.chinaz.com/ipbatch 批量提取IP 然后提取后 例如52.114.132.21 改成52.114.132.0/24 然后添加到你新建的规则IP里 
有啥可以交流交流 
等啥时候提取下GTA5的 目前用sstap NAT是完全 看看能不能弄成开放 GTA5就能用游戏加加提取IP了 
首先要把你的Teredo弄好了 这个东西网上教程一大堆

**Comment by D1ocom** [comment]
目前地平线4唯一可用，有立竿见影效果的加速器是奇游，可以拜托您做一个地平线4的奇游规则吗？我可以提供奇游帐号以供您测试。至于现在的这个规则，我在使用后并没有效果，同时使用后还会导致"NAT类型：Teredo无法进行限定"，我也想尝试着自行去提取一下，但相关的索引我找不到，您的这个教程对我来说无异于天书，毕竟我只是个小白

**Comment by NormanBB** [comment]
@D1ocom 关于地平线的联机问题，解决方案首先是解决teredo的问题，请自行搜索。如果解决了，可以不需要加速器。如果是关于自身网络的问题，日后会联系你来提供账号，目前，咕咕。

**Comment by D1ocom** [comment]
非常感谢您的回信。我目前的情况是：电信500M公网IP，但裸连仍然有很高的丢包导致不能玩线上(图丢包29%)，使用奇游加速器的话，丢包问题就可以解决(图丢包0%)。如果使用SSTap,目前的规则网络数据没有变化且会导致Teredo网络崩掉(图NAT类型限定)。我已经尝试着去学习怎样去抓取规则，但网络关于这方面的信息太少了，检索SSTAP 地平线4只有您的相关信息，而整个GitHub中，也只有这两条对应的规则且都没有作用。所以想试着联系您做一个地平线4奇游加速的SSTAP规则








------------------&nbsp;原始邮件&nbsp;------------------
发件人: "NormanBB"<notifications@github.com&gt;; 
发送时间: 2020年2月12日(星期三) 下午4:52
收件人: "FQrabbit/SSTap-Rule"<SSTap-Rule@noreply.github.com&gt;; 
抄送: "　　　 &amp;#x1F463;"<6456499@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [FQrabbit/SSTap-Rule] 极限竞速地平线4 sstap规则 (#279)




@D1ocom 关于地平线的联机问题，解决方案首先是解决teredo的问题，请自行搜索。如果解决了，可以不需要加速器。如果是关于自身网络的问题，日后会联系你来提供账号，目前，咕咕。

**Comment by D1ocom** [comment]
@NormanBB Teredo问题我是可以解决的，解决Teredo后裸连会有25%的丢包，所以必须使用加速器，目前唯一有左右的加速器是奇游。使用SSTAP的地平线规则后，反而会导致Teredo网络崩掉（NAT类型：Teredo无法进行限定；服务器连接：已阻止）且网络数据和裸连是一样的。所以想寻求一个地平线奇游加速的规则。
