### ISSUE TITLE
League-of-Legends-kr

### ISSUE THREAD

**Issue by Teemobabie** [FQrabbit/SSTap-Rule#28]
``League-of-Legends-kr``

``PC``

**该游戏\程序哪部分需要代理**
如
``整个游戏都需要``

**特殊情况**
我需要LOL韩服的股则
I need League-of-Legends-kr rules

**Comment by FQrabbit** [comment]
抱歉，这个游戏已经出现多例用户说明SSTap不能完整的代理这款游戏，表现如（游戏内置更新能走代理，真正连接游戏服务器会出错）
推荐使用SSTap作者的另一款程序 ```SocksCap64```
链接:[官网介绍页](https://www.sockscap64.com/zh-hans/homepage/)
