### ISSUE TITLE
请求添加YY语音规则，经常间歇性墙国外IP影响体验

### ISSUE THREAD

**Issue by Cjay-Chou** [FQrabbit/SSTap-Rule#285]

**Comment by Cjay-Chou** [comment]
自己抓了一个，能用，不保证大家都能用哈

14.17.109.0/24
14.17.112.0/24
42.56.75.0/24
45.255.126.0/24
60.223.222.0/24
61.133.52.0/24
61.146.73.0/24
61.156.199.0/24
103.49.134.0/24
110.185.109.0/24
112.25.57.0/24
112.90.174.0/24
113.107.236.0/24
120.52.140.0/24
122.13.211.0/24
124.115.10.0/24
175.153.60.0/24
180.208.65.0/24
182.247.249.0/24
183.60.166.0/24
183.240.18.0/24
219.151.23.0/24
220.194.67.0/24
223.99.234.0/24

**Comment by Cjay-Chou** [comment]
yy屏蔽国外ip, 使用中国节点回国

NormanBB <notifications@github.com> 于 2019年10月7日周一 18:06写道：

**Comment by NormanBB** [comment]
可使用目前issue里面的抓包工具尝试获取路由表。

**Comment by Cjay-Chou** [comment]
感谢

NormanBB <notifications@github.com> 于 2019年10月7日周一 22:23写道：
