### ISSUE TITLE
新枫之谷（台服）规则

### ISSUE THREAD

**Issue by emmy470** [FQrabbit/SSTap-Rule#286]
**新枫之谷（台服）**

**PC\虚拟机**

**整个游戏\程序，游戏官网都需要**

**Comment by faynwol** [comment]
需求+1

或者能否教下怎样获取这个游戏会连接的IP？

另外尝试过proxifier，似乎没作用

**Comment by cduyzh** [comment]
@faynwol 会的话大佬就不需要忙活了我们自己就能添加了

**Comment by faynwol** [comment]
@emmy470 提了个PR，亲测可用，不过中间游戏自己关闭了一次，不知道啥情况
#290

**Comment by tangxuchao** [comment]
> @ emmy470提了个PR，亲测可用，不过中间游戏自己关闭了一次，不知道啥情况
> [＃290](https://github.com/FQrabbit/SSTap-Rule/pull/290)

怎么使用？直接做一个rule文件 放进去用吗

**Comment by faynwol** [comment]
> > @ emmy470提了个PR，亲测可用，不过中间游戏自己关闭了一次，不知道啥情况
> > [＃290](https://github.com/FQrabbit/SSTap-Rule/pull/290)
> 
> 怎么使用？直接做一个rule文件 放进去用吗

https://github.com/FQrabbit/SSTap-Rule/blob/628a3071465cf3df240eb84b3f3a294d6add90c0/rules/TMS.rules
这个文件跟其他rules放一起

**Comment by emmy470** [comment]
> > > @ emmy470提了个PR，亲测可用，不过中间游戏自己关闭了一次，不知道啥情况
> > > [＃290](https://github.com/FQrabbit/SSTap-Rule/pull/290)
> > 
> > 
> > 怎么使用？直接做一个rule文件 放进去用吗
> 
> https://github.com/FQrabbit/SSTap-Rule/blob/628a3071465cf3df240eb84b3f3a294d6add90c0/rules/TMS.rules
> 这个文件跟其他rules放一起

谢谢大佬的支援！

**Comment by tangxuchao** [comment]
> > > @ emmy470提了个PR，亲测可用，不过中间游戏自己关闭了一次，不知道啥情况
> > > [＃290](https://github.com/FQrabbit/SSTap-Rule/pull/290)
> > 
> > 
> > 怎么使用？直接做一个rule文件 放进去用吗
> 
> https://github.com/FQrabbit/SSTap-Rule/blob/628a3071465cf3df240eb84b3f3a294d6add90c0/rules/TMS.rules
> 这个文件跟其他rules放一起

大佬，能做一个流亡黯道-台服的规则吗，我只找到国际服的规则

**Comment by faynwol** [comment]
> 大佬，能做一个流亡黯道-台服的规则吗，我只找到国际服的规则

@tangxuchao 淘宝租一个uu账号，按 [创建规则教程 之 提取加速器规则（超详细）](https://github.com/FQrabbit/SSTap-Rule/wiki/%E5%88%9B%E5%BB%BA%E8%A7%84%E5%88%99%E6%95%99%E7%A8%8B-%E4%B9%8B-%E6%8F%90%E5%8F%96%E5%8A%A0%E9%80%9F%E5%99%A8%E8%A7%84%E5%88%99%EF%BC%88%E8%B6%85%E8%AF%A6%E7%BB%86%EF%BC%89) 这个wiki做就行了
