### ISSUE TITLE
导入规则后，访问国内网站还是走代理

### ISSUE THREAD

**Issue by KangnakamuyiW** [FQrabbit/SSTap-Rule#287]
**问题描述**
我是下载了Skip-all-China-IP-and-LAN这个规则，选择完规则后然后启用，启用后去国内的测IP网站看到直接显示代理IP，哔哩哔哩看视频的时候也是走akamai的服务器，请问这是怎么回事？

**从哪里开始出现这个问题**
访问国内网站时

**截图**
![捕获](https://user-images.githubusercontent.com/47733293/62942834-bad5c400-be0b-11e9-84f8-90c0d05a010c.JPG)
![捕获2](https://user-images.githubusercontent.com/47733293/62942844-bf9a7800-be0b-11e9-9a13-1ac6c8fc459c.JPG)
![捕获3](https://user-images.githubusercontent.com/47733293/62942856-c2956880-be0b-11e9-989e-f7ecf100ef3d.JPG)

**运行环境**
操作系统：Windows 7 with Service Pack 1
网络环境：浙江移动
问题发现时间：2019-08-13 20:50

**Comment by BlackKxyz** [comment]
你为什么发给我..




在2019年08月13日 20:50，Kangna233 写道：

问题描述
我是下载了Skip-all-China-IP-and-LAN这个规则，选择完规则后然后启用，启用后去国内的测IP网站看到直接显示代理IP，哔哩哔哩看视频的时候也是走akamai的服务器，请问这是怎么回事？

从哪里开始出现这个问题
访问国内网站时

截图




运行环境
操作系统：Windows 7 with Service Pack 1
网络环境：浙江移动
问题发现时间：2019-08-13 20:50

**Comment by FQrabbit** [comment]
@Kangna233 应该是dns解析走了代理，所以解析成了bilibili的境外cdn，建议使用本地chinadns或者其他无污染dns

**Comment by thisisjin** [comment]
@FQrabbit 
请问，如果是使用SKIP CHINA AND LAN规则，DNS设置一栏该如何选择，
![image](https://user-images.githubusercontent.com/22115417/64856973-e4298000-d655-11e9-8d97-71bfb6d9c57e.png)
是自定义DNS ， 然后勾选“代理服务器选项”
还是选择“智能分流DNS”分别设置谷歌跟本地DNS呢

**Comment by NormanBB** [comment]
@thisisjin 目前问题依旧存在？

**Comment by catterdx** [comment]
@NormanBB 我也遇到类似的问题，比如访问weibo.com 如果使用谷歌DNS，就会跳转到weibo.us
我不清楚使用不同DNS的损溢，我比较倾向使用谷歌DNS.
别外，我发现使用智能分流DNS可以正常访问weibo.com.
属于小白，请求解答，谢谢
