### ISSUE TITLE
Skip All China IP and LAN 规则下电脑CPU占用过高

### ISSUE THREAD

**Issue by Hmmmmmmmmmm** [FQrabbit/SSTap-Rule#288]
**问题描述**
使用Skip All China IP and LAN 规则下电脑CPU占用过高
主要是两个进程占用CPU，分别是

- Service Host: Local Service (network restricted)
- Service Host: Quality Windows Audio Video Experience

**What I've tested**
断开连接或者使用 built-in 的Global模式，这两个进程很快消失。

**运行环境**
``操作系统``Windows 10, 
``网络环境``Strong & unmetered WiFi network, 运营商我猜是中国联通

**Comment by miaopasimiao** [comment]
Win10 开启代理后 CPU 占用很高
这是由一个 Win10 的一个网络检测服务所致，且一般发生在网络适配器开启了 IPv6 协议的情况下，SSTap 虚拟网卡创建的连接由于没有 IPv6 而被误认为是受限网络从而触发了检测。（大概）
如果您不使用或当前网络环境没有 IPv6，可以将网络适配器属性中的 IPv6 取消打勾。

**Comment by Hmmmmmmmmmm** [comment]
@miaopasimiao 
我所在的网络环境确实支持 IPv6 。
那要怎么解释 Global 模式下CPU占用突然下降到正常呢？

**Comment by Thinking2018** [comment]
我有着完全一样的问题
