### ISSUE TITLE
新增：巫师之昆特牌国服

### ISSUE THREAD

**Issue by cduyzh** [FQrabbit/SSTap-Rule#289]
**需要增加游戏\程序名字**
巫师之昆特牌国服

**该游戏\程序的运行环境**
如
``PC``

**该游戏\程序哪部分需要代理**
``整个游戏\程序都需要``

**特殊情况**
因为国服和国际服存在匹配到一起的情况下，所以只要匹配到外服的人就会掉线故希望增加

**Comment by NormanBB** [comment]
提取了其他加速器中，巫师昆特服国际服的规则。你可以试试。

[Gwent.zip](https://github.com/FQrabbit/SSTap-Rule/files/3590839/Gwent.zip)

**Comment by cduyzh** [comment]
@NormanBB 感谢 我看看
