### ISSUE TITLE
韩服跑跑卡丁车规则

### ISSUE THREAD

**Issue by ibq00** [FQrabbit/SSTap-Rule#297]
*需要增加游戏韩服跑跑卡丁车

**该游戏\程序的运行环境**
``PC``

**该游戏\程序哪部分需要代理**

``整个游戏\程序都需要``
我写的规则，测试一切正常！

[KartRider.zip](https://github.com/FQrabbit/SSTap-Rule/files/3582363/KartRider.zip)

**Comment by NormanBB** [comment]
请问你是用什么方法获取游戏所需的ip？

**Comment by ibq00** [comment]
> 请问你是用什么方法获取游戏所需的ip？

cports 这个工具抓取的，还有，要测试哦！

**Comment by NormanBB** [comment]
ty

**Comment by NormanBB** [comment]
请提交pull request.

**Comment by ibq00** [comment]
怎么提交？

**Comment by FQrabbit** [comment]
Merged
