### ISSUE TITLE
请问1097的内置规则有办法提取嘛。

### ISSUE THREAD

**Issue by thisisjin** [FQrabbit/SSTap-Rule#300]
我想在游戏的同时，利用浏览器去观看YouTube，
感觉如果知道这个 “浏览器不代理中国IP”的规则，再加上，游戏的代理规则。
就能解决我现在的需要了。 
请问有办法提取嘛

**Comment by NormanBB** [comment]
项目内有跳过中国的规则，而程序内置规则无法提取。
