### ISSUE TITLE
如何监控游戏的ip地址不是数字类的

### ISSUE THREAD

**Issue by xiaomoy** [FQrabbit/SSTap-Rule#309]
@FQrabbit 请问如何监控游戏的ip地址不是数字类的(111.111.11.11)而是字母类的，和网站的差不多(lpc-dl-ac.playbattlegrounds.com)

**Comment by FQrabbit** [comment]
应该大部分防火墙类的软件都能拦截到游戏程序请求的域名地址吧，好像windows资源监视器也能看到请求域名

**Comment by NormanBB** [comment]
@xiaomoy  问题仍然存在？

**Comment by PUBGLITE** [comment]
@oooldtoy 我的意思是要查到lpc-dl-ac.playbattlegrounds.com像这样的地址

**Comment by NormanBB** [comment]
@PUBGLITE  考虑下进tele群讨论？

你可以更新下绝地求生的相关规则吗？

**Comment by oooldtoy** [comment]
@PUBGLITE 上次获取到域名是在glasswire上

**Comment by PUBGLITE** [comment]
@NormanBB 有时间会更新的
