### ISSUE TITLE
路由器转rules没有输出

### ISSUE THREAD

**Issue by TheAnsIs42** [FQrabbit/SSTap-Rule#310]
**问题描述**
简单清晰的说一下问题的描述.
转换后无输出

**截图**
如果可以，请添加截图以帮助解释您的问题.
![SharedScreenshot](https://user-images.githubusercontent.com/44214674/65834435-c6554f80-e2d2-11e9-8e92-c8483511bbfa.jpg)

**运行环境**
win10
网易uu加速器 模式3 加速ff14国服神意之地

**Comment by NormanBB** [comment]
同时勾选其他模式。重试。

这样的输出表明uu加速器的模式三并不是用修改路由表的原理，则提取路由表的方法不可用。

**Comment by TheAnsIs42** [comment]
> 同时勾选其他模式。重试。
> 
> 这样的输出表明uu加速器的模式三并不是用修改路由表的原理，则提取路由表的方法不可用。

切换到模式12之后也是一样的

**Comment by NormanBB** [comment]
可能是提取路由表的方法对uu加速器的该游戏不可用。

你想加速国内服而不是国际服？

**Comment by NormanBB** [comment]
我去试用了uu加速器对于ff14（最终幻想14）国服的加速。模式三下有路由表的变化。

![批注 2019-10-02 212749](https://user-images.githubusercontent.com/18748504/66048100-8f459f00-e55b-11e9-8d35-aa950b4449e6.jpg)

**Comment by TheAnsIs42** [comment]
> 可能是提取路由表的方法对uu加速器的该游戏不可用。
> 
> 你想加速国内服而不是国际服？

是的，我在国外，好像有区别

**Comment by NormanBB** [comment]
那么你需要我这里的国服规则吗？

**Comment by TheAnsIs42** [comment]
> 那么你需要我这里的国服规则吗？

需要 非常感谢

**Comment by NormanBB** [comment]
[ff14.zip](https://github.com/FQrabbit/SSTap-Rule/files/3688959/ff14.zip)

试一下。

**Comment by TheAnsIs42** [comment]
> [ff14.zip](https://github.com/FQrabbit/SSTap-Rule/files/3689814/ff14.zip)
> 
> 试一下。

好的，非常感谢

**Comment by TheAnsIs42** [comment]
> [ff14.zip](https://github.com/FQrabbit/SSTap-Rule/files/3689814/ff14.zip)
> 
> 试一下。

有效，非常感谢
虽然很羞于启齿，能否麻烦您再做一下星际争霸2的国服规则，非常感谢。

**Comment by NormanBB** [comment]
[星际争霸2国服__route.txt](https://github.com/FQrabbit/SSTap-Rule/files/3692766/2.__route.txt)

你自己转换吧。

**Comment by TheAnsIs42** [comment]
> [星际争霸2国服__route.txt](https://github.com/FQrabbit/SSTap-Rule/files/3692766/2.__route.txt)
> 
> 你自己转换吧。

好的 非常感谢

**Comment by NormanBB** [comment]
你能不能帮我个忙，把这两个规则给项目提交更新？
