### ISSUE TITLE
希望增加vrchat的规则

### ISSUE THREAD

**Issue by sola97** [FQrabbit/SSTap-Rule#32]
**需要增加游戏\程序名字**
VRChat

**该游戏\程序的运行环境**
PC

**该游戏\程序哪部分需要代理**
整个游戏都需要
地图和角色好像是走TCP的
语音是UDP
视频加载内置的youtube-dl

**Comment by FQrabbit** [comment]
已经支持，期待你的尝试. 👍

**Comment by sola97** [comment]
其实最主要的是UDP语音，vrchat是用的photon引擎，连接的域名是
gcsc001.exitgames.com
...
gcsc007.exitgames.com
这七个
所以IP地址段需要加上
92.38.173.0/24

**Comment by GusRoth** [comment]
> 其实最主要的是UDP语音，vrchat是用的photon引擎，连接的域名是
> gcsc001.exitgames.com
> ...
> gcsc007.exitgames.com
> 这七个
> 所以IP地址段需要加上
> 92.38.173.0/24

请问在哪里修改呢？

**Comment by sola97** [comment]
> > 其实最主要的是UDP语音，vrchat是用的photon引擎，连接的域名是
> > gcsc001.exitgames.com
> > ...
> > gcsc007.exitgames.com
> > 这七个
> > 所以IP地址段需要加上
> > 92.38.173.0/24
> 
> 请问在哪里修改呢？

我觉得sstap这种黑名单机制太蛋疼了，我改用proxycap了

**Comment by GusRoth** [comment]
> > > 其实最主要的是UDP语音，vrchat是用的光子引擎，连接的
> > > 域名是gcsc001.exitgames.com 
> > > ... 
> > > gcsc007.exitgames.com 
> > > 这七个
> > > 所以IP地址段需要加上
> > > 92.38.173.0/24
> > 
> > 
> > 请问在哪里修改呢？
> 
> 我觉得sstap这种黑名单机制太蛋疼了，我改用proxycap了

哭了，我安装proxycap一直提示错误orz

**Comment by GusRoth** [comment]
> 已经支持，期待你的尝试。 👍

您好！youtube-dl的代理没有成功！挂上代理后，一切正常，但是youtube视频是无法加载的！使用sstap内置的全局代理的时候是可以的！能否更新一下vrchat的规则！

**Comment by NormanBB** [comment]
@GusRoth Netch. 请。
