### ISSUE TITLE
希望增加FIFA20和NBA2K20

### ISSUE THREAD

**Issue by owenzwen** [FQrabbit/SSTap-Rule#324]
**需要增加游戏\程序名字**
如``FIFA20和NBA2K20``

**该游戏\程序的运行环境**
如
``虚拟机``
``局域网其他设备``
``PC``

**该游戏\程序哪部分需要代理**
如
``整个游戏\程序都需要``
``只代理登陆部分``

**特殊情况**
如果还有特殊想说明的请在这里描述.

**Comment by RudeTheJack** [comment]
+1

**Comment by RudeTheJack** [comment]
2K20+1

**Comment by FQrabbit** [comment]
这游戏得多少钱🌚

**Comment by RudeTheJack** [comment]
> 这游戏得多少钱🌚

steam上有啊

**Comment by NormanBB** [comment]
#316

**Comment by 412572219** [comment]
**###### NBA2K20 ######**
3.112.0.0/16
3.226.109.0/24
13.32.35.0/24
13.32.60.0/24
13.32.196.0/24
13.33.43.0/24
13.33.197.0/24
13.33.210.0/24
13.35.18.0/24
13.35.38.0/24
13.35.45.0/24
13.35.93.0/24
13.35.160.0/24
13.112.0.0/16
13.124.0.0/16
13.124.213.0/24
13.125.0.0/16
13.125.27.0/24
13.209.0.0/16
13.210.0.0/16
13.224.35.0/24
13.224.150.0/24
13.224.167.0/24
13.224.190.0/24
13.224.249.0/24
13.225.102.0/24
13.225.149.0/24
13.225.163.0/24
13.225.176.0/24
13.230.0.0/16
13.236.0.0/16
13.249.150.0/24
13.249.167.0/24
15.164.0.0/16
18.179.0.0/16
18.182.0.0/16
23.20.0.0/16
34.206.98.0/24
34.208.0.0/16
35.160.0.0/16
35.185.192.0/24
46.51.224.0/24
52.4.157.0/24
52.10.0.0/16
52.12.0.0/16
52.21.195.0/24
52.24.0.0/16
52.28.0.0/16
52.32.0.0/16
52.36.0.0/16
52.40.0.0/16
52.58.0.0/16
52.62.0.0/16
52.68.0.0/16
52.78.0.0/16
52.79.0.0/16
52.84.0.0/16
52.92.0.0/16
52.94.6.0/24
52.94.198.64/32
52.94.198.79/32
52.94.248.80/32
52.94.248.95/32
52.94.248.176/32
52.94.248.191/32
52.95.111.0/24
52.95.192.0/24
52.95.243.0/24
52.95.252.0/24
52.95.255.48/32
52.95.255.63/32
52.192.0.0/16
52.194.0.0/16
52.196.0.0/16
52.200.0.0/16
52.219.56.0/24
52.219.60.0/24
52.222.202.0/24
52.222.235.0/24
54.64.0.0/16
54.68.0.0/16
54.80.0.0/16
54.88.251.0/24
54.92.0.0/16
54.95.0.0/16
54.148.0.0/16
54.150.0.0/16
54.153.128.0/24
54.168.0.0/16
54.178.0.0/16
54.180.0.0/16
54.182.0.0/16
54.192.108.0/24
54.199.0.0/16
54.202.0.0/16
54.218.0.0/16
54.230.15.0/24
54.230.151.0/24
54.238.0.0/16
54.239.0.192/32
54.239.0.207/32
54.239.116.0/24
54.239.120.0/24
54.248.0.0/16
54.250.0.0/16
54.254.0.0/16
99.82.166.0/24
99.84.57.0/24
99.84.206.0/24
99.84.238.0/24
99.86.146.0/24
99.86.196.0/24
103.4.8.0/24
103.10.124.0/24
104.198.0.0/16
104.255.107.0/24
107.20.0.0/16
119.9.82.0/24
143.204.81.0/24
155.133.245.0/24
175.41.192.0/24
176.32.64.0/24
176.34.0.0/16
176.34.32.0/24

**Comment by 412572219** [comment]
**###### FIFA20 ######**
1.65.174.0/24
3.0.0.0/4
3.85.58.0/24
3.227.29.0/24
5.144.106.0/24
13.112.0.0/16
13.211.52.0/24
13.211.232.0/24
13.230.0.0/16
13.233.50.0/24
15.206.0.0/16
18.162.0.0/16
18.179.223.0/24
18.196.167.0/24
18.197.48.0/24
18.206.67.0/24
34.194.95.0/24
34.194.115.0/24
34.198.174.0/24
34.200.59.0/24
34.201.40.0/24
34.207.155.0/24
34.207.188.0/24
34.207.237.0/24
34.241.205.0/24
34.246.50.0/24
34.251.96.0/24
34.253.14.0/24
35.154.91.0/24
35.157.160.0/24
35.158.22.0/24
35.158.41.0/24
35.158.80.0/24
35.171.196.0/24
35.180.144.0/24
43.239.136.0/24
52.2.16.0/24
52.4.0.0/16
52.7.196.0/24
52.16.167.0/24
52.18.194.0/24
52.19.111.0/24
52.22.164.0/24
52.23.167.0/24
52.23.176.0/24
52.47.70.0/24
52.50.142.0/24
52.67.114.0/24
52.74.103.0/24
52.86.28.0/24
52.91.115.0/24
52.205.181.0/24
52.206.219.0/24
52.206.228.0/24
52.207.23.0/24
52.207.215.0/24
52.208.122.0/24
52.209.218.0/24
52.210.224.0/24
52.211.109.0/24
52.212.104.0/24
52.220.199.0/24
52.229.171.0/24
54.76.46.0/24
54.86.6.0/24
54.86.16.0/24
54.87.90.0/24
54.87.208.0/24
54.87.235.0/24
54.88.186.0/24
54.89.179.0/24
54.91.106.0/24
54.144.31.0/24
54.144.52.0/24
54.145.236.0/24
54.145.243.0/24
54.146.146.0/24
54.162.34.0/24
54.163.47.0/24
54.163.61.0/24
54.164.21.0/24
54.164.51.0/24
54.165.216.0/24
54.172.166.0/24
54.172.209.0/24
54.173.129.0/24
54.173.153.0/24
54.174.105.0/24
54.174.186.0/24
54.174.212.0/24
54.175.150.0/24
54.175.190.0/24
54.189.201.0/24
54.190.223.0/24
54.204.140.0/24
54.208.82.0/24
54.209.90.0/24
54.210.13.0/24
54.221.8.0/24
54.224.25.0/24
54.225.181.0/24
54.232.212.0/24
54.242.43.0/24
54.242.215.0/24
54.248.82.0/24
57.7.200.0/24
60.70.102.0/24
65.158.114.0/24
85.195.103.0/24
89.159.239.0/24
95.138.141.0/24
103.194.165.0/24
108.128.238.0/24
109.200.212.0/24
109.200.215.0/24
109.200.221.0/24
109.200.222.0/24
111.91.228.0/24
114.226.106.0/24
115.192.90.0/24
116.121.43.0/24
119.28.142.0/24
119.28.187.0/24
121.131.173.0/24
123.113.90.0/24
124.168.36.0/24
125.81.175.0/24
134.213.201.0/24
145.255.21.0/24
146.0.231.0/24
150.109.67.0/24
150.109.79.0/24
159.153.28.0/24
159.153.36.0/24
159.153.42.0/24
159.153.59.0/24
159.153.62.0/24
159.153.64.0/24
159.153.75.0/24
159.153.126.0/24
159.153.166.0/24
159.153.190.0/24
159.153.191.0/24
159.153.224.0/24
159.153.234.0/24
159.153.244.0/24
159.163.28.0/24
169.38.89.0/24
169.38.100.0/24
169.57.53.0/24
169.57.68.0/24
169.57.76.0/24
173.248.243.0/24
175.37.203.0/24
180.150.147.0/24
185.50.104.0/24
185.179.200.0/24
185.179.203.0/24
188.234.7.0/24
203.135.190.0/24
203.195.120.0/24
203.195.121.0/24
203.195.122.0/24

**Comment by NormanBB** [comment]
@412572219 请发起pull request.

**Comment by RudeTheJack** [comment]
> **###### NBA2K20 ######**
> 3.112.0.0/16
> 3.226.109.0/24
> 13.32.35.0/24
> 13.32.60.0/24
> 13.32.196.0/24
> 13.33.43.0/24
> 13.33.197.0/24
> 13.33.210.0/24
> 13.35.18.0/24
> 13.35.38.0/24
> 13.35.45.0/24
> 13.35.93.0/24
> 13.35.160.0/24
> 13.112.0.0/16
> 13.124.0.0/16
> 13.124.213.0/24
> 13.125.0.0/16
> 13.125.27.0/24
> 13.209.0.0/16
> 13.210.0.0/16
> 13.224.35.0/24
> 13.224.150.0/24
> 13.224.167.0/24
> 13.224.190.0/24
> 13.224.249.0/24
> 13.225.102.0/24
> 13.225.149.0/24
> 13.225.163.0/24
> 13.225.176.0/24
> 13.230.0.0/16
> 13.236.0.0/16
> 13.249.150.0/24
> 13.249.167.0/24
> 15.164.0.0/16
> 18.179.0.0/16
> 18.182.0.0/16
> 23.20.0.0/16
> 34.206.98.0/24
> 34.208.0.0/16
> 35.160.0.0/16
> 35.185.192.0/24
> 46.51.224.0/24
> 52.4.157.0/24
> 52.10.0.0/16
> 52.12.0.0/16
> 52.21.195.0/24
> 52.24.0.0/16
> 52.28.0.0/16
> 52.32.0.0/16
> 52.36.0.0/16
> 52.40.0.0/16
> 52.58.0.0/16
> 52.62.0.0/16
> 52.68.0.0/16
> 52.78.0.0/16
> 52.79.0.0/16
> 52.84.0.0/16
> 52.92.0.0/16
> 52.94.6.0/24
> 52.94.198.64/32
> 52.94.198.79/32
> 52.94.248.80/32
> 52.94.248.95/32
> 52.94.248.176/32
> 52.94.248.191/32
> 52.95.111.0/24
> 52.95.192.0/24
> 52.95.243.0/24
> 52.95.252.0/24
> 52.95.255.48/32
> 52.95.255.63/32
> 52.192.0.0/16
> 52.194.0.0/16
> 52.196.0.0/16
> 52.200.0.0/16
> 52.219.56.0/24
> 52.219.60.0/24
> 52.222.202.0/24
> 52.222.235.0/24
> 54.64.0.0/16
> 54.68.0.0/16
> 54.80.0.0/16
> 54.88.251.0/24
> 54.92.0.0/16
> 54.95.0.0/16
> 54.148.0.0/16
> 54.150.0.0/16
> 54.153.128.0/24
> 54.168.0.0/16
> 54.178.0.0/16
> 54.180.0.0/16
> 54.182.0.0/16
> 54.192.108.0/24
> 54.199.0.0/16
> 54.202.0.0/16
> 54.218.0.0/16
> 54.230.15.0/24
> 54.230.151.0/24
> 54.238.0.0/16
> 54.239.0.192/32
> 54.239.0.207/32
> 54.239.116.0/24
> 54.239.120.0/24
> 54.248.0.0/16
> 54.250.0.0/16
> 54.254.0.0/16
> 99.82.166.0/24
> 99.84.57.0/24
> 99.84.206.0/24
> 99.84.238.0/24
> 99.86.146.0/24
> 99.86.196.0/24
> 103.4.8.0/24
> 103.10.124.0/24
> 104.198.0.0/16
> 104.255.107.0/24
> 107.20.0.0/16
> 119.9.82.0/24
> 143.204.81.0/24
> 155.133.245.0/24
> 175.41.192.0/24
> 176.32.64.0/24
> 176.34.0.0/16
> 176.34.32.0/24

怎么制作呢

**Comment by NormanBB** [comment]
规则已更新且已存在于项目中。
