### ISSUE TITLE
请求添加YY语音规则的详细教学，看了 #285 还是不懂

### ISSUE THREAD

**Issue by holiday0917** [FQrabbit/SSTap-Rule#326]

**Comment by NormanBB** [comment]
需要详细操作有点困难。

请说明你目前的情况。回国节点可用？直连？使用什么规则？

**Comment by holiday0917** [comment]
在用SSR的回国节点。偶尔翻墙回国内看视频什么的。SStap除了yy使用节点（翻墙回国），其他都要直连（使用外国IP）。

**Comment by NormanBB** [comment]
#316

该项目有发布Windows下的可执行程序，readme有详细操作方法。后续可回到本issue页面更新动态。

**Comment by holiday0917** [comment]
感谢，按照上面方法已解决。
