### ISSUE TITLE
请求更新彩虹六号规则

### ISSUE THREAD

**Issue by MasterOfStar** [FQrabbit/SSTap-Rule#328]
**问题描述**
彩虹六号规则亟需更新
游戏新增了一些IP，这是目前规则没有的。
我个人并不能够抓到全部IP（**可能不同线路IP不同，我更换两个不同节点之后所连接的IP变得不同了 如原先连接3.221.0.0/16段，更换节点后连接到3.222.0.0/16段**）
目前已经确定新增了以下规则：
3.207.0.0/16
3.208.0.0/16
3.215.0.0/16
3.217.0.0/16
3.221.0.0/16
3.222.0.0/16
35.241.0.0/16
23.63.0.0/16
34.206.0.0/16
65.158.122.0/24
77.67.85.0/24
**请大家帮忙再查查还有那些疏漏没有**

**从哪里开始出现这个问题**
游戏更新之后上不去
进入游戏直接提示“无法连接到服务器”

**截图**
如果可以，请添加截图以帮助解释您的问题.

**运行环境**
Win10X64 1903
浙江电信
节点：香港Azure
           香港阿里云

**Comment by NormanBB** [comment]
彩虹六号国际服？

**Comment by MasterOfStar** [comment]
> 彩虹六号国际服？

EAS港服

**Comment by MasterOfStar** [comment]
![image](https://user-images.githubusercontent.com/21274896/67092662-68859a80-f1e2-11e9-89da-9b728a3032d4.png)
更新：发现新的IP段
34.237.0.0/16

**Comment by NormanBB** [comment]
你仅通过获取到的一个ip就写上了/16的网段？

**Comment by MasterOfStar** [comment]
毕竟我只是业余的进行抓取，没法确定育碧到底用了这个段哪些IP
就比如一开始3.215.0.0/16这个段我以为只用了一个C段，但是后来在其他网络环境下发现又连不上去，切出去发现又出现了一个C段。我没有那么多的时间去抓去更多的IP，而且万一不写全到时候某些人肯定又会问：为什么上不去。
所以我索性直接把/16写上去了
毕竟用这个具体规则的人肯定只是加速这个游戏。

**Comment by NormanBB** [comment]
[Rainbow-Six-asia.zip](https://github.com/FQrabbit/SSTap-Rule/files/3744547/Rainbow-Six-asia.zip)

提取自某加速器，试一下。

我对网段的扩大持保留意见。

**Comment by MasterOfStar** [comment]
@NormanBB 这份规则实际上也不全，3.2xx段就不全
对于扩大网段这件事也算是无奈之举
毕竟如果游戏里（尤其是排位） 突然换了个不在列表里的IP进行连接（发生过这事），然后掉线了。。。
掉分掉的就很爽了
只能说主要算是为了稳吧

**Comment by NormanBB** [comment]
一个月过去了，有继续更新吗？

**Comment by NormanBB** [comment]
> [Rainbow-Six-asia.zip](https://github.com/FQrabbit/SSTap-Rule/files/3744547/Rainbow-Six-asia.zip)
> 
> 提取自某加速器，试一下。
> 
> 我对网段的扩大持保留意见。

@juszhc  用下这个规则。

**Comment by sky-wdl** [comment]
我也请求

**Comment by ddrangers** [comment]
谢谢分享！解决了我的问题！

**Comment by ifconfig2333** [comment]
> 
> 
> > [Rainbow-Six-asia.zip](https://github.com/FQrabbit/SSTap-Rule/files/3744547/Rainbow-Six-asia.zip)
> > 提取自某加速器，试一下。
> > 我对网段的扩大持保留意见。
> 
> @juszhc 用下这个规则。

好像不行？连接失败
