### ISSUE TITLE
rule 规则头请教

### ISSUE THREAD

**Issue by jesonxie** [FQrabbit/SSTap-Rule#332]
关于SSTAP规则头，每个参数以逗号分隔例如
`#CSGO,反恐精英:全球攻势,0,0,1,0,1,0,By-AmazingDM`

参数说明：
  * \# (规则头开始，1.0.9.7版本用 # , 1.1.0.0 用 = )
  * CSGO(规则英文名)
  * 反恐精英:全球攻势(规则中文名)
  * 0(动作类型 0.代理 1.直连)
  * 0(和上一条相同 动作类型 0.代理 1.直连)
  * 1(未知)
  * 0(未知)
  * 1(是否可读写 0.可读写 1.只可读)
  * 0(DNS代理类型 0.自动 1.直连 2.代理)
  * By-AmazingDM(备注)

这里有个猜测：
如果 sstap 规则头是 直连，则在规则中的 ip 都是直连，不在其中的都走代理；
如果 sstap 规则头是 代理，则在规则中的 ip 都是代理，不在其中的都是直连；

找了很多博客，都没有相关说明，有大佬指点下么

**Comment by NormanBB** [comment]
Good question.
不过最好的解决方法还是自己尝试。

10开头为sstap网卡，192为本地适配器ip

更改rules头后
![批注 2019-10-24 151509](https://user-images.githubusercontent.com/18748504/67462179-a0249480-f671-11e9-8a3f-1df532aa2566.jpg)

sstap建立了全局连接，优先级更高，但rules里面的ip直连，相当于白名单。
