### ISSUE TITLE
请问可以分享下网站上面的routeToRules工具源码嘛？

### ISSUE THREAD

**Issue by Jiufox** [FQrabbit/SSTap-Rule#333]
**问题描述**
本案例里面有一个关键步骤，就是需要去网站：
[https://www.ssrtool.com/tool/routeToRules]
(https://www.ssrtool.com/tool/routeToRules)
然后把提取的路由表信息，放入网站
才能转化成需要的sstap规则格式

求大佬，可否把这个网页的源码分享给我？
不胜感谢！foxix@qq.com

**截图**
http://i1.fuimg.com/594903/82b8c845bec82a91.jpg

**运行环境**
PC: win10
服务器：CentOS7

**Comment by NormanBB** [comment]
这个问题你得问 @AmazingDM ，不过他也没那么快回复。

关于这个工具，我个人是这么分析的。工具发布在ssrtool的网站，am似乎是管理者。同时网站自身有相关的论坛与telegram群组，你可以自己去那问问。

再者，通过分析网页代码可发现请求的网址与方法。

![批注 2019-10-25 205433](https://user-images.githubusercontent.com/18748504/67572993-e9580f80-f769-11e9-821a-c445f5af04bb.jpg)


尽管api不一定向外公开，但你可以自己写工具请求返回数据。如果可以做到的话可以向项目提交pull request。**:)**
