### ISSUE TITLE
请求增加谷歌云盘客户端"备份与同步"的规则

### ISSUE THREAD

**Issue by Pudge1996** [FQrabbit/SSTap-Rule#335]
**需要增加游戏\程序名字**
``备份与同步``

**该游戏\程序的运行环境**
如
``PC``

**该游戏\程序哪部分需要代理**
如
``整个程序都需要``

**特殊情况**
现在挂 SSR 开 PAC 模式无法正常备份文件, 必须挂全局才可以, 但是挂全局了访问国内网站很不方便.

所以想请教下有没有办法加一个规则,可以开 PAC 的 SSR, 同时开带有云盘规则的 SSTAP, 做到正常浏览国内网站的同时, 谷歌云盘也能连接到.

谢谢!~

**Comment by NormanBB** [comment]
你可以试试sstap的绕过大陆和局域网模式。

对于google drive的ip抓取，参阅 #316

**Comment by Jhin3433** [comment]
请问你解决这个问题了吗
