### ISSUE TITLE
请求增加荒野大镖客2

### ISSUE THREAD

**Issue by uniqueliuzhen** [FQrabbit/SSTap-Rule#339]
**需要增加游戏\程序名字**
如``荒野大镖客2pc``

**该游戏\程序的运行环境**

``PC``

**该游戏\程序哪部分需要代理**

``整个游戏`
`

**特殊情况**
如果还有特殊想说明的请在这里描述.

**Comment by uniqueliuzhen** [comment]
请求增加新规则

**Comment by NormanBB** [comment]
#316 

刚出的游戏还是自己先做个吧

**Comment by uniqueliuzhen** [comment]
能给我分享一下你的吗，我不会做这个

**Comment by NormanBB** [comment]
https://github.com/FQrabbit/SSTap-Rule/blob/fe91a63edec45b9be6241e859290375376f4b4fb/rules/Red-dead-redemption2.rules
