### ISSUE TITLE
求roblox代理规则

### ISSUE THREAD

**Issue by 2729414614** [FQrabbit/SSTap-Rule#341]
**Roblox**

**该游戏\程序的运行环境**
``PC``

**该游戏\程序哪部分需要代理**
``整个游戏\程序都需要``

**Comment by 412572219** [comment]
8.42.96.0/24
23.57.113.0/24
23.106.120.0/24
23.106.121.0/24
23.106.122.0/24
23.106.123.0/24
23.106.124.0/24
23.106.125.0/24
35.186.208.0/24
43.249.37.0/24
52.216.0.0/16
62.212.82.0/24
64.120.112.0/24
64.120.113.0/24
64.120.114.0/24
64.120.115.0/24
64.120.116.0/24
64.120.117.0/24
66.115.169.0/24
66.165.237.0/24
66.165.238.0/24
66.165.239.0/24
66.165.240.0/24
66.165.241.0/24
66.165.244.0/24
66.165.245.0/24
66.165.246.0/24
66.165.248.0/24
78.159.97.0/24
78.159.98.0/24
95.168.180.0/24
95.168.183.0/24
95.168.188.0/24
95.168.189.0/24
95.211.86.0/24
103.101.129.0/24
103.101.130.0/24
104.206.0.0/16
104.206.1.0/24
104.206.2.0/24
104.206.228.0/24
104.206.229.0/24
104.206.230.0/24
107.158.144.0/24
107.158.145.0/24
107.158.146.0/24
107.181.164.0/24
107.181.173.0/24
128.116.0.0/16
128.116.1.0/24
128.116.2.0/24
128.116.3.0/24
128.116.4.0/24
128.116.5.0/24
128.116.6.0/24
128.116.7.0/24
128.116.8.0/24
128.116.9.0/24
128.116.13.0/24
128.116.14.0/24
128.116.15.0/24
128.116.16.0/24
128.116.17.0/24
128.116.18.0/24
128.116.19.0/24
128.116.20.0/24
128.116.23.0/24
128.116.24.0/24
128.116.25.0/24
128.116.26.0/24
128.116.27.0/24
128.116.28.0/24
128.116.29.0/24
128.116.30.0/24
128.116.31.0/24
128.116.32.0/24
128.116.33.0/24
128.116.34.0/24
128.116.39.0/24
128.116.40.0/24
128.116.41.0/24
128.116.42.0/24
128.116.43.0/24
172.83.42.0/24
172.83.43.0/24
172.83.44.0/24
172.83.45.0/24
172.83.46.0/24
172.83.47.0/24
172.98.70.0/24
172.98.75.0/24
172.98.90.0/24
172.98.93.0/24
172.98.95.0/24
180.222.100.0/24
185.254.70.0/24
185.254.71.0/24
192.111.128.0/24
198.8.89.0/24
198.8.95.0/24
199.36.222.0/24
199.116.116.0/24
199.229.251.0/24
205.185.216.0/24
209.58.170.0/24
209.58.184.0/24
209.58.185.0/24
209.206.42.0/24
209.206.43.0/24
209.206.44.0/24
209.206.45.0/24
209.206.46.0/24
209.206.47.0/24
