### ISSUE TITLE
绝地求生可以加速游戏登陆连接，但是匹配无法进入游戏

### ISSUE THREAD

**Issue by bluexzh** [FQrabbit/SSTap-Rule#344]
**问题描述**
绝地求生可以加速游戏登陆连接，但是匹配无法进入游戏

**从哪里开始出现这个问题**
例如
``某游戏的登陆页面``、
``内置的网页``、
``游戏房间内部``、
``商店页面`` 等

**截图**
如果可以，请添加截图以帮助解释您的问题.

**运行环境**
请说明当前的运行环境
例如：
``操作系统``
``网络环境``(如 运营商等

**Comment by NormanBB** [comment]
@bluexzh @johnny-feng 

[PUBG-Asia&-Southeast-Asia.zip](https://github.com/FQrabbit/SSTap-Rule/files/3853838/PUBG-Asia.-Southeast-Asia.zip)
 
请帮忙测试。
