### ISSUE TITLE
YY语音

### ISSUE THREAD

**Issue by helpmsg** [FQrabbit/SSTap-Rule#347]
**需要增加游戏\程序名字**
程序名字：YY语音

**该游戏\程序的运行环境**
``PC``

**该游戏\程序哪部分需要代理**
``只代理房间的聊天部分``

**特殊情况**
现在YY语音限制的太厉害了，在新疆或者个别地区 都使用不了。
海外玩家想使用YY与国内玩家互动 必须开代理，要不然使用不了。
奈何玩游戏的大多玩家都使用YY语音

**Comment by helpmsg** [comment]
登陆进程 好像是 YY.exe
房间的 进程yyexternal.exe
我使用ip_crawl_tool.v3.0 找了一些IP

[YY.zip](https://github.com/FQrabbit/SSTap-Rule/files/3882243/YY.zip)
但是 偶尔 还是使用不了， 应该是IP 没有找全！ 所以来这里请求帮助了

**Comment by helpmsg** [comment]
使用SSTAP 的全局 可以解决..
但是我在海外,玩国内的 游戏也使用全局 会很不稳定.,
所以想单独代理YY语音

**Comment by oooldtoy** [comment]
@helpmsg 可以试试使用netch呢

**Comment by helpmsg** [comment]
> @helpmsg 可以试试使用netch呢

那个软件不太好用啊...还不如kkcap 呢,
但是 sstap 用的最舒服啊!!

**Comment by helpmsg** [comment]
@oooldtoy  那个软件好像有问题... 也可能是我机器的问题..
 话说.  kkcap 也不错啊..
 但是sstap 用的最舒服 顺手啊...
 所以... 能不能 搞出这个YY的规则呢

**Comment by NormanBB** [comment]
@helpmsg 你可以用久一些来收集更多的IP。但如果yy的机制是在用户间进行数据交换，而不仅仅在服务器与用户间进行交换的话，基于ip的加速方式也许比较困难。欢迎继续研究并交流意见，或向项目上传规则。

也许可以尝试使用仅代理国内的规则。

**Comment by helpmsg** [comment]
目前 又收集了一些IP。
我机器上可以用
[YY.zip](https://github.com/FQrabbit/SSTap-Rule/files/3883415/YY.zip)

**Comment by helpmsg** [comment]
@oooldtoy  顺便问一下..
https://github.com/oooldtoy/SSTAP_ip_crawl_tool.git
里面的http://23.101.14.221:5001 为什么不能收集YY的规则呢?? 是需要你那边后台指定吗?
如果是的, 添加一下呗
