### ISSUE TITLE
启用代理后访问国内网站显示国外ip的相关问题

### ISSUE THREAD

**Issue by NormanBB** [FQrabbit/SSTap-Rule#355]
**问题描述**

请说明你使用的是哪一个规则？

在何种情况下会出现显示国外ip的问题？

**截图**

如果可以，请添加截图以帮助解释您的问题.

**网络环境**

在使用哪一个运营商？

**补充说明**

写上你认为重要的补充说明。

**Comment by NormanBB** [comment]
解决方案

1. [手动指定DNS教程](https://cloud.tencent.com/developer/news/18326)。将DNS修改为以下图片中的[Googlehost项目](https://github.com/googlehosts/hosts/wiki/%E5%AE%9E%E9%AA%8C%E5%AE%A4#shadowsocks)提供的防污染DNS。


![批注 2019-12-07 214724](https://user-images.githubusercontent.com/18748504/70375664-5bac3a00-193b-11ea-9a45-dbc2ab9f4653.jpg)

> 关于DNS在日常生活中的使用经验，如果有人需要我可以分享相关教程。

**Comment by NormanBB** [comment]
@catterdx

**Comment by tomking007** [comment]
你好。我按步骤来，可以看到游戏文件加入，问题是连接时需要输入一个代理，代理的地址怎么填啊？

**Comment by NormanBB** [comment]
@tomking007 这种问题请百度sstap用法
