### ISSUE TITLE
请大佬添加一下pubglite日服规则

### ISSUE THREAD

**Issue by laolaroubbc** [FQrabbit/SSTap-Rule#357]
**需要增加游戏\程序名字**
如``pubglite日服``

**该游戏\程序的运行环境**
如
``PC``

**该游戏\程序哪部分需要代理**
如
``整个游戏\程序都需要``

**特殊情况**
如果还有特殊想说明的请在这里描述.

**Comment by NormanBB** [comment]
#316  

请使用自助工具来帮助我们编写规则，请详细写明游戏细节，如哪个服，哪个版本。
