### ISSUE TITLE
原有彩六规则失效

### ISSUE THREAD

**Issue by juszhc** [FQrabbit/SSTap-Rule#362]
**需要增加游戏\程序名字**
彩虹六号亚服

使用三种方式均未成功获取到游戏地址

目标加速器为 golink 

**该游戏\程序的运行环境**

``PC`` win10 1909 

**该游戏\程序哪部分需要代理**

``整个游戏\程序都需要``

**特殊情况**
如果还有特殊想说明的请在这里描述.

**Comment by NormanBB** [comment]
裸连情况下用工具能抓取到ip吗？

**Comment by juszhc** [comment]
> 裸连情况下用工具能抓取到ip吗？
先谢谢你发的那个规则 我这边服务器延迟有点高 开始用加速器了
裸连的话 应该可以 但是我没有抓到
