### ISSUE TITLE
请求增加“士官长合集（steam版）”、

### ISSUE THREAD

**Issue by Sonic8694** [FQrabbit/SSTap-Rule#363]
**需要增加游戏\程序名字**
如``CS-GO``

请使用[自动抓IP工具](https://github.com/oooldtoy/SSTAP_ip_crawl_tool)来帮助我们编写规则，请详细写明游戏细节，如哪个服，哪个版本。

**该游戏\程序的运行环境**
如
``虚拟机``
``局域网其他设备``
``PC``

**该游戏\程序哪部分需要代理**
如
``整个游戏\程序都需要``
``只代理登陆部分``

**特殊情况**
如果还有特殊想说明的请在这里描述.

**Comment by NormanBB** [comment]
请使用自动抓IP工具来帮助我们编写规则，请详细写明游戏细节，如哪个服，哪个版本。

**Comment by ClarkeCheng** [comment]
UU加速器提取的，未测试过
```
13.64.0.0/16
13.64.199.0/24
13.65.213.0/24
13.67.45.0/24
13.89.220.0/24
13.93.215.0/24
18.162.105.0/24
20.36.218.0/24
20.36.246.0/24
20.40.120.0/24
20.40.160.0/24
20.40.176.0/24
20.40.182.0/24
20.43.96.0/24
20.43.128.0/24
20.184.0.0/16
20.188.128.0/24
20.189.64.0/24
20.193.0.0/16
23.32.241.73/32
23.32.241.75/32
23.32.241.83/32
23.76.84.125/32
23.77.27.52/32
23.96.34.128/32
23.97.97.0/24
23.100.98.0/24
23.101.224.0/24
23.199.76.10/32
23.219.212.11/32
34.249.9.0/24
34.255.142.0/24
35.161.244.179/32
35.163.236.222/32
40.65.128.0/24
40.67.188.0/24
40.74.72.0/24
40.76.58.0/24
40.81.16.0/24
40.81.48.0/24
40.82.192.0/24
40.82.216.0/24
40.82.255.0/24
40.83.128.0/24
40.90.10.0/24
40.90.216.0/24
40.90.217.0/24
40.90.222.0/24
40.91.72.0/24
40.91.88.0/24
40.91.91.0/24
40.113.99.0/24
40.117.224.0/24
40.119.192.0/24
40.121.129.0/24
43.228.183.0/24
44.228.138.155/32
51.136.18.0/24
52.31.15.0/24
52.35.214.0/24
52.38.231.0/24
52.139.128.0/24
52.139.192.0/24
52.156.32.0/24
52.162.214.0/24
52.167.1.0/24
52.175.55.0/24
52.184.0.0/16
52.184.151.0/24
52.187.224.0/24
52.213.93.0/24
52.229.128.0/24
52.230.0.0/16
52.230.56.0/24
52.253.80.0/24
52.253.81.0/24
54.229.129.0/24
61.92.203.0/24
65.55.44.0/24
94.245.110.0/24
104.42.1.0/24
104.42.219.0/24
104.43.216.0/24
104.46.50.0/24
104.74.20.0/24
104.93.0.10/32
104.209.80.0/24
104.209.137.9/32
104.209.138.0/24
104.215.180.0/24
111.221.29.0/24
121.211.169.0/24
124.171.7.0/24
125.161.189.0/24
134.170.179.0/24
137.116.68.0/24
137.135.0.0/16
138.91.64.0/24
138.91.122.0/24
152.199.39.0/24
162.14.17.17/32
168.62.0.0/16
168.62.55.0/24
168.63.232.0/24
180.150.82.0/24
184.87.133.2/32
193.115.127.0/24
203.40.171.0/24
204.79.197.0/24
219.135.99.68/32
219.135.99.70/32
219.135.99.74/32
```

**Comment by FQrabbit** [comment]
> UU加速器提取的，未测试过
> 
> ```
> 13.64.0.0/16
> 13.64.199.0/24
> 13.65.213.0/24
> 13.67.45.0/24
> 13.89.220.0/24
> 13.93.215.0/24
> 18.162.105.0/24
> 20.36.218.0/24
> 20.36.246.0/24
> 20.40.120.0/24
> 20.40.160.0/24
> 20.40.176.0/24
> 20.40.182.0/24
> 20.43.96.0/24
> 20.43.128.0/24
> 20.184.0.0/16
> 20.188.128.0/24
> 20.189.64.0/24
> 20.193.0.0/16
> 23.97.97.0/24
> 23.100.98.0/24
> 23.101.224.0/24
> 34.249.9.0/24
> 34.255.142.0/24
> 40.65.128.0/24
> 40.67.188.0/24
> 40.74.72.0/24
> 40.76.58.0/24
> 40.81.16.0/24
> 40.81.48.0/24
> 40.82.192.0/24
> 40.82.216.0/24
> 40.83.128.0/24
> 40.90.10.0/24
> 40.90.216.0/24
> 40.90.217.0/24
> 40.90.222.0/24
> 40.91.72.0/24
> 40.91.88.0/24
> 40.91.91.0/24
> 40.113.99.0/24
> 40.117.224.0/24
> 40.119.192.0/24
> 40.121.129.0/24
> 43.228.183.0/24
> 51.136.18.0/24
> 52.31.15.0/24
> 52.35.214.0/24
> 52.38.231.0/24
> 52.139.128.0/24
> 52.139.192.0/24
> 52.156.32.0/24
> 52.162.214.0/24
> 52.167.1.0/24
> 52.175.55.0/24
> 52.184.0.0/16
> 52.184.151.0/24
> 52.187.224.0/24
> 52.213.93.0/24
> 52.229.128.0/24
> 52.230.0.0/16
> 52.230.56.0/24
> 52.253.80.0/24
> 52.253.81.0/24
> 54.229.129.0/24
> 61.92.203.0/24
> 65.55.44.0/24
> 94.245.110.0/24
> 104.42.1.0/24
> 104.42.219.0/24
> 104.43.216.0/24
> 104.46.50.0/24
> 104.74.20.0/24
> 104.209.80.0/24
> 104.209.138.0/24
> 104.215.180.0/24
> 111.221.29.0/24
> 121.211.169.0/24
> 124.171.7.0/24
> 125.161.189.0/24
> 134.170.179.0/24
> 137.116.68.0/24
> 137.135.0.0/16
> 138.91.64.0/24
> 138.91.122.0/24
> 152.199.39.0/24
> 162.14.17.17/32
> 168.62.0.0/16
> 168.62.55.0/24
> 168.63.232.0/24
> 180.150.82.0/24
> 193.115.127.0/24
> 203.40.171.0/24
> 204.79.197.0/24
> 219.135.99.68/32
> 219.135.99.70/32
> 219.135.99.74/32
> ```

@ClarkeCheng  里面含有好几个中国ip是否考虑剔除让它直连呢?🤔

**Comment by ClarkeCheng** [comment]
@FQrabbit 这，我不了解这个游戏，我也不清楚有无剔除的必要
