### ISSUE TITLE
我想问问,emmm...你们用这款程序的时候会不会突然给你放歌?

### ISSUE THREAD

**Issue by BelieveQvQ** [FQrabbit/SSTap-Rule#366]
![SStap](https://user-images.githubusercontent.com/24773068/71917274-a5967300-31ba-11ea-8a5c-2628a08de428.jpg)
就... 很恐怖 大半夜的 现在凌晨两点 突然就放了首比较诡异的歌? 并且我现在好像还找不到关闭他的方法...

**Comment by FQrabbit** [comment]
@BelieveQvQ 图片下面有个按钮，点一下单独静音该程序.

**Comment by wolp6635236** [comment]
哈哈哈，我昨天晚上也遇到了，戴上耳机差点被吓死

**Comment by Raki-start** [comment]
原版内嵌广告没禁音频

**Comment by JusufUs** [comment]
我也有，没事让你听听小音乐。哈哈。。这广告真恶心啊，管理员能否让音乐关了？？？

**Comment by NormanBB** [comment]
@JusufUs 请到release页面下载去广告版
