### ISSUE TITLE
彩虹六號東亞貌似代理了全局

### ISSUE THREAD

**Issue by isewkai** [FQrabbit/SSTap-Rule#37]
![qq 20180828224653](https://user-images.githubusercontent.com/42776542/44730852-7840ac00-ab14-11e8-9a4e-3eff152633d1.png)
可以看到開了代理后網頁流量也代理了
煩請更新下rule

**Comment by FQrabbit** [comment]
@isewkai 请问你的欧朋浏览器是不是打开了流量压缩🤔？
