### ISSUE TITLE
如果可以.请更新下怪物猎人冰原的规则

### ISSUE THREAD

**Issue by just2ciao** [FQrabbit/SSTap-Rule#377]
如果可以.请更新下怪物猎人世界冰原的规则,
冰原更新后原规则失效.
谢谢了

**Comment by just2ciao** [comment]
自动抓IP工具我试过.只创建了一个带名称的文件.记事本打开后里面没有任何IP地址.
这次冰原DLC更新增加了新的反作弊系统,哪怕是MOD也要先用上反作弊插件才能加载.所以可能是抓IP工具无法抓取地址的原因

**Comment by oooldtoy** [comment]
@just2ciao 在抓取ip的时候，工具界面会显示出抓取到的ip，如果没有显示，文件就只有一个文件头

**Comment by just2ciao** [comment]
> @just2ciao 在抓取ip的时候，工具界面会显示出抓取到的ip，如果没有显示，文件就只有一个文件头

没错了.运行游戏期间完全没有显示任何IP. 用的SSTAP是1.0.9.7
抓取不了好蛋疼

**Comment by NormanBB** [comment]
@just2ciao 这个插件是运行的程序吗？如果是，可尝试加上它的程序名称

**Comment by just2ciao** [comment]
> @just2ciao 这个插件是运行的程序吗？如果是，可尝试加上它的程序名称

不是程序.是DLL文件.

**Comment by FQrabbit** [comment]
ummm,这游戏貌似除了开头会访问官网获取活动信息，进游戏之后的链接如果联机全是走UDP(貌似还是贴着steam主程序走的udp)，我自己打开了一段时间，进入别的玩家领域抓包出来的udp全是对方的家宽ip,联机体验卡的话，如果确定好友都是国内，建议还是挂国内的加速器会比较合适，如果你说加载活动信息卡慢的话，貌似只要代理TCP就阔以了
52.48.0.0/14
~~当然，以上测试时间还没20分钟，可能不准确.我也不懂你们说的反作弊程序是什么鬼东西~~
