### ISSUE TITLE
新增规则Everquest北美

### ISSUE THREAD

**Issue by simons02222** [FQrabbit/SSTap-Rule#380]
需要增加游戏\程序名字
Everquest\eqgame.exe

请使用自动抓IP工具来帮助我们编写规则，请详细写明游戏细节，如哪个服，哪个版本。
eqgame.exe 北美,运营商:daybreaker
64.37.171.73

该游戏\程序的运行环境
PC

该游戏\程序哪部分需要代理
整个游戏\程序都需要

特殊情况
no

**Comment by simons02222** [comment]
用ip_crawl_tool3.3 试了下 仍只抓取到一个ip地址 64.37.171.73

**Comment by oooldtoy** [comment]
@simons02222 是否使用管理员身份运行，是否开启抓取udp模式。然后查看防火墙日志是否开启

**Comment by simons02222** [comment]
防火墙日志开启? 防火墙是开启or关闭?

**Comment by oooldtoy** [comment]
@simons02222 防火墙日志，如果使用管理员身份运行，且同意抓取udp，就会默认开启防火墙日志

**Comment by oooldtoy** [comment]
@simons02222 好像确实有点问题，我再改一下
