### ISSUE TITLE
模式“不代理中国IP”还是会走代理

### ISSUE THREAD

**Issue by DarknessLucius** [FQrabbit/SSTap-Rule#381]
**问题描述**
模式选“不代理中国IP且绕过局域网精简版”（完整版会卡很长时间而且连上后像断网一样啥都看不了），看B站或者网易云音乐之类的国内应用，还是会走代理，太耗流量了。用内置的网页模式就正常。
但我平常会边玩warframe边看b站，只用网页模式的话，warframe就代理不了，聊天频道经常卡住，但是网页模式又添加不了规则。。求大佬指点，痛苦orz

**运行环境**
操作系统:win10 1909
网络环境:广东电信

**Comment by FQrabbit** [comment]
这个问题，应该是DNS解析到了国内视频网站的国际CDN，所以误认为IP是国外，所以流量都跑代理了.
解决方法的话，使用国内的无污染DNS解析.
