### ISSUE TITLE
请求添加 战争前线俄服规则

### ISSUE THREAD

**Issue by a1751874251** [FQrabbit/SSTap-Rule#383]

**Comment by FQrabbit** [comment]
真的很抱歉，我没有玩过这个游戏，如果你自己动手能力强的话，可以参考一下这个 #316 ，手动获取游戏的服务器地址. 如有使用上的问题，可以在群里一起讨论 [![加入 Telegram 群组](https://img.shields.io/badge/%E5%8A%A0%E5%85%A5-Telegram_%E7%BE%A4%E7%BB%84-brightgreen.svg)](https://t.me/SSTapRule)

**Comment by a1751874251** [comment]
> 真的很抱歉，我没有玩过这个游戏，如果你自己动手能力强的话，可以参考一下这个#316，手动获取游戏的服务器地址.如有使用上的问题，可以在群里一起讨论[![加入Telegram 群组](https://camo.githubusercontent.com/1356f7f95c69c5e3bab7f69ef6e77d01dfb36de6/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f2545352538412541302545352538352541352d54656c656772616d5f2545372542452541342545372542422538342d627269676874677265656e2e737667)](https://t.me/SSTapRule)
这怎么用,有教程?

**Comment by a1751874251** [comment]
@FQrabbit 看了使用方法,是不是获取游戏ip.那用游戏加加来获取ip也可以?

**Comment by NormanBB** [comment]
@a1751874251 详细方法参见项目wiki。
