### ISSUE TITLE
请求更新PES2020服务器规则

### ISSUE THREAD

**Issue by wyLeon** [FQrabbit/SSTap-Rule#385]
**需要增加游戏\程序名字**
``PES2020``

游戏不分服

**该游戏\程序的运行环境**
``PC``

**该游戏\程序哪部分需要代理**
``整个游戏\程序都需要``

**Comment by FQrabbit** [comment]
真的很抱歉，我没有购买这个游戏，如果你自己动手能力强的话，可以参考一下这个 #316 ，手动获取游戏的服务器地址.

**Comment by wyLeon** [comment]
> 真的很抱歉，我没有购买这个游戏，如果你自己动手能力强的话，可以参考一下这个 #316 ，手动获取游戏的服务器地址.

好的 非常感谢！

**Comment by FQrabbit** [comment]
@wyLeon 不客气，期待你也能为项目提交ip
