### ISSUE TITLE
罗博造造RobocraftClient

### ISSUE THREAD

**Issue by xsgteamx** [FQrabbit/SSTap-Rule#386]
**需要增加游戏\程序名字**
如``CS-GO``

全球服

PC

整个游戏都需要代理

**特殊情况**
可能服务器在欧洲(德国或者法国)

**Comment by NormanBB** [comment]
@xsgteamx 个人认为，就算可以加速，加速效果也不一定好。

**Comment by xsgteamx** [comment]
因为是欧洲的缘故吗？

NormanBB <notifications@github.com> 于2020年2月29日周六 下午6:21写道：

**Comment by NormanBB** [comment]
@xsgteamx 是的
