### ISSUE TITLE
请求新增DJMAX Respect V

### ISSUE THREAD

**Issue by wearshoes** [FQrabbit/SSTap-Rule#388]
**需要增加游戏\程序名字**
DJMAX Respect V

**该游戏\程序的运行环境**
PC

**该游戏\程序哪部分需要代理**
整个游戏\程序都需要

**特殊情况**
我自己尝试过用SSTAP_ip_crawl_tool抓取规则并且成功生成了规则文件 但是放入sstap中进行游戏并不奏效 只能请大佬帮帮忙了

**Comment by NormanBB** [comment]
13.249.43.0/24
13.224.253.0/24
15.255.255.0/24
35.241.26.0/24
35.241.13.0/24
35.241.52.0/24
35.190.78.0/24
45.253.64.0/24
52.78.133.0/24
52.196.73.0/24
52.68.115.0/24
58.251.121.0/24
58.60.10.0/24
103.10.124.0/24
111.30.138.0/24
113.96.12.0/24
117.185.116.0/24
119.29.29.0/24
119.28.28.0/24
120.131.11.0/24
120.232.18.0/24
120.131.14.0/24
153.254.86.0/24
155.133.245.0/24
155.133.254.0/24
162.254.195.0/24
162.254.193.0/24
172.217.24.0/24
172.217.11.0/24
172.217.25.0/24
172.217.161.0/24
180.101.192.0/24
183.192.196.0/24
199.7.83.0/24
203.80.149.0/24
203.208.41.0/24
205.196.6.0/24
216.58.200.0/24
216.239.34.0/24
216.58.197.0/24
216.239.36.0/24
216.58.199.0/24
219.76.10.0/24

我手动编辑了下你的规则，把与dns有关的行去掉了，看下这样有用吗

**Comment by wearshoes** [comment]
> 13.249.43.0/24
> 13.224.253.0/24
> 15.255.255.0/24
> 35.241.26.0/24
> 35.241.13.0/24
> 35.241.52.0/24
> 35.190.78.0/24
> 45.253.64.0/24
> 52.78.133.0/24
> 52.196.73.0/24
> 52.68.115.0/24
> 58.251.121.0/24
> 58.60.10.0/24
> 103.10.124.0/24
> 111.30.138.0/24
> 113.96.12.0/24
> 117.185.116.0/24
> 119.29.29.0/24
> 119.28.28.0/24
> 120.131.11.0/24
> 120.232.18.0/24
> 120.131.14.0/24
> 153.254.86.0/24
> 155.133.245.0/24
> 155.133.254.0/24
> 162.254.195.0/24
> 162.254.193.0/24
> 172.217.24.0/24
> 172.217.11.0/24
> 172.217.25.0/24
> 172.217.161.0/24
> 180.101.192.0/24
> 183.192.196.0/24
> 199.7.83.0/24
> 203.80.149.0/24
> 203.208.41.0/24
> 205.196.6.0/24
> 216.58.200.0/24
> 216.239.34.0/24
> 216.58.197.0/24
> 216.239.36.0/24
> 216.58.199.0/24
> 219.76.10.0/24
> 
> 我手动编辑了下你的规则，把与dns有关的行去掉了，看下这样有用吗

多谢大佬 我昨晚又试了下抓包并且成功了 但是rule并没有你这个这么多 我的rule是
224.0.0.0/24
203.208.41.0/24
239.255.255.0/24
114.114.114.0/24
119.29.29.0/24
45.253.64.0/24
127.0.0.0/24
15.255.255.0/24
8.8.8.0/24
8.8.4.0/24
119.28.28.0/24
172.217.24.0/24
120.131.11.0/24
13.224.253.0/24
13.249.43.0/24
216.58.199.0/24
58.60.10.0/24
52.78.133.0/24
35.241.26.0/24
52.196.73.0/24
35.241.52.0/24
35.190.78.0/24
114.114.115.0/24
219.76.10.0/24
58.251.121.0/24
183.192.196.0/24
117.185.116.0/24
