### ISSUE TITLE
请问这个仅网页浏览器（跳过中国站点）失效是什么原因？

### ISSUE THREAD

**Issue by 1015127214** [FQrabbit/SSTap-Rule#395]
**问题描述**
请问这个仅网页浏览器（跳过中国站点）失效，不能翻墙了，但是换成仅网页浏览器（全局）又可以，
![image](https://user-images.githubusercontent.com/31812278/77162703-833ca200-6ae7-11ea-8010-10b3bd25ea9a.png)

跳过中国站点就是这样的情况，连接为0。
因为平时用游戏较少，浏览器比较多，所以请问一下，谢谢！

**Comment by NormanBB** [comment]
尝试修改本机DNS。

**Comment by 1015127214** [comment]
> 尝试修改本机DNS。

好的，谢谢了！
