### ISSUE TITLE
sstap有bug

### ISSUE THREAD

**Issue by zerozero123** [FQrabbit/SSTap-Rule#40]
一个小小的加速器为什么会吃掉1GB的内存

**Comment by FQrabbit** [comment]
@zerozero123 可能是广告引起的内存溢出

本项目只负责完善规则🌚

**Comment by FQrabbit** [comment]
test

**Comment by FQrabbit** [comment]
test

**Comment by FQrabbit** [comment]
你可以尝试一下这个[方法](https://github.com/FQrabbit/SSTap-Rule/wiki/SSTap%E8%B6%8A%E7%94%A8%E5%86%85%E5%AD%98%E5%8D%A0%E7%94%A8%E8%B6%8A%E5%A4%A7%EF%BC%8C%E7%94%9A%E8%87%B3%E6%AD%BB%E6%9C%BA%3F),或许能帮到你 👍

**Comment by FQrabbit** [comment]
你可以尝试一下这个 [方法](https://github.com/FQrabbit/SSTap-Rule/wiki/SSTap%E8%B6%8A%E7%94%A8%E5%86%85%E5%AD%98%E5%8D%A0%E7%94%A8%E8%B6%8A%E5%A4%A7%EF%BC%8C%E7%94%9A%E8%87%B3%E6%AD%BB%E6%9C%BA%3F) ,或许能帮到你 👍
