### ISSUE TITLE
Skip all China IP mini and LAN 可以打开youtube，但是无法打开视频

### ISSUE THREAD

**Issue by guilin1iu** [FQrabbit/SSTap-Rule#409]
**问题描述**
Skip all China IP mini and LAN 可以打开youtube，但是无法打开视频

将 74.125.0.0/10 添加进去即可

其实就是 video.google.com 的IP地址

**Comment by NormanBB** [comment]
在设置中开启代理DNS功能，并选择智能DNS。

**Comment by guilin1iu** [comment]
> 在设置中开启代理DNS功能，并选择智能DNS。

![image](https://user-images.githubusercontent.com/58240137/80299174-e1366680-87c4-11ea-9f0a-139d1dadde7b.png)


请问您说的是这个吗？尝试之后还是不行呢

**Comment by NormanBB** [comment]
@guilin1iu 该功能目前为实验性，等待日后详细说明。

关于你提到的规则修改，我会留意。

**Comment by guilin1iu** [comment]
> @guilin1iu 该功能目前为实验性，等待日后详细说明。
> 
> 关于你提到的规则修改，我会留意。

谢谢！其实使用它的"内置规则"就可以正常看YouTube的视频。但是我无法取得他内置的规则，应该是写在dll里面了。内置规则虽然能看，但是因为我需要墙掉某些IP，而内置的规则无法这样做，陷入两难

**Comment by NormanBB** [comment]
你说的是系统代理？

你可以在hosts中写入你要墙的ip。

**Comment by guilin1iu** [comment]
是的，我已经写入到host文件中。没开SSTAP之前可以墙掉，使用Skip all China IP mini and LAN的规则时也可以墙掉。但是在使用软件自带的规则“仅网页浏览器（跳过中国站点）-内置规则”时就无法墙掉。不知道为何会这样。而使用“Skip all China IP mini and LAN”规则又无法看YouTube的视频，哈哈哈哈

**Comment by guilin1iu** [comment]
还有补充说明的就是我的网络是移动的，我不知道是否相关，但也一并反映给您

**Comment by guilin1iu** [comment]
打开YouTube网站可以正常访问，但点开视频就如下图所示：
![image](https://user-images.githubusercontent.com/58240137/80361861-33a28080-88b4-11ea-82f6-a31d0fcdaa08.png)
还有，我在打开F12调试模式时，发现是
![image](https://user-images.githubusercontent.com/58240137/80362029-81b78400-88b4-11ea-81b1-ea6e8c965002.png)
应该是googlevideo.com的GET请求无法等到响应。

**Comment by NormanBB** [comment]
https://github.com/FQrabbit/SSTap-Rule/tree/temp

请使用新用法。
