### ISSUE TITLE
麻烦大佬提供个Twitch Studio的规则包，国内无法直播Twitch。

### ISSUE THREAD

**Issue by bestfujianese** [FQrabbit/SSTap-Rule#410]
需要增加游戏\程序名字
Twitch Studio

该游戏\程序的运行环境
如
PC

该游戏\程序哪部分需要代理
如
整个游戏\程序都需要

特殊情况
如果还有特殊想说明的请在这里描述.

**Comment by NormanBB** [comment]
全局，请。

**Comment by bestfujianese** [comment]
全局玩游戏卡

**Comment by bestfujianese** [comment]
老哥帮帮忙吧

**Comment by NormanBB** [comment]
1. 关于issue中的说明，你并没有照做。

2. 全局影响游戏性能请先排除线路问题，而SStap的确有其缺陷，如果你不想折腾这些东西，可购买相应商用加速服务。

**Comment by bestfujianese** [comment]
已经用SSTAP_ip_crawl_tool解决了，还是谢谢你。

**Comment by nanashira** [comment]
想问一下层主是如何解决的 SSTAP_IP_ROPEL_又是什么 可以加我q教一下吗 1584382591

**Comment by FQrabbit** [comment]
#536
