### ISSUE TITLE
Switch 动物之森，求开动森的规则，给跪下了

### ISSUE THREAD

**Issue by eyaeya** [FQrabbit/SSTap-Rule#411]
**Switch 动物之森**

> 暂未抓包，优先支持 日服。其他包含 美服/港服

游戏平台：Switch游戏机
那部分需要翻墙：开岛后与全服朋友联机

**特殊情况**
默认100%无法成功开岛，提示NAT等级不够。

**Comment by NormanBB** [comment]
此工具无法解决你的问题。
