### ISSUE TITLE
仅代理中国ip会造成cpu占用异常

### ISSUE THREAD

**Issue by mikuyourworld** [FQrabbit/SSTap-Rule#414]
**问题描述**
使用仅代理中国ip会造成cpu占用异常

**从哪里开始出现这个问题**
因为自带的仅代理中国ip不好用 随即谷歌找到这个规则github，下载后使用就出现这个问题。
有一个本地服务 显示网络受限，确实占用很高。可以结束。但是除了这个服务以外 还有几个服务 占用也异常高。直接让我的6700跑到了100%占用。
用其他规则没有这个问题。
然后我从ip.cn 拉了一个国内ip地址下来用，发现 只有 本地服务 显示网络受限 这个服务占用率很高，结束后cpu占用基本正常。但是这个服务似乎会时不时重新自己启动。

猜测。和规则文件的大小有关系？该github提供的规则 仅代理国内ip 体积是8000k+，我自己从ip.cn拉取的地址列表是49kb。

**运行环境**
win10

**Comment by NormanBB** [comment]
@mikuyourworld 的确，问题出在这个文件，日后会进行优化。

**Comment by NormanBB** [comment]
@mikuyourworld 可使用mini版的跳过中国大佬的规则，仓库内有。
