### ISSUE TITLE
使命召唤16规则无法使用

### ISSUE THREAD

**Issue by Hankkkk** [FQrabbit/SSTap-Rule#415]
**问题描述**
使用SSTAP连接SSR日本节点 无法使用 测试连接无问题

**从哪里开始出现这个问题**
登录游戏后提示无法连接服务器

**截图**

![image](https://user-images.githubusercontent.com/16262554/80827873-fe30c680-8c16-11ea-98d6-dd7301fd0c5e.png)

**运行环境**
win10最新版本(自动更新)
中国电信网络(河南郑州)

**Comment by Hankkkk** [comment]
![image](https://user-images.githubusercontent.com/16262554/80831906-3b4c8700-8c1e-11ea-9caa-80048256d560.png)
这个是测试连接的图

**Comment by NormanBB** [comment]
目前cod16 已锁区。
