### ISSUE TITLE
请求增加steam远程畅玩规则

### ISSUE THREAD

**Issue by tangli159** [FQrabbit/SSTap-Rule#417]
需要增加游戏\程序名字
steam远程畅玩
该游戏\程序的运行环境
PC
该游戏\程序哪部分需要代理
整个游戏\程序都需要？
特殊说明：并没有抓包，因为这不是个单独的游戏，是一个steam的功能。
steam去年开放了这个功能，大陆小范围测试后就取消了该服务，解释是在大陆没有相关的基础设施支撑。目前网易uu出了单独的steam远程畅玩加速，使用后自动切换到香港，可以开始远程同乐，但是网易uu该服务付费。这个是steam（可能需要测试版）的功能，不知道怎么抓包。

**Comment by NormanBB** [comment]
对于此功能，我了解到国内仅有香港的某些服务器支持。那么在没有相关环境的情况下适配比较困难。
