### ISSUE TITLE
请问自定义规则IP/后面的18、20、22或者其他数字是什么意思？

### ISSUE THREAD

**Issue by tk1114632** [FQrabbit/SSTap-Rule#42]
例如：
45.255.160.0/19
45.255.192.0/19
45.255.224.0/20
45.255.240.0/21

最后一位0我理解是 * 的意思，那后面/XX 数字是什么意思呢？
谢谢

**Comment by FQrabbit** [comment]
@tk1114632 子网掩码的简写

**Comment by Zzmissu** [comment]
CIDR表示法

**Comment by firesky123** [comment]
想请教一下，这个子网掩码要怎么填，后面随便/多少都可以吗
