### ISSUE TITLE
請求添加台服 新瑪奇英雄傳 規則

### ISSUE THREAD

**Issue by xu1310623524** [FQrabbit/SSTap-Rule#420]
需要增加游戏\程序名称
新瑪奇英雄傳   
该游戏\程序的运行环境
PC
该游戏\程序哪部分需要代理
整个游戏\程序都需要
特殊說明  
沒有抓包 因為我是個程序小白 不懂如何抓包

**Comment by NormanBB** [comment]
既然是小白，请使用全局。
