### ISSUE TITLE
使用规则（不代理国内）+ss全局导致冒险岛日服NGS的问题

### ISSUE THREAD

**Issue by maplestorykaede** [FQrabbit/SSTap-Rule#423]
**问题描述**
冒险岛日服在游戏过程中进行特定动作时NGS的问题

**测试方法**
0，sstap使用规则都为，不代理中国国内。
1，仅使用sstap，sstap直接添加ss服务器地址
2，使用sstap和ss，sstap直接添加本机地址（127.0.0.1），ss使用pac模式（pac文件已经从gfwlist更新）
3，使用sstap和ss，sstap直接添加本机地址（127.0.0.1），ss使用全局模式

**从哪里开始出现这个问题**
以上三种情况都在
进入拍卖行之后，一分钟不到的时间
新建部分职业角色的时候
出现NGS

**截图**
没找到截图如何添加。

**运行环境**
``操作系统``：win7 日文旗舰版，区域语言为cn，登录游戏使用了locale emulator
``网络环境``：长城宽带

还有些不完整的地方回头进行补充。

**Comment by NormanBB** [comment]
@maplestorykaede 首先，建议你单使用sstap进行测试。还是你需要ss的一些功能？既然是绕过中国大陆，尝试使用更新后使用方法。

https://github.com/FQrabbit/SSTap-Rule/tree/temp

**Comment by maplestorykaede** [comment]
> 
> 
> @maplestorykaede 首先，建议你单使用sstap进行测试。还是你需要ss的一些功能？既然是绕过中国大陆，尝试使用更新后使用方法。
> 
> https://github.com/FQrabbit/SSTap-Rule/tree/temp

很抱歉我的描述太暧昧了，已经修改了部分内容，若有时间请看看，谢谢。

**Comment by NormanBB** [comment]
鉴于游戏采用的反外挂系统（不清楚机制），我也没有相应游戏进行测试，只能从我熟知的方面给你一些建议。

DNS问题有没有设置正确？线路有没有问题？locale emulator 有没有影响？

**Comment by FQrabbit** [comment]
请问NGS是只封号的意思吗？如果是封号，可能涉及到很多问题

首先第一，这个游戏是否存在不是当地ip禁止登录，如果是的话，规则代理不上那你应该进入不到游戏
如果规则成功代理，说明你在用当地的ip进行访问游戏服务器，但是你的ip可能是因为是商宽ip，会容易触发对方游戏服务器的检测，从而导致你的封号概率上升，你或许尝试使用当地的家宽ip进行代理游玩.

第二种情况，就是你使用pac规则，会导致部分场景访问的时候，用的是你cn的ip进行访问服务器，结果导致你在游玩的时候不同ip使用同一个角色进行游玩，导致风控或反作弊之类的检测导致的封号.
  
我觉得SSTap配合ss的pac规则代理可能不太合适，双重分流容易出现分流不到位等问题.

**Comment by maplestorykaede** [comment]
最近我只开sstap且使用全局模式进行了一次测试，发现在进入游戏拍卖行的时候依然会NGS。另外，某网友说他在家用路由器上直接用的ss，没有任何问题。
我在想，可能是该游戏的安全系统检测到了什么。

**Comment by maplestorykaede** [comment]
> 
> 
> 请问NGS是只封号的意思吗？如果是封号，可能涉及到很多问题
> 
> 首先第一，这个游戏是否存在不是当地ip禁止登录，如果是的话，规则代理不上那你应该进入不到游戏
> 如果规则成功代理，说明你在用当地的ip进行访问游戏服务器，但是你的ip可能是因为是商宽ip，会容易触发对方游戏服务器的检测，从而导致你的封号概率上升，你或许尝试使用当地的家宽ip进行代理游玩.
> 
> 第二种情况，就是你使用pac规则，会导致部分场景访问的时候，用的是你cn的ip进行访问服务器，结果导致你在游玩的时候不同ip使用同一个角色进行游玩，导致风控或反作弊之类的检测导致的封号.
> 
> 我觉得SSTap配合ss的pac规则代理可能不太合适，双重分流容易出现分流不到位等问题.

ngs是这个游戏的安全组件，类似于腾讯的TP一样。

**Comment by maplestorykaede** [comment]
> 
> 
> 鉴于游戏采用的反外挂系统（不清楚机制），我也没有相应游戏进行测试，只能从我熟知的方面给你一些建议。
> 
> DNS问题有没有设置正确？线路有没有问题？locale emulator 有没有影响？

抱歉，很早之前就已经测试过了但是没有开回复。
1.DNS设置成四个8之后好像连游戏都上不去了。
2.不使用LE依然NGS，通过某付费加速器配合LE使用正常，不会NGS。

近期内我会开启加速器来抓下包，整理好目标IP的list，到时候还请麻烦您添加一下游戏规则，谢谢。
