### ISSUE TITLE
连不上网络

### ISSUE THREAD

**Issue by Happiness-in-Danger** [FQrabbit/SSTap-Rule#426]
**问题描述**
1、节点会突然全部消失，手动更新也刷不出来。
2、在不代理中国IP模式下，能连接上，答案是国外网站一律打不开

**从哪里开始出现这个问题**
浏览网页就突然不行了，查看延时会特别高，自那以后就会出现第二类问题。不是节点问题。

**截图**
![图片](https://user-images.githubusercontent.com/45912561/83320052-4ffc5900-a276-11ea-8f30-151a51aa8064.png)

**运行环境**
Win10
联通4G网络

**Comment by NormanBB** [comment]
@Happiness-in-Danger 问题1 是机场的订阅不稳定导致的。

问题2 是规则要更新了。

参见：https://github.com/FQrabbit/SSTap-Rule/tree/temp
