### ISSUE TITLE
请求新增规则 坦克世界闪电战亚服

### ISSUE THREAD

**Issue by Cyancat000** [FQrabbit/SSTap-Rule#431]
**需要增加游戏\程序名字**

坦克世界闪电战\World of Tanks Blitz

**服务器**

亚洲

**版本**

7.1.0

**该游戏\程序的运行环境**

Steam
Windows 10(UWP)
Mac
Android
IOS

**该游戏\程序哪部分需要代理**

整个游戏都需要

**特殊情况**
无

***已使用[自动抓IP工具](https://github.com/oooldtoy/SSTAP_ip_crawl_tool)并测试***

```
#World of Tanks Blitz,坦克世界闪电战,0,0,1,0,1,0,By-ip_crawl_tool
92.223.29.0/24
208.64.200.0/24
35.160.106.0/24
93.158.134.0/24
203.208.50.0/24
92.223.20.0/24
100.20.164.0/24
52.25.28.0/24
92.223.96.0/24
92.223.122.0/24
35.156.181.0/24
92.223.17.0/24
13.224.8.0/24
52.38.231.0/24
52.34.84.0/24
```

**Comment by NormanBB** [comment]
👍
