### ISSUE TITLE
路由转SSTAP规则工具

### ISSUE THREAD

**Issue by ABXYvvv** [FQrabbit/SSTap-Rule#439]
**问题描述**
路由转SSTAP规则工具 点击转换显示 加载失败

**从哪里开始出现这个问题**
网页

**截图**
如果可以，请添加截图以帮助解释您的问题.

**运行环境**
Edge
win10

**Comment by NormanBB** [comment]
请贴出你的路由表。

**Comment by ABXYvvv** [comment]
非常感谢你的回答，我已经分段转换成功，可能是因为一次转换的数据太多导致的失败。
