### ISSUE TITLE
关于如何使用？

### ISSUE THREAD

**Issue by Undifinedu** [FQrabbit/SSTap-Rule#446]
**问题描述**
是ss-tap上添加服务器后加速吗？还是直接改路由表后就能用？

**从哪里开始出现这个问题**

**截图**
如果可以，请添加截图以帮助解释您的问题.

**运行环境**
请说明当前的运行环境
例如：
``操作系统`` Win10
``网络环境``（上海电信 等

**Comment by NormanBB** [comment]
@Undifinedu 基础问题先google搜索。
