### ISSUE TITLE
Heroes & Generals

### ISSUE THREAD

**Issue by KineDenton** [FQrabbit/SSTap-Rule#465]
需要增加游戏\程序名字
Heroes & Generals

该游戏\程序的运行环境
PC

该游戏\程序哪部分需要代理

整个游戏\程序都需要

特殊情况
雷神，流星，netch加速游戏和不加速一个效果

**Comment by FQrabbit** [comment]
> 需要增加游戏\程序名字
> 
> Heroes & Generals
> 
> 
> 
> 该游戏\程序的运行环境
> 
> PC
> 
> 
> 
> 该游戏\程序哪部分需要代理
> 
> 
> 
> 整个游戏\程序都需要
> 
> 
> 
> 特殊情况
> 
> 雷神，流星，netch加速游戏和不加速一个效果

如果游戏进程本体不走网络，可能需要找到它用哪个模块进行网络访问了🤔
