### ISSUE TITLE
用SSTap连接ssr的外网IP后，无法使用ping

### ISSUE THREAD

**Issue by zhaowenjun** [FQrabbit/SSTap-Rule#469]
**问题描述**
简单清晰的说一下问题的描述.
选用不代理中国IP规则，连接SSR后（IP为香港），我用本地ping不通任何外网的ip，游戏内的服务器与我连接的外网ip ping值也不显示。但我用网页浏览器-内置规则，ping的通，但是我游戏打不打。  想请教下，是不是我用不代理中国IP规则后，该规则把443端口被屏蔽了啊，我想知道怎么修改规则放通443。。。  我的ssr服务器443是开通的。

**Comment by NormanBB** [comment]
@zhaowenjun 换软件。

**Comment by oooldtoy** [comment]
@zhaowenjun Ss不代理icmp协议。虚拟网卡模式下自然ping不通。网页模式不是全局代理，就能ping通了

**Comment by zhaowenjun** [comment]
@NormanBB @oooldtoy 谢谢解答，也就是说我自己搭建的ssr服务，不可以用SSTAP或者Netch这种软件连接了撒？如果换软件，求推荐一下换什么软件好呢？我以前购买过收费的加速器，他们能够正常的连接游戏，并且能ping通，是不是他们的软件在实现加速的基础上后，又进行了icmp协议支持？还是说他们的技术不一样啊？

**Comment by NormanBB** [comment]
@zhaowenjun 接上面的解释，对于sstap，应该是无法实现你想要的功能。netch我不清楚。但对于你自己搭建的ssr服务，sstap可以进行连接。

PS sstap启用相应规则后不会对端口加限制。ping也没有端口的概念。再者，建议加群来获取你n个问题的答案。

**Comment by zhaowenjun** [comment]
@NormanBB 太感谢，我就是想通过sstap启用相应规则取消对端口的限制。我看了一些sstap的规则，大部分都是直接添加需要适配的游戏或者网络的ip，但是怎么取消端口限制的规则，还是没找到答案。  大佬能不能推荐个这方面知识的群？我今天也是百度到这个规则github的。

**Comment by NormanBB** [comment]
@zhaowenjun https://t.me/SSTapRule

**Comment by zhaowenjun** [comment]
@NormanBB 感谢！
