### ISSUE TITLE
How do these come to be?

### ISSUE THREAD

**Issue by KaratekHD** [FQrabbit/SSTap-Rule#473]
Sorry for writing an issue in English.
I just stumbled over this repository, namely about rules/Discord-All.rules. 
How did you find this list of servers? 
I'm currently trying to get Discord running behind a firewall together with my father, and he wants to be able to generate this list on his own.
Any help is appreciated.
Thank you
- Karatek

**Comment by NormanBB** [comment]
@KaratekHD I think this website might help you.

https://www.netify.ai/resources/applications/discord

**Comment by KaratekHD** [comment]
That looks promising, thank you!
