### ISSUE TITLE
求添加个暗黑2亚服的规则

### ISSUE THREAD

**Issue by ccc919** [FQrabbit/SSTap-Rule#475]
暗黑2狱火重生-亚服

**Comment by skyblueing** [comment]
同求

**Comment by skyblueing** [comment]
#DR2,暗黑2,0,0,1,0,1,0,By-elmagnifico
117.52.35.0/24
37.244.54.0/24
24.105.29.0/24
203.208.50.0/24
96.17.68.0/24
142.250.68.0/24
34.117.122.0/24
35.247.166.0/24
54.192.18.0/24
104.91.68.0/24
37.244.28.0/24
13.224.154.0/24
142.250.66.0/24
35.200.162.0/24

**Comment by zhangdiming** [comment]
#525
