### ISSUE TITLE
请求增加eve 世界服的规则，谢谢了

### ISSUE THREAD

**Issue by wnark** [FQrabbit/SSTap-Rule#48]
eve online 世界服

Windows/mac

整个游戏都需要代理

**特殊情况**
eve online 世界服的资源下载貌似走的是亚马逊的cdn，如果可以的话希望也能增加

**Comment by coldeve** [comment]
我知道连接的ip是：
54.192.151.45
54.192.151.46
54.192.151.90
54.192.151.50
54.192.151.17
54.192.151.95
54.192.151.104
54.192.151.80
54.192.150.236
 54.192.151.58
54.192.151.6
54.192.151.14
54.192.151.63
54.192.151.17
54.192.151.120
54.192.151.11
54.192.151.62
209.58.176.97
151.101.0.133
151.101.64.133
151.101.128.133
151.101.192.133
87.237.34.203
54.192.151.127
54.192.151.124
54.192.151.122
54.192.151.50
54.243.179.137
50.16.248.221
54.243.123.39
50.19.229.252
23.23.114.123
23.21.121.219
52.51.50.62
34.247.149.5
54.246.208.25
54.192.151.105
54.192.151.29
54.192.151.65
54.192.151.12
87.237.34.107
54.192.151.81
54.192.151.38
54.192.151.10
54.192.151.113
87.237.34.107
54.192.151.95
54.192.151.104
54.192.151.80
54.192.151.17
52.90.52.15
但不知道怎么填入sstap的新增IP
我填的是：
23.21.121.0/24
23.23.114.0/24
34.247.149.0/24
50.16.248.0/24
50.19.229.0/24
52.51.50.0/24
52.90.52.0/24
54.192.150.0/24
54.192.151.0/24
54.243.123.0/24
54.243.179.0/24
54.246.208.0/24
87.237.34.0/24
151.101.0.0/24
151.101.64.0/24
151.101.128.0/24
151.101.192.0/24
209.58.176.0/24
连不上去

**Comment by coldeve** [comment]
已上传

**Comment by FQrabbit** [comment]
emmmm，抓出来之后，用这个规则又无效还是什么意思

**Comment by coldeve** [comment]
这个是eve世界服（欧服）的规则，eve还有个国服。
使用方法不是安装好sstap后，将这个文件放入sstap的rule文件夹内，重启电脑（sstap）选项内就有了。

**Comment by FQrabbit** [comment]
@coldeve 晚点我帮你整理一下就给你合并🤔

**Comment by coldeve** [comment]
> @coldeve晚点我帮你整理一下就给你合并🤔

喔 不用，我已经整理好等待管理员合并了，谢谢
