### ISSUE TITLE
能不能指定某个EXE程序不走代理？

### ISSUE THREAD

**Issue by SingleTata** [FQrabbit/SSTap-Rule#485]
因为平时用的都是默认的那个绕开国内IP的默认规则，然后就不会读取rule里面的规则
所以请问有没有不通过IP，而是强制指定部分exe程序直连或者地阿里

**Comment by FQrabbit** [comment]
> 因为平时用的都是默认的那个绕开国内IP的默认规则，然后就不会读取rule里面的规则
> 
> 所以请问有没有不通过IP，而是强制指定部分exe程序直连或者地阿里

如果有指定进程代理需求，可以尝试使用_Netch_
