### ISSUE TITLE
求 艦隊これくしょん -艦これ- 规则

### ISSUE THREAD

**Issue by charliezzo** [FQrabbit/SSTap-Rule#49]
**需要增加游戏\程序名字**
艦隊これくしょん -艦これ-

**该游戏\程序的运行环境**
``专用浏览器poi：https://github.com/poooi/poi``

**该游戏\程序哪部分需要代理**
``整个游戏\程序都需要``

**Comment by FQrabbit** [comment]
@charliezzo Poi我记得不是只是一个框架吗？🤔

话说舰c玩家应该都在用岛风go?🤔

**Comment by charliezzo** [comment]
找到了

**Comment by charliezzo** [comment]
43.255.40.0/22	
103.254.144.0/22
157.112.80.0/20
202.6.244.0/22
223.252.113.0/24
223.252.114.0/24
抓到了这些可以登录，但是不能游戏，这个客户端蛮麻烦的。

**Comment by FQrabbit** [comment]
@charliezzo Poi不是...单纯的一个框架吗，你直接抓dmm网页不是就可以了吗🤔

**Comment by charliezzo** [comment]
@FQrabbit 现在在抓 DMM CENTER ，网页已经可以用了。

**Comment by charliezzo** [comment]
@FQrabbit DMM CENTER是怎么都不能用，不知道为啥。
