### ISSUE TITLE
加速器规则转换失败

### ISSUE THREAD

**Issue by zhangnanlin** [FQrabbit/SSTap-Rule#490]
**问题描述**
我在kk加速器里面加速了游戏冒险岛(台服)，并且成功提取了路由，但是后续转换规则失败了，看浏览器f12接口返回了一个code:1，data:''

**从哪里开始出现这个问题**
转换规则时

**截图**
![image](https://user-images.githubusercontent.com/88031412/158731737-6bb9868d-9e08-40ab-96d7-a43875e17818.png)

这个是路由文档
[route.txt](https://github.com/FQrabbit/SSTap-Rule/files/8281199/route.txt)

**Comment by AmazingDM** [comment]
加速模式错了 换个模式试试，正常情况下路由模式加速会有非常多的活动路由
