### ISSUE TITLE
对PR进行奖励的告示

### ISSUE THREAD

**Issue by NormanBB** [FQrabbit/SSTap-Rule#494]
即日起，若您对本项目发起合格的PR，待审核通过后，将可联系[此邮箱](mailto:@15920548078@163.com)获得奖励一份。

其他对本项目有贡献的行为也可酌情考虑。

~~碎碎念，项目的确在走下坡路，玩玩而已，诸君随意。~~

**Comment by NormanBB** [comment]
![屏幕截图 2022-07-23 194359](https://user-images.githubusercontent.com/18748504/180603615-a8d0c845-7c27-43dc-85bc-eca631e82f80.png)

已为 @MirrorCY 发放一笔奖励。

**Comment by NormanBB** [comment]
已为 #506 发放两笔奖励

**Comment by MirrorCY** [comment]
感谢奖励～我教一下我朋友也来帮忙更新规则



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月24日(周日) 晚上6:09
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [FQrabbit/SSTap-Rule] 对PR进行奖励的告示 (Issue #494)




 
已为 #506 发放两笔奖励

**Comment by NormanBB** [comment]
@MirrorCY 努力获取uu的规则是第一步，第二步则是想想怎样才能取消掉第一步，提高生产力，从而获得隐藏大奖。这一步[此项目](https://github.com/oooldtoy/SSTAP_ip_crawl_tool)已经做出了很好的尝试。

不过我希望为项目作出贡献是你最大的动力，而不是获取奖励，毕竟自驱力相比有限的奖励来得更持久。

当然我也接受你将所有的issue都解决或者更新其他规则，从而获取所有的奖励。

@FQrabbit 你怎么看？

**Comment by cscli** [comment]
> @MirrorCY 努力获取uu的规则是第一步，第二步则是想想怎样才能取消掉第一步，提高生产力，从而获得隐藏大奖。这一步[此项目](https://github.com/oooldtoy/SSTAP_ip_crawl_tool)已经做出了很好的尝试。
> 
> 不过我希望为项目作出贡献是你最大的动力，而不是获取奖励，毕竟自驱力相比有限的奖励来得更持久。
> 
> 当然我也接受你将所有的issue都解决或者更新其他规则，从而获取所有的奖励。
> 
> @FQrabbit 你怎么看？
请问获取uu的规则是怎么个思路，谢谢

**Comment by NormanBB** [comment]
@cscli 参见 https://github.com/FQrabbit/SSTap-Rule/blob/master/doc/UU-extract.md
