### ISSUE TITLE
你好，路由表提取了，但是转换的时候显示加载出错

### ISSUE THREAD

**Issue by yeqirt** [FQrabbit/SSTap-Rule#497]
![QQ截图20220509122645](https://user-images.githubusercontent.com/65324711/167340641-a64b7300-cb84-4028-99e8-a53f77d60eb9.png)

失落的方舟-steam

**Comment by AmazingDM** [comment]
请上传你需要转换的内容

**Comment by yeqirt** [comment]
> 请上传你需要转换的内容
[route.txt](https://github.com/FQrabbit/SSTap-Rule/files/8660350/route.txt)

**Comment by AmazingDM** [comment]
[Rule.txt](https://github.com/FQrabbit/SSTap-Rule/files/8660408/Rule.txt)

**Comment by yeqirt** [comment]
> 

好的，感谢
