### ISSUE TITLE
因为OpenClash代理时国服登录异常，我自己抓取了 战舰世界国服的规则

### ISSUE THREAD

**Issue by cfj521** [FQrabbit/SSTap-Rule#500]
#wows_cn,战舰世界国服,0,0,1,0,1,0,By-ip_crawl_tool
172.67.34.0/24
8.133.124.0/24
8.133.125.0/24

以下是所有ip
-----------------
172.67.34.170 172.67.34.0 
8.133.124.41 8.133.124.0 
8.133.125.116 8.133.125.37  8.133.125.54  8.133.125.69  8.133.125.145  8.133.125.153  8.133.125.175  8.133.125.0

**Comment by MirrorCY** [comment]
#506 已更新规则，有条件可以帮忙测试
