### ISSUE TITLE
CSGO香港服的规则失效，搜索时无法连接到服务器。

### ISSUE THREAD

**Issue by SusuWei** [FQrabbit/SSTap-Rule#503]
**问题描述**
CSGO香港服的规则失效，搜索时无法连接到服务器。

**从哪里开始出现这个问题**

游戏房间内部

**截图**
我自己从网易UU导出的路由规则也不能用--

**运行环境**

河北电信Win10

**Comment by MirrorCY** [comment]
#506 已更新规则，请测试
