### ISSUE TITLE
提供免费加速服务器以供测试

### ISSUE THREAD

**Issue by MirrorCY** [FQrabbit/SSTap-Rule#507]
现对规则贡献者提供免费加速服务器以供测试规则   感谢 @NormanBB 赞助
可以使用[这个项目](https://github.com/oooldtoy/SSTAP_ip_crawl_tool)来进行规则抓取，基本是全自动的
提交PR后联系<MirrorCY@vip.qq.com>以获取服务器地址

**Comment by MirrorCY** [comment]
如果没有账号或者不会使用Github的可以直接把抓出来的规则发我邮箱

**Comment by MirrorCY** [comment]
由于三个月来无人使用，现已关闭测试服务器。
有人需要自建的Apex Legends加速器的话，回复此issue，够人开放。

**Comment by a1385679569** [comment]
来个试试？

**Comment by MirrorCY** [comment]
留下邮箱我发你
