### ISSUE TITLE
请大佬增加origin规则

### ISSUE THREAD

**Issue by esen-biaobiao** [FQrabbit/SSTap-Rule#52]
**需要增加游戏\程序名字**
``origin``

**该游戏\程序的运行环境**
``PC``

**该游戏\程序哪部分需要代理**
``整个程序都需要``

**Comment by 982959103** [comment]
上客户端可以，但是下载无效

**Comment by esen-biaobiao** [comment]
@982959103 直接用全局下载就可以了
