### ISSUE TITLE
Update China IP list and generate BypassCN.rule Failed

### ISSUE THREAD

**Issue by NormanBB** [FQrabbit/SSTap-Rule#544]
![image](https://github.com/FQrabbit/SSTap-Rule/assets/18748504/9253ac3a-696b-434c-8ca7-887bd35a6bfd)

@KoinuDayo 看起来是上游没有更新？

**Comment by KoinuDayo** [comment]
应该是，你可以试试看把rule修改为空文件，再重新跑一遍workflow。如果成功了就是上游没更新

**Comment by KoinuDayo** [comment]
https://github.com/FQrabbit/SSTap-Rule/pull/545 修了

**Comment by NormanBB** [comment]
git checkout --orphan release-orphan
        git rm -rf .

        cp -rf dist/CN-ip-cidr.txt ./
        cp -rf dist/Country.mmdb ./

        git add Country.mmdb
        git add CN-ip-cidr.txt
        git commit -am "Updated at $(date)"

        git branch -D release
        git branch -m release
            
上游的做法是，切换到 orphan 分支 ，删除了 release 分支，将 orphan 分支命名为 release
一套下来后分支里仅存在一个 commit, 我个人不希望分支里存在许多空 commit。
@FQrabbit  你觉得呢？

**Comment by FQrabbit** [comment]
> ```
>     git checkout --orphan release-orphan
>     git rm -rf .
> 
>     cp -rf dist/CN-ip-cidr.txt ./
>     cp -rf dist/Country.mmdb ./
> 
>     git add Country.mmdb
>     git add CN-ip-cidr.txt
>     git commit -am "Updated at $(date)"
> 
>     git branch -D release
>     git branch -m release
> ```
> 
> 上游的做法是，切换到 orphan 分支 ，删除了 release 分支，将 orphan 分支命名为 release 一套下来后分支里仅存在一个 commit, 我个人不希望分支里存在许多空 commit。 @FQrabbit 你觉得呢？

确实没有空commit会好许多，看上去这样子切换分支逻辑没什么问题，但删除分支这种操作会不会有潜在问题，例如说删除分支之后新分支命名回原来名字的时候如果出错会怎么样.

**Comment by KoinuDayo** [comment]
实际上我认为现在这样就可以，没必要修改。上游没更新咱也不需要更新，~~只是workflow失败比较不好看~~

**Comment by FQrabbit** [comment]
> 实际上我认为现在这样就可以，没必要修改。上游没更新咱也不需要更新，~只是workflow失败比较不好看~。
> 
> 可以在workflow脚本内添加判断条件，如果commit失败，那么使用 `echo` 输出上游未更新，然后 `exit 0` ，这样应该可以缓解问题。

现在fail不会commit的话，其实也没问题，workflow可以删除失败的事件么

**Comment by KoinuDayo** [comment]
> > 实际上我认为现在这样就可以，没必要修改。上游没更新咱也不需要更新，~只是workflow失败比较不好看~。
> > 
> > 可以在workflow脚本内添加判断条件，如果commit失败，那么使用 `echo` 输出上游未更新，然后 `exit 0` ，这样应该可以缓解问题。
> 
> 现在fail不会commit的话，其实也没问题，workflow可以删除失败的事件么

是指手动删还是指让workflow自动删。
前者的答案是可以，后者我记得也是可以的。
添加一个workflow，修改触发判断条件为当某个workflow complete，获取是否失败，如果为失败那么删除失败的workflow run。

**Comment by FQrabbit** [comment]
> 是指手动删还是指让workflow自动删。 前者的答案是可以，后者我记得也是可以的。 添加一个workflow，修改触发判断条件为当某个workflow complete，获取是否失败，如果为失败那么删除失败的workflow run。

www太麻烦的话不弄自动也行，偶尔上去删一下问题也不大

**Comment by KoinuDayo** [comment]
> www太麻烦的话不弄自动也行，偶尔上去删一下问题也不大

那我有空再整个自动删的，~~也不算麻烦，主要只是我现在不在家没办法写~~

**Comment by KoinuDayo** [comment]
https://github.com/FQrabbit/SSTap-Rule/pull/550
修了，让它判断上游是否更新，如果更新了但是无法commit才会报错

**Comment by NormanBB** [comment]
@KoinuDayo 

> #550 修了，让它判断上游是否更新，如果更新了但是无法commit才会报错。 之前失败的workflow run手动删下吧，我认为自动删会把真的出问题的也删掉，还是得留着。
> Add: If Upstrean Updated but can't commit, it will return ERROR, and exit 1 .

```
shell: /usr/bin/bash -e {0}
From https://github.com/FQrabbit/SSTap-Rule
   7d69684..e[10](https://github.com/FQrabbit/SSTap-Rule/actions/runs/5908929299/job/16031908500#step:4:11)8fd9  master     -> origin/master
On branch master
Your branch is behind 'origin/master' by 2 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	BypassCNandLan.rules

nothing added to commit but untracked files present (use "git add" to track)
Error: Process completed with exit code 1.
```

看起来还是有问题？

**Comment by KoinuDayo** [comment]
@NormanBB 
![Screenshot_20230819-225630_GitHub.png](https://github.com/FQrabbit/SSTap-Rule/assets/123655015/6661fae5-f0ea-4bc5-a61d-7a4b6a57bb30)

看起来是workflow checkout时没检出最新commit。可以试试看在 `git fetch` 后面加上 `git pull` 。或只是github刚好抽风了，试试看手动跑一遍，我在自己fork的仓库内跑没办法复现，具体发生什么和为什么会这样，我不太明白。

**Comment by KoinuDayo** [comment]
![Screenshot_20230819-230606_GitHub.png](https://github.com/FQrabbit/SSTap-Rule/assets/123655015/6d688e63-ab9c-4395-91fd-09881ffa930f)

正常的情况下最新commit的workflow应该是像这样的。

**Comment by NormanBB** [comment]
@KoinuDayo 
>  如果你是手动把之前的重新跑了的话，是不会使用最新commit的，得手动跑最新commit才会使用最新commit的内容。

是的，你说得对
![image](https://github.com/FQrabbit/SSTap-Rule/assets/18748504/4be5ea66-d3d5-4a76-94f6-f7da8de81525)
![image](https://github.com/FQrabbit/SSTap-Rule/assets/18748504/1769ce25-319a-4a73-9aaa-e7b1b7bb15fc)

多谢您的贡献。
