### ISSUE TITLE
invalid path windows下不允许的文件命名

### ISSUE THREAD

**Issue by TheOnlyPathfinder** [FQrabbit/SSTap-Rule#549]
**问题描述**
仓库里的路径  'rules/Hunt: Showdown-Asia.rules'  由于包含了冒号是windows下的无效路径，会导致widows 下 git clone失败

**从哪里开始出现这个问题**
git clone 时

建议把名字里的冒号删掉

**Comment by FQrabbit** [comment]
[commit](https://github.com/FQrabbit/SSTap-Rule/commit/7d696841c374464bd07a3cd420f4f08da6a68736)
已修改，感谢.
