### ISSUE TITLE
Apex 2023/12/24

### ISSUE THREAD

**Issue by Xqing-hup** [FQrabbit/SSTap-Rule#559]
### 问题描述

所有模式均正常匹配但是无法进入

### 从哪里开始出现这个问题

进入游戏界面（匹配成功）

### 截图

如下是我在最新模式抓到的IP（你们提供的Python 抓IP工具）并未做去重处理（你们提供的Apex 规则，非apex-uu文件）

54.245.85.0/24
52.25.224.0/24
54.164.68.0/24
44.225.198.0/24
108.128.92.0/24
35.169.181.0/24
35.80.96.0/24
52.208.75.0/24
54.83.43.0/24
104.21.45.0/24
159.153.191.0/24
52.218.232.0/24
34.211.122.0/24
52.55.146.0/24
52.5.107.0/24
54.158.196.0/24
3.210.214.0/24
184.25.198.0/24
35.155.149.0/24
44.195.184.0/24
54.190.185.0/24
54.75.203.0/24
35.170.144.0/24
108.128.89.0/24
35.164.4.0/24
52.88.215.0/24
44.197.254.0/24
52.42.171.0/24
34.211.65.0/24
54.173.169.0/24
18.206.28.0/24
54.77.133.0/24

![屏幕截图 2023-12-24 130429](https://github.com/FQrabbit/SSTap-Rule/assets/122222347/3436d0d8-1ca0-4094-bc61-776386393ef0)

![屏幕截图 2023-12-24 130614](https://github.com/FQrabbit/SSTap-Rule/assets/122222347/4e12c712-781f-499c-a4cc-c8efd05ba2c1)
![屏幕截图 2023-12-24 130827](https://github.com/FQrabbit/SSTap-Rule/assets/122222347/726ae3bb-c769-4a82-9bfe-71bdf4666646)

### 运行环境

Windows，电信，自己搭建的socks5代理。

**Comment by chise0713** [comment]
请问抓到的IP是否可以正常游戏？如果可以的话麻烦修改现有的规则，加入新抓到的IP，开一个PR。感谢

**Comment by Xqing-hup** [comment]
> 请问抓到的IP是否可以正常游戏？如果可以的话麻烦修改现有的规则，加入新抓到的IP，开一个PR。感谢

抱歉并不能，如果可以我会申请提交修改规则。不过我已发现另外一个问题或许有关，但我开启sstap连接之后Windows 11 右下角会显示断网，但实际可以正常ping以及访问网站进入游戏。（不可以进入对战）

**Comment by Xqing-hup** [comment]
> 请问抓到的IP是否可以正常游戏？如果可以的话麻烦修改现有的规则，加入新抓到的IP，开一个PR。感谢

抓到的IP，我纳入原本规则之后重启sstap进行连接仍然是这样。但是的确有新IP

**Comment by chise0713** [comment]
开一个新的游戏账号也可以复现吗，这么问的原因是我看到第三张图里写了似乎是账号问题

**Comment by Xqing-hup** [comment]
> 开一个新的游戏账号也可以复现吗，这么问的原因是我看到第三张图里写了似乎是账号问题

应该也可以复现，我在抓ip的时候分别使用了代理、无代理和加速器三种方法。其中无代理和加速器可以正常游戏。（代理，就是开启sstao连接加速）最后一次我加入了我抓到的所有IP仍然如此不可进入对战。

**Comment by Xqing-hup** [comment]
> > 开一个新的游戏账号也可以复现吗，这么问的原因是我看到第三张图里写了似乎是账号问题
> 
> 应该也可以复现，我在抓ip的时候分别使用了代理、无代理和加速器三种方法。其中无代理和加速器可以正常游戏。（代理，就是开启sstao连接加速）最后一次我加入了我抓到的所有IP仍然如此不可进入对战。

无代理：v2ray使用全局。
加速器：ak加速器。

**Comment by chise0713** [comment]
你的代理服务器是否可以正常访问apex服务器，全局代理的情况下试试看。
若是不可以正常访问可以考虑套cloudflare的warp，这里有个[脚本](https://github.com/chise0713/warp-reg.sh/(和[程序](https://github.com/chise0713/wgcf-cli/)可以获取warp的第三方程序的入口。

**Comment by Xqing-hup** [comment]
> 你的代理服务器是否可以正常访问apex服务器，全局代理（v2ray的全局代理不会代理游戏，需要使用sstap或其他透明代理软件）的情况下试试看。
> 若是不可以正常访问可以考虑套cloudflare的warp，这里有个[脚本](https://github.com/chise0713/warp-reg.sh/)和[程序](https://github.com/chise0713/wgcf-cli/)可以获取warp的第三方程序的入口。

我的代理服务器，可以正常访问apex服务器。我会进行你的建议在周末。

**Comment by chise0713** [comment]
既然可以那应该就不是服务器的问题了，可以找其他人测试下规则是否正常，可以尝试使用[netch](https://github.com/NetchX/Netch)或[proxifier](https://github.com/y9nhjy/Proxifier-Keygen)进行进程代理来进行确定是否确实是规则集的问题。

**Comment by Xqing-hup** [comment]
> 既然可以那应该就不是服务器的问题了，可以找其他人测试下规则是否正常，可以尝试使用[netch](https://github.com/NetchX/Netch)或[proxifier](https://github.com/y9nhjy/Proxifier-Keygen)进行进程代理来进行确定是否确实是规则集的问题。

好，周末我会借用他人账号进行尝试，到时候反馈。（原规则和我抓到的都进行尝试）你说的工具我周末研究一下怎么用。

**Comment by Xqing-hup** [comment]
> 这应该就不是服务器的问题了，可以找其他人测试下规则是否正常，可以尝试使用[netch](https://github.com/NetchX/Netch)或[proxifier](https://github.com/y9nhjy/Proxifier-Keygen)进行进程代理来进行确定是否确实是规则集的问题。

我已尝试更换账户，目前还是这个情况，只要一连接我Win11右下角就会显示断开网络，但是还是可以正常访问网络。
