### ISSUE TITLE
求一个游戏的规则

### ISSUE THREAD

**Issue by blacksugarboy** [FQrabbit/SSTap-Rule#58]
**需要增加游戏\程序名字**
BlackSurvivor（黑色幸存者）

**该游戏\程序的运行环境**
PC（steam）

**该游戏\程序哪部分需要代理**
整个游戏\程序都需要

**特殊情况**
使用全局sstap连接数显示5个，但自己扒出来的ip无法使用

**Comment by AmazingDM** [comment]
已添加，期待你的尝试。

**Comment by blacksugarboy** [comment]
规则无效，未起到作用

**Comment by blacksugarboy** [comment]
> 已添加，期待你的尝试。

规则无效，未起到作用，能否再帮忙尝试？
