### ISSUE TITLE
求 maple story 美服规则

### ISSUE THREAD

**Issue by liusy-jz** [FQrabbit/SSTap-Rule#64]
**需要增加游戏\程序名字**
maple story 美服

**该游戏\程序的运行环境**
PC

**该游戏\程序哪部分需要代理**
只代理登陆部分

**特殊情况**
无

**Comment by liusy-jz** [comment]
因为我登录部分就进不去，所以这样写的，可能后续也需要吧

**Comment by HustCoderHu** [comment]
我拿 openvpn + udp2raw 搭了个代理，你要不要试试

**Comment by liusy-jz** [comment]
我用SS试过了，进程里面有代理好像就不行

**Comment by HustCoderHu** [comment]
你不是用的steam?
我sstap启动steam里的maple没问题

**Comment by liusy-jz** [comment]
我是用的stean，也可以启动游戏，就是进不去游戏界面，要进游戏界面的时候就自己消失了

**Comment by HustCoderHu** [comment]
游戏页面显示出来之前，进程里看看有没有nxsteam这个玩意，我这边到界面出来之前也要一段时间，感觉跟线路情况有关

**Comment by liusy-jz** [comment]
我这边是Nexon stream connector出来了，然后这个进程不到几秒钟就意外终止了，难道与我SS是全局模式有关？

**Comment by HustCoderHu** [comment]
你开的全局?。。。我用的不代理国内ip。。。
开sstap的时候你还开了 ss client?

**Comment by liusy-jz** [comment]
之前用sstap没试成功，后来都是直接用ss试的，那我回头用sstap再试试，谢谢你了。

**Comment by MechanicalBrain** [comment]
楼上大佬，有没有gms规则啊

**Comment by HustCoderHu** [comment]
我直接国内白名单模式了，没有专门去整gms规则了
