### ISSUE TITLE
就一个！求增加steam客户端跨区登录的规则，好多游戏要steam跨区登录

### ISSUE THREAD

**Issue by laozhou125** [FQrabbit/SSTap-Rule#73]
**需要增加游戏\程序名字**
如``steam 客户端

**该游戏\程序的运行环境**
如

``PC``

**该游戏\程序哪部分需要代理**
如
``程序需要``

**特殊情况**
好多游戏要steam跨区登录才能下载，安装，购买游戏，和启动游戏

**Comment by noir1216** [comment]
游戏锁激活和客户端有关，不过可以用steamcn大佬搭建的云激活解决。
但是游戏锁运行就和steam客户端没关系了，需要单独把你锁运行的游戏进行代理才行。
我以前买的俄区老滚5就是。
