### ISSUE TITLE
你好，请问如何设置upup呀，我用来加速命运2总是设置为严格NAT

### ISSUE THREAD

**Issue by githubhao0705** [FQrabbit/SSTap-Rule#78]

**Comment by jason2000915** [comment]
emmm这算sstap的一个bug（作者没来得及实现）吧 NAT永远为严格，想代理对NAT有要求的游戏可以试试Super Socks5cap / sockscap / openV*N（这个不算代理了）等软件

**Comment by shixinwang** [comment]
> 
> 
> emmm这算sstap的一个bug（作者没来得及实现）吧 NAT永远为严格，想代理对NAT有要求的游戏可以试试Super Socks5cap / sockscap / openV*N（这个不算代理了）等软件
 
个人刚刚试了一下
Super Socks5cap / sockscap / 通过 ssr进行连接游戏（荣耀战魂 实际上nat类型并没有改变）  所以。。。
