### ISSUE TITLE
【请更新】英雄联盟台服规则

### ISSUE THREAD

**Issue by lu549772129** [FQrabbit/SSTap-Rule#80]
**问题描述**
在游戏大厅匹配几分钟左右会断，连带着Garena登录器的LOL界面也会提示被断开网络，只要几分钟内匹配到人进了游戏之后，就不会有断的问题了，但是因为大厅是另外一个进程，每次打完一盘回到大厅就是断着的状态（其实刚进游戏没一会大厅就断了），导致每次打完都要从新上号，急匆匆的匹配，不然就会再断，而且台服的大厅是断3秒就不让从连了，很头疼。

ps:朋友是广东电信，跟我一起玩台服，他也会断，而且跟我描述的问题一模一样。
我们同样用香港的SSR线路玩玩美服日服都没有出现问题。

**从哪里开始出现这个问题**
Garena登录器，游戏大厅

**截图**
不知道git怎么提交图片。

**运行环境**
Windows7 x64
北京联通

**Comment by lu549772129** [comment]
哦对 建议把Garena登录器的规则与台服整合一下。

**Comment by AmazingDM** [comment]
已更 待测
