### ISSUE TITLE
申请添加永恒之塔台服

### ISSUE THREAD

**Issue by Insightfy** [FQrabbit/SSTap-Rule#82]
**需要增加游戏\程序名字**
永恒之塔台服

**该游戏\程序的运行环境**
如
PC

**该游戏\程序哪部分需要代理**
如
整个游戏\程序都需要`

**特殊情况**
如果还有特殊想说明的请在这里描述.
感谢兔兔已经各位大佬的无私奉献

**Comment by AmazingDM** [comment]
已添加
