### ISSUE TITLE
导入CSGO的规则后，在下拉列表里找不到

### ISSUE THREAD

**Issue by xxxdd360noscope** [FQrabbit/SSTap-Rule#83]
导入CSGO的规则后，在下拉列表里找不到

![snipaste_2018-11-20_14-21-07](https://user-images.githubusercontent.com/29542203/48755231-9e1ebc80-eccf-11e8-8f15-9c4767bea4c8.png)

``操作系统`` WIN7

**Comment by AmazingDM** [comment]
已修复
