### ISSUE TITLE
"lost ARK"

### ISSUE THREAD

**Issue by Haruter** [FQrabbit/SSTap-Rule#84]
**需要增加游戏\程序名字**
如``CS-GO``

**该游戏\程序的运行环境**
如
``虚拟机``
``局域网其他设备``
``PC``

**该游戏\程序哪部分需要代理**
如
``整个游戏\程序都需要``
``只代理登陆部分``

**特殊情况**
如果还有特殊想说明的请在这里描述.

**Comment by lmc999** [comment]
规则已上传至PR,欢迎测试
https://github.com/FQrabbit/SSTap-Rule/pull/101
