### ISSUE TITLE
天命2规则

### ISSUE THREAD

**Issue by Raki-start** [FQrabbit/SSTap-Rule#89]
**需要增加游戏\程序名字**
如``天命2/命运2（Destiny2）``

**该游戏\程序的运行环境**
如
``PC 暴雪平台``

**该游戏\程序哪部分需要代理**
如
``整个游戏\程序都需要``
**特殊情况**
原来规则里有 只不过打开是一堆乱七八糟的英文 然后导入进去也不能用 求大佬费心添加规则

**Comment by AmazingDM** [comment]
已添加
