### ISSUE TITLE
PUBG-HK-only

### ISSUE THREAD

**Issue by Asion-J** [FQrabbit/SSTap-Rule#9]
23.32.0.0/11
23.48.201.0/24
61.244.0.0/16
61.244.24.0/22
103.44.60.0/22
103.44.61.0/24
103.235.44.0/22
103.235.46.0/24
155.133.244.0/24
175.45.0.0/18
175.45.32.0/19
175.45.42.0/23
谁有多的HK，加几个进去

**Comment by nzcool** [comment]
问题是，感觉用sstap加速效果不是很理想，不知道是不是线路问题。

**Comment by FQrabbit** [comment]
@nzcool 这个和协议本身，以及线路都有关系🤔

**Comment by nzcool** [comment]
我的意思就是说，感觉用ss或是ssr这个本身玩游戏，并不好。速度不行。线路就算不错，感觉还是有点不舒服。
