### ISSUE TITLE
如何删除1.0.9.7以下三个内置规则

### ISSUE THREAD

**Issue by dengandy** [FQrabbit/SSTap-Rule#95]
请求大神：如何删除1.0.9.7以下三个内置规则
全局-内置规则
仅网页浏览器（全局）-内置规则
仅网页浏览器（跳过中国站点）-内置规则
因为只想用来玩游戏，SSTap-beta-setup-1.1.0.1会占用内存过大而掉线。
分享给其他同学用，但只想用于游戏。

如果上述不能做到

请问可以解决SSTap-beta-setup-1.1.0.1因为广告导致占用内存过大的问题吗？

请大神帮忙。。。。

**Comment by sion934** [comment]
暂无相关计划。

**Comment by Raki-start** [comment]
直接rules里删不行么

**Comment by Bornres** [comment]
感觉内置规则很有用。。

**Comment by 1015127214** [comment]
这三个规则能单独下载吗？
