### ISSUE TITLE
泰坦陨落2

### ISSUE THREAD

**Issue by Raki-start** [FQrabbit/SSTap-Rule#98]
**需要增加游戏\程序名字**
``泰坦陨落2``

**该游戏\程序的运行环境**
``PC/EA``

**该游戏\程序哪部分需要代理**
``整个游戏\程序都需要``

**特殊情况**
EA将要凉凉的游戏 求各位大佬们费心添加一下
各位大佬如果不嫌麻烦可以出个教程教我等萌新添加规则

**Comment by AmazingDM** [comment]
已加
