### ISSUE TITLE
请求添加steam怪物猎人世界规则

### ISSUE THREAD

**Issue by baloneyspeaker** [FQrabbit/SSTap-Rule#99]
**问题描述**
跪求添加steam怪物猎人世界规则

**从哪里开始出现这个问题**
跟好友联机一会就5058

**运行环境**
win10；长城宽带（居住地区只能办理这个）

**Comment by FQrabbit** [comment]
@homever 玩的都是有钱人大佬，所以没钱的我们都没做

**Comment by baloneyspeaker** [comment]
T﹏T尝试过教程的那种用别的加速器导出规则过，但是效果并不好。

FQrabbit <notifications@github.com>于2019年2月2日 周六上午10:08写道：

**Comment by lingyu15** [comment]
@homever 肝不了，肾不好，肾还是要的
